Default workdir clean on demo server
aiidalab/aiidalab-qe pull request #1007
Opened 2024-12-20 09:30 UTC by edan-bainglass

Closes #1006

This PR implement a simple file-based (YAML) system for defining app configuration. A `on_demo_server` attribute is added to the configuration for demo server detection. This is read in the `aiidalab_qe.config.environment` module and used by the advanced model to set the default value of the clean workdir state variable.

2024-12-20 11:23 UTC, superstar54 requested changes
I suggest using a general config file, instead of hard-coding the `demo server` inside the app. See the suggested code.

2024-12-20 11:23 UTC, superstar54 commented on src/aiidalab_qe/config/environment.py
> +    return False
```suggestion
def load_config():
    config = {}
    if CONFIG_PATH.exists():
        with CONFIG_PATH.open("r") as file:
            config = yaml.safe_load(file)
    return config
```

2024-12-20 11:23 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/advanced/model.py
> +from aiidalab_qe.config.environment import on_demo_server
```suggestion
from aiidalab_qe.config.environment import load_config
```

2024-12-20 12:25 UTC, edan-bainglass commented
Thanks @superstar54. Good suggestion! I'll implement it in a bit. 

Just to clarify, I would then do `get_config().get("on_demo_server", False)`, yeah?

2024-12-20 12:54 UTC, superstar54 commented
> Just to clarify, I would then do `get_config().get("on_demo_server", False)`, yeah?

I would not include any demo server related to the app.
```python
clean_workdir = tl.Bool(load_config().get("clean_workdir", False))
```

2024-12-20 13:01 UTC, edan-bainglass commented
> > Just to clarify, I would then do `get_config().get("on_demo_server", False)`, yeah?
> 
> I would not include any demo server related to the app.
> 
> ```python
> clean_workdir = tl.Bool(load_config().get("clean_workdir", False))
> ```

Oh I see. In that case, I wouldn't even use a new config file. I would just use the qeapp.yaml file, no?

2024-12-20 13:38 UTC, edan-bainglass commented
> > > Just to clarify, I would then do `get_config().get("on_demo_server", False)`, yeah?
> > 
> > 
> > I would not include any demo server related to the app.
> > ```python
> > clean_workdir = tl.Bool(load_config().get("clean_workdir", False))
> > ```
> 
> Oh I see. In that case, I wouldn't even use a new config file. I would just use the qeapp.yaml file, no?

@giovannipizzi can I get your thoughts on this? I can add `clean_workdir` to qeapp.yaml, which is already being used for various defaults. But this does not provide auto detection for the demo server. It just means that when we deploy on the demo server, we need to modify this file. I'm not sure this is the correct approach, as it means modifying a tracked file in the actual codebase. I think perhaps it would be better to rely on some external config file, maybe again in /home/user/.aiidalab? 

Note that environment variables didn't work out here. Couldn't get Jupyter to detect them.

2024-12-20 14:19 UTC, giovannipizzi commented
I agree we should not change a file from he installed package. Probably the app should first load the yaml you mention, then allow for an optional override file in the home folder. If present, those variables take precedence, essentially you load both and do a dictionary update before applying (or something like this, this works for simple values, not sure of you also have dictionaries or lists and need more customized overrides).
If not present, no warning is raised, you just use the defaults from the first file in the code base. 

Then, in the deployment you just drop the overrides file with the fee things you want to change.

Would that work?

2024-12-20 15:23 UTC, edan-bainglass commented
> I agree we should not change a file from he installed package. Probably the app should first load the yaml you mention, then allow for an optional override file in the home folder. If present, those variables take precedence, essentially you load both and do a dictionary update before applying (or something like this, this works for simple values, not sure of you also have dictionaries or lists and need more customized overrides). If not present, no warning is raised, you just use the defaults from the first file in the code base.
> 
> Then, in the deployment you just drop the overrides file with the fee things you want to change.
> 
> Would that work?

Possibly. Let me see.

2024-12-23 09:06 UTC, edan-bainglass commented
> > I agree we should not change a file from he installed package. Probably the app should first load the yaml you mention, then allow for an optional override file in the home folder. If present, those variables take precedence, essentially you load both and do a dictionary update before applying (or something like this, this works for simple values, not sure of you also have dictionaries or lists and need more customized overrides). If not present, no warning is raised, you just use the defaults from the first file in the code base.
> > Then, in the deployment you just drop the overrides file with the fee things you want to change.
> > Would that work?
> 
> Possibly. Let me see.

Works like a charm. Matter of fact, this is great for development, as I can have an external config with the simplest settings (no relaxation, fast protocol, clean work directory), saving me clicks and storage!

2024-12-23 10:00 UTC, superstar54 commented on src/aiidalab_qe/app/parameters/__init__.py
> +        - If values are lists, extend the list in `d1`.
I suggest overriding the list instead of extending it, which is better controllable for the following reasons:
- the user can override the list entirely.
- when recursive merge multiple times, it will not add duplicate data.

2024-12-23 10:55 UTC, superstar54 approved these changes
Nice!

2024-12-23 10:57 UTC, merged