Replace advanced settings override checkbox with a reset button
aiidalab/aiidalab-qe pull request #1012
Opened 2024-12-20 18:47 UTC by edan-bainglass

This PR discards the override mechanism in the advanced settings panel. All widgets are enabled and may be overridden by the user. A reset button is added in place of the override checkbox to reset the advanced settings to their defaults w.r.t the basic settings and selected structure.

Closes #991

2024-12-23 07:14 UTC, AndresOrtegaGuerrero commented
I would suggest , that you add a message to tell the user that if the calculation is magnetic  "Set the magnetization in advanced settings to select your desired magnetic configuration."

2024-12-23 07:58 UTC, superstar54 requested changes
Thanks for the work! I found two small issues when resetting to the default
- the kpoint is reset to 0.1 when protocol is moderate (should be 0.15)
- the Wavefunction cutoff and Charge density cutoff are not reset.

2024-12-23 17:06 UTC, edan-bainglass commented
> Thanks for the work! I found two small issues when resetting to the default
> 
> * the kpoint is reset to 0.1 when protocol is moderate (should be 0.15)
> * the Wavefunction cutoff and Charge density cutoff are not reset.

Thanks @superstar54. I'll take a look.

2024-12-24 08:42 UTC, edan-bainglass commented
> > Thanks for the work! I found two small issues when resetting to the default
> > 
> > * the kpoint is reset to 0.1 when protocol is moderate (should be 0.15)
> > * the Wavefunction cutoff and Charge density cutoff are not reset.
> 
> Thanks @superstar54. I'll take a look.

@superstar54 I can't reproduce your issues. Everything resets as it should on my end.

2024-12-24 08:57 UTC, edan-bainglass commented
> I would suggest , that you add a message to tell the user that if the calculation is magnetic "Set the magnetization in advanced settings to select your desired magnetic configuration." Since the default is 0 , so it wont have magnetization

![image](https://github.com/user-attachments/assets/494fe5f8-f9a1-4c69-9f27-769d6eb34aed)

2024-12-24 09:33 UTC, edan-bainglass commented
> > > Thanks for the work! I found two small issues when resetting to the default
> > > 
> > > * the kpoint is reset to 0.1 when protocol is moderate (should be 0.15)
> > > * the Wavefunction cutoff and Charge density cutoff are not reset.
> > 
> > 
> > Thanks @superstar54. I'll take a look.
> 
> @superstar54 I can't reproduce your issues. Everything resets as it should on my end.

@AndresOrtegaGuerrero can you check as well?

2024-12-24 09:42 UTC, superstar54 commented
> the Wavefunction cutoff and Charge density cutoff are not reset.

I still has this.

2024-12-25 09:01 UTC, edan-bainglass commented
> > the Wavefunction cutoff and Charge density cutoff are not reset.
> 
> I still have this.

Okay @superstar54. This should be resolved now. Please retest 🙏

2024-12-25 09:48 UTC, AndresOrtegaGuerrero commented
If I select a different Pseudos set, like Pseudo Dojo, and adjust the cutoffs, clicking the reset button not only resets the cutoffs but also switches back to SSSP efficiency. Shouldn't it retain the selected Pseudos and only reset the cutoffs?

2024-12-25 10:00 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced/advanced.py
> +            description="Tick to clean-up the work directory after the calculation is finished",
Tick to delete the work directory after the calculation finishes.

2024-12-25 10:49 UTC, edan-bainglass commented on src/aiidalab_qe/app/configuration/advanced/advanced.py
> +            description="Tick to clean-up the work directory after the calculation is finished",
It is left empty on purpose, so we can add a label of the same text on the right.

2024-12-25 10:51 UTC, edan-bainglass commented
> 
> If I select a different Pseudos set, like Pseudo Dojo, and adjust the cutoffs, clicking the reset button not only resets the cutoffs but also switches back to SSSP efficiency. Shouldn't it retain the selected Pseudos and only reset the cutoffs?

The reset button returns everything back to what it was w.r.t the structure and protocol. For a moderate protocol, the default is SSSP efficiency.

2024-12-25 11:42 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced/advanced.py
> +            description="Tick to clean-up the work directory after the calculation is finished",
I meant that the description text should be maybe be "Tick to delete the work directory after the calculation finishes."

2024-12-25 11:45 UTC, AndresOrtegaGuerrero commented
> > If I select a different Pseudos set, like Pseudo Dojo, and adjust the cutoffs, clicking the reset button not only resets the cutoffs but also switches back to SSSP efficiency. Shouldn't it retain the selected Pseudos and only reset the cutoffs?
> 
> The reset button returns everything back to what it was w.r.t the structure and protocol. For a moderate protocol, the default is SSSP efficiency.

Yes, it did feel a bit odd to go there (change the pseudos selection) while making the change, but you're right — it should have that behavior since that's how it has always worked.

2024-12-25 12:06 UTC, edan-bainglass commented on src/aiidalab_qe/app/configuration/advanced/advanced.py
> +            description="Tick to clean-up the work directory after the calculation is finished",
Oh my bad, the git diff was confusing. Okay, yeah, this has a description and you're suggesting to reword. I agree if that's what actually happens. If the user ticks this, does it delete the workdir, or does it just clean it?

2024-12-25 12:13 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced/advanced.py
> +            description="Tick to clean-up the work directory after the calculation is finished",
It deletes the work directory. I think some users might find the term "clean up" confusing, so it's better to clearly state that it deletes the directory. This clarification will also be useful for the post-processing calculations. The clearer, the better.

2024-12-25 13:22 UTC, AndresOrtegaGuerrero approved these changes
LGTM!  thank you @edan-bainglass

2024-12-26 08:08 UTC, superstar54 approved these changes
LGTM! Thanks for the nice work!

2024-12-26 08:10 UTC, merged