Add smearing width and type set
aiidalab/aiidalab-qe pull request #158
Opened 2021-11-19 13:33 UTC by unkcpz

The WorkChain has also changed so the workchain need to be released and change the dependency info. 
@mbercx What is the correct workflow to make the PR when the work chain is changed? Should those change in another PR and release first?

2021-11-23 10:56 UTC, mbercx commented
> What is the correct workflow to make the PR when the work chain is changed? Should those change in another PR and release first?

Not sure that's necessary? I haven't made any changes to the work chain since it was placed in the `src` directory, but I'd say it's fine to have a single PR for changing both the app and work chain, unless @csadorf objects?

2021-11-23 11:50 UTC, mbercx requested changes
Thanks @unkcpz! I've given the implementation a test run and left some comment regarding the frontend.

I'm also considering we should maybe add two headers in the "Advanced settings". Maybe

* Functional and pseudopotential
* Brillouin zone sampling

What do you think?

2021-11-23 11:50 UTC, mbercx commented on aiidalab_qe/steps.py
> +        The k-points mesh density of scf calculation is set by the chosen <b>protocol</b>.
```suggestion
        The k-points mesh density of the SCF calculation is set by the chosen <b>protocol</b>.
```

2021-11-23 11:50 UTC, mbercx commented on aiidalab_qe/steps.py
> +            description="Override default smearing setting.",
Maybe we can just shorten the description of both this checkbox and the k-points one to "Override" in boldface. Should be clear and more succinct.

2021-11-23 11:50 UTC, mbercx commented on aiidalab_qe/steps.py
> +            description="Degauss (Ry):",
Although these are definitely "expert" settings, maybe we can use the more generic "Smearing width" instead of the name of the QE input?

2021-11-23 11:50 UTC, mbercx commented on aiidalab_qe/report.py
> +        degauss = None
Currently, the report shows `None` for the smearing type and width when they are not overridden. Best to grab these from the work chain or protocol in case they are not specifically set by the user.

2021-11-23 11:50 UTC, mbercx commented on aiidalab_qe/steps.py
> +        self.smearing = ipw.Dropdown(
Maybe it's more natural to put the smearing type first, then the smearing width?

2021-11-23 14:21 UTC, unkcpz reviewed
Thanks @mbercx !
I update the commits and accept most of your advice. Could you have another around look at this?

2021-11-23 14:21 UTC, unkcpz commented on aiidalab_qe/report.py
> +        degauss = None
Yes, I think it is hard to get it from the workchain because the default value of these variables are set in the base calculation. If we run band structure and pdos at the same time in the future, they both set the degauss and smearing in the innermost base calculation by default then we don't know which one to read is more proper. 

I now hard code the value from the protocol, but maybe there is a util function (not the one in `ProtocolMixin` have to call with `cls`) that can extract the value from the protocol?

2021-11-23 15:25 UTC, mbercx commented on aiidalab_qe/steps.py
> +            description="Override default smearing setting.",
No worries, boldface is not really critical. I forgot how tricky it can be to get the widget format exactly as you want it sometimes. ;)

2021-11-23 15:26 UTC, mbercx commented on aiidalab_qe/steps.py
> +            description="Degauss (Ry):",
Agreed! 👍

2021-11-26 12:17 UTC, mbercx commented on aiidalab_qe/report.py
> +        degauss = None
Sorry for the slow response to this one. Wanted to look into this more closely but got distracted by other work.

1. Regarding getting the values from the work chain: I preferred this method for the report, since then we'd actually see the values that were used, which was useful as an extra check to find bugs. I don't immediately see the issue with running both the bands and pdos. We'd use the same smearing and `degauss` for all SCF calculations, no?
2. I now use the `PwBaseWorkChain.get_protocol_inputs()` method for obtaining the defaults for the k-points density:

https://github.com/aiidalab/aiidalab-qe/blob/b5c6bcbf0392a108178c8ab6ac0fe87365dd0615/aiidalab_qe/steps.py#L276-L282

This is the easiest way to obtain the defaults for each protocol, I think. For example, to get the smearing:

```python
PwBaseWorkChain.get_protocol_inputs('moderate')['pw']['parameters']['SYSTEM']['smearing']
```

Is this the one you wanted to avoid, or?

2021-12-08 12:48 UTC, csadorf commented
> > What is the correct workflow to make the PR when the work chain is changed? Should those change in another PR and release first?
> 
> Not sure that's necessary? I haven't made any changes to the work chain since it was placed in the `src` directory, but I'd say it's fine to have a single PR for changing both the app and work chain, unless @csadorf objects?

Indeed, unless I am missing something, adding a new work chain is a two-step process, because one has to update the dependency URL to something that has already been pushed:
https://github.com/aiidalab/aiidalab-qe/blob/b5c6bcbf0392a108178c8ab6ac0fe87365dd0615/setup.cfg#L31

In practice, I would recommend to

1. Manually install the work chain during development, then
2. Push both the new work chain and related changes with dependency set to the next (pre-)release.

The tests will almost certainly have to fail during the transition phase.

2021-12-21 14:29 UTC, unkcpz commented on aiidalab_qe/report.py
> +        degauss = None
Almost forget about this PR 🥲. I update it as advised, try to finish this.

2021-12-21 14:30 UTC, unkcpz commented
@mbercx Have a final look when you back from holiday next year 😄

2022-01-25 19:32 UTC, mbercx commented
@unkcpz sorry for leaving this PR in the cold for so long! If you rebase and fix the conflicts I'll give it a final review so we can wrap this up.

2022-01-26 13:53 UTC, unkcpz commented
Hi @mbercx, I rebase the PR and think it is good to have another round.

2022-01-26 14:04 UTC, unkcpz commented
When looking at the original feature request https://github.com/aiidalab/aiidalab-qe/issues/64
In this PR I did nothing to distinguish the METAL and insulator.

2022-02-21 14:24 UTC, mbercx approved these changes
Thanks @unkcpz! Just a few final comments. I'll already approve and let you decide whether it makes sense to already link the protocol to the default smearing values. Now the smearing settings are the same for all protocols, so perhaps adding extra code isn't sensible at this point.

2022-02-21 14:24 UTC, mbercx commented on aiidalab_qe/steps.py
> +        Untick the box to override the default.
With the current interfact the user has to tick the box to override.

2022-02-21 14:24 UTC, mbercx commented on aiidalab_qe/steps.py
> +        Untick the box to override the default.
This should also be adapted for the k-points override. :)

2022-02-21 14:24 UTC, mbercx commented on aiidalab_qe/steps.py
> +    degauss_default = traitlets.Float(default_value=0.01)
Here the defaults are still hard coded instead of retrieved from the protocol. Currently the defaults don't really have to be linked to the protocol, since the smearing is the same for all protocols. This might change in the future, however.

2022-02-25 11:29 UTC, unkcpz commented on aiidalab_qe/steps.py
> +    degauss_default = traitlets.Float(default_value=0.01)
In the `Configuration` it is linked to the protocol already, it will change when you choose a different protocol. Here, I think it is fine to have a default value for the class.

2022-02-25 11:29 UTC, unkcpz commented on aiidalab_qe/steps.py
> +        Untick the box to override the default.
Good catch! I will change this.

2022-02-25 11:55 UTC, unkcpz commented on aiidalab_qe/steps.py
> +    degauss_default = traitlets.Float(default_value=0.01)
I see your point. Yes, it is somehow not linked to the protocol. I have a fake illusion I have done that :1

2022-02-25 11:58 UTC, unkcpz commented on aiidalab_qe/steps.py
> +    degauss_default = traitlets.Float(default_value=0.01)
Wait, I think there are duplicate codes in both `KpointSetting` and `ConfigureQeAppStep` that link to the protocol settings.

2022-02-25 14:58 UTC, mbercx commented on aiidalab_qe/steps.py
> +    degauss_default = traitlets.Float(default_value=0.01)
You did do it for the report ^^

It's not necessary to implement the same logic as was implemented for the `kpoints-distance` though, since the smearing settings are the same for all protocols and not likely to change soon.

2022-02-25 15:05 UTC, unkcpz commented on aiidalab_qe/steps.py
> +    degauss_default = traitlets.Float(default_value=0.01)
> You did do it for the report ^^

True. You have a good memory. 
Anyway, I copy and paste the logic from kpoint-distance default, it should works well. Could you have a final look at the last commit and we merge this?

2022-02-25 15:28 UTC, mbercx commented on aiidalab_qe/steps.py
> +    degauss_default = traitlets.Float(default_value=0.01)
I didn't test the latest changes, but it all looks good! Go ahead and merge. 🚀

2022-02-25 15:40 UTC, merged