Running PDOS workchain and plot bands + pdos
aiidalab/aiidalab-qe pull request #159
Opened 2021-11-19 17:06 UTC by unkcpz

- [ ] The PR is blocked by https://github.com/aiidalab/aiidalab-widgets-base/issues/262 since pdos workchain have outputs in namespace.
- [ ] Clean `qe.ipynb`
- [x] add checkbox and able to run PDOS workchain when the box checked
- [ ] newly added `pdos` and `projwfc` code setting will break backward compatibility. 
- [ ] Dependency: new `aiida-quantumespresso` plugin otherwise will raise `tetrahydro` setting error.
- [x] bands+pdos plot

2021-11-25 14:37 UTC, mbercx commented
@unkcpz `aiida-quantumespresso` 3.5.0 is now released with the fix you need for the `tetrahedra` override, so you can update the dependency.

2021-11-25 16:24 UTC, unkcpz commented
For the band structure output view widget tab name, it is only a good to have feature. So I think this PR is ready to review.

2021-11-26 14:39 UTC, mbercx requested changes
Thanks @unkcpz! Just left some minor comments. Two other things:

1. The dependency version of `aiida-quantumespresso` doesn't seem to be upgraded to `3.5.0`?
2. When I refresh the app, the `dos.x` and `projwfc.x` codes weren't automatically set to the defaults. But this is most likely because I didn't install the app with this branch, since if I understand correctly the default are set upon installation.

2021-11-26 14:39 UTC, mbercx commented on aiidalab_qe/steps.py
> +                ipw.HBox(children=[ipw.HTML("<b>PDOS</b>"), self.pdos_run]),
```suggestion
                ipw.HBox(children=[ipw.HTML("<b>Projected density of states</b>"), self.pdos_run]),
```

2021-11-26 14:39 UTC, mbercx commented on aiidalab_qe/node_view.py
> +        self.result_tabs.set_title(2, "Band Structure and DOS")
This doesn't seem to fit in the tab header anymore. 😅 Maybe use "Electronic Structure"? And/or we have to tweak the tab header widths.

Also note that the original tab title still is "Band structure (n/a)".

2021-11-29 17:49 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +        self.result_tabs.set_title(2, "Band Structure and DOS")
Yes, agree that the name 'Electronic Structure' is a good idea.

2021-11-29 17:52 UTC, unkcpz commented
> The dependency version of aiida-quantumespresso doesn't seem to be upgraded to 3.5.0?

Ah, true. I forget to push the latest commits with some other changes.

> I refresh the app, the dos.x and projwfc.x codes weren't automatically set to the defaults. But this is most likely because I didn't install the app with this branch, since if I understand correctly the default are set upon installation

This is an issue, I think the dos.x and projwfc.x were installed with pw.x. Just not sure which line of code influence this default fresh and setting behavior.  I need to check this more.

2021-12-08 13:34 UTC, csadorf requested changes

2021-12-08 13:34 UTC, csadorf commented on aiidalab_qe/steps.py
>                  "calculation or both."
```suggestion
            "Select either a structure relaxation method or at least one of the "
            "the bands or the PDOS calculations or both."
```

2021-12-08 13:34 UTC, csadorf commented on aiidalab_qe/steps.py
> +                pass
I would suggest that we move the utility `_load_code()` function from line 582/561 into the module namespace and then use it here as well for improved readability.

```suggestion
        self.codes_selector.pw.selected_code = _load_code(parameters["pw_code"])
        self.codes_selector.dos.selected_code = _load_code(parameters["dos_code"])
        self.codes_selector.projwfc.selected_code = _load_code(
            parameters["projwfc_code"]
        )
```

The function itself could be expressed a bit more succinctly like this:

```python
from contextlib import suppress

def _load_code(code):
    with suppress(NotExistent, ValueError):
        return load_code(None)
```

2021-12-08 13:34 UTC, csadorf commented on aiidalab_qe/steps.py
> +            builder.pop("pdos")
Do we actually need the `run_pdos` (and the `run_bands`) variable? And do we need to remove them from the `parameters` dict? This would also work, right?
```suggestion
        if not parameters["run_pdos"]:
            builder.pop("pdos")
```

2021-12-09 09:21 UTC, unkcpz commented
I make all the changes you mentioned in the review, but I need to give it a final run and test. Will request another review after it.

2021-12-09 09:21 UTC, unkcpz commented on aiidalab_qe/steps.py
> +                pass
Looks very cool! changed.

2021-12-09 09:22 UTC, unkcpz commented on aiidalab_qe/steps.py
> +            builder.pop("pdos")
Will try whether not pop in from parameters works.

2022-01-05 13:05 UTC, unkcpz commented
> When I refresh the app, the dos.x and projwfc.x codes weren't automatically set to the defaults. But this is most likely because I didn't install the app with this branch, since if I understand correctly the default are set upon installation.

I am not sure since I create a new container with install the app with this branch but got the QE setup error `'NoneType' object has no attribute 'uuid'`.  @csadorf I am a bit lot in the `QESetupWidget` code. Could you tell me where this error might come from?

Moreover, I can not figure out how to retrigger the codes install and code setup or maybe just manually set the related parameters for code `dos` and `projwfc`? I don't think create a new container to get the code set is a convenient way to do this.

2022-01-07 10:37 UTC, unkcpz commented
The only block of this is the code selector not setting the default code as expected.

2022-01-07 10:39 UTC, csadorf commented
> The only block of this is the code selector not setting the default code as expected.

I will try to reproduce the issue.

2022-01-07 11:21 UTC, csadorf commented
I think we should have a bot that automatically generates the following command for us 😁 :
```console
aiidalab install quantum-espresso@git+https://github.com/unkcpz/aiidalab-qe@pdos --yes
```

2022-01-07 11:45 UTC, csadorf commented
I am still investigating, but I will start to try to answer some of your questions.

> > When I refresh the app, the dos.x and projwfc.x codes weren't automatically set to the defaults. But this is most likely because I didn't install the app with this branch, since if I understand correctly the default are set upon installation.
> 

I just installed this app version in a new environment and did not experience any issues with the qe installation. However, I also found that the codes were not selected by default.

> I am not sure since I create a new container with install the app with this branch but got the QE setup error `'NoneType' object has no attribute 'uuid'`. @csadorf I am a bit lot in the `QESetupWidget` code. Could you tell me where this error might come from? 

I am not able to reproduce this problem.

> The thing confuse me is in the method `SubmitQeAppWorkChainStep:_auto_select_code` it calls `get_input_parameters` which need the corresponding code selector being set?

Indeed, I am not exactly sure how that currently works either. I will keep investigating.

> Moreover, I can not figure out how to retrigger the codes install and code setup or maybe just manually set the related parameters for code `dos` and `projwfc`? I don't think create a new container to get the code set is a convenient way to do this.

To re-trigger the setup process just remove the AiiDA codes with the corresponding labels (pw-6.7@localhost etc.) and optionally also remove the `quantum-espresso-6.7` conda environment.

2022-01-07 13:52 UTC, csadorf commented
I can confirm that the pw.x code is currently not automatically selected, not even on the "master" branch. Trying to figure out when and how this regression was introduced.

2022-01-07 16:05 UTC, csadorf commented
Please rebase this branch after merging #167 .

2022-01-07 16:06 UTC, csadorf requested changes
Please apply my suggestion on how to fix the remaining code selection issue and then rebase on master after #167 has been merged.

2022-01-10 09:47 UTC, unkcpz commented
Hi @csadorf, I have run `bumpver update` to create a new `tag: v22.01.0`. I need then push this tag? Or do this after pr https://github.com/aiidalab/aiidalab-qe/pull/169 merged?

2022-01-10 10:14 UTC, csadorf commented
> Hi @csadorf, I have run `bumpver update` to create a new `tag: v22.01.0`. I need then push this tag? Or do this after pr #169 merged?

As discussed offline, we should not bump the version on the feature branch. That said, `bumpver` should have pushed the tag, not sure why that did not happen.

2022-01-10 11:47 UTC, csadorf requested changes
I tests this on the latest aiidalab version and everything appeared to work fine, however the DOS and the Projwfc calculations never appeared to fully finish:
![Screen Shot 2022-01-10 at 12 42 01](https://user-images.githubusercontent.com/1441208/148760668-819c99ab-193d-4f45-978b-f6602dfcf7b4.png)

That's despite the fact the logs appear completed:
![Screen Shot 2022-01-10 at 12 42 08](https://user-images.githubusercontent.com/1441208/148760708-0fed1a18-f513-4b29-b57a-0e4e0f0a03e4.png)


I have one last question regarding the widgets base requirement, but other than that this is good to go.

2022-01-10 11:49 UTC, csadorf commented on setup.cfg
>      aiidalab-widgets-base~=1.1
This is almost certainly the case, see also issue: https://github.com/aiidalab/aiidalab-qe/issues/172

Because of this issue, I was not able to retrieve the previously completed workchain.

2022-01-10 13:27 UTC, unkcpz commented on setup.cfg
>      aiidalab-widgets-base~=1.1
Thanks for testing @csadorf . I think this is the reason for the problem.

2022-01-17 18:31 UTC, csadorf commented on setup.cfg
>      aiidalab-widgets-base~=1.1
@unkcpz Version 1.2.0 was just released: https://github.com/aiidalab/aiidalab-widgets-base/releases/tag/v1.2.0

```suggestion
    aiidalab-widgets-base~=1.2,>=1.2.0
```

2022-01-17 22:16 UTC, unkcpz commented on setup.cfg
>      aiidalab-widgets-base~=1.1
Thanks! Changed, good to go.

2022-01-19 17:56 UTC, csadorf approved these changes
I reviewed the code and just ran a pdos work chain for testing on Si.
![Screen Shot 2022-01-19 at 18 54 57](https://user-images.githubusercontent.com/1441208/150186984-07e63c11-2d5d-481e-828f-bd42bbf35df7.png)

Everything appears to be working. 👍

2022-01-19 18:18 UTC, merged