Move computational resources selection into a separate step.
aiidalab/aiidalab-qe pull request #178
Opened 2022-01-18 13:43 UTC by yakutovicha

2022-01-19 11:21 UTC, mbercx requested changes
Thanks @yakutovicha! I gave the PR a first test run and left some comments. I think we still need to improve the resource selection for remote computers, but perhaps I can work on this in a separate PR.

2022-01-19 11:21 UTC, mbercx commented on aiidalab_qe/steps.py
>      def _get_default_num_mpi_tasks(self):
This may be outside the scope of this PR, but for a remote machine like Eiger the default number of MPI tasks should probably be set to `Computer.get_default_mpiprocs_per_machine()`. Also, currently the max number of MPI tasks is set to 100, so I can't even select the optimal value of 128 for Eiger.

2022-01-19 11:21 UTC, mbercx commented on aiidalab_qe/steps.py
> +                self._submission_blocker_messages.value = """
This message no longer disappears when the user reconfigures the work chain to actually run something. Probably have to set the `self._submission_blocker_messages.value` to `None` in the `else` clause, or also use a `_identify_submission_blockers` method as for the `SubmitQeAppWorkChainStep`.

2022-01-19 12:09 UTC, yakutovicha commented on aiidalab_qe/steps.py
> +                self.tab,
Or, as an option, we just remove the expert mode button? The expert settings are on the second tab, maybe there is no reason to hide them with a button?

2022-01-19 12:23 UTC, yakutovicha commented on aiidalab_qe/static/welcome.jinja
> +    <li style="padding-top: 2px; padding-bottom: 2px;">✔️ <b>Step 5:</b> Look at the results!</li>
I am generally not good at writing nice text. I just wanted to emphasize that this part might be slightly adapted. Suggestions are welcome :)

2022-01-19 12:29 UTC, mbercx commented on aiidalab_qe/steps.py
> +                self.tab,
Yeah, at this point this makes sense. Initially we had a lot more tabs that were added in expert mode, but now the button has become a bit unnecessary... What do you think, @csadorf?

2022-01-19 12:30 UTC, mbercx commented on aiidalab_qe/static/welcome.jinja
> +    <li style="padding-top: 2px; padding-bottom: 2px;">✔️ <b>Step 5:</b> Look at the results!</li>
I'd just drop the 5th step and make it a simple 4-step process. :)

2022-01-19 12:51 UTC, csadorf commented on aiidalab_qe/steps.py
> +                self.tab,
We should remove the expert button.

2022-01-19 13:10 UTC, mbercx commented on aiidalab_qe/steps.py
> +                self.tab,
Note that this PR will also then close #109

2022-01-19 17:27 UTC, yakutovicha commented on aiidalab_qe/static/welcome.jinja
> +    <li style="padding-top: 2px; padding-bottom: 2px;">✔️ <b>Step 5:</b> Look at the results!</li>
Done in 33da89f98f9092efb4102628ab7aa6031c9e3d68

Today I learned that 4 steps are the limit for simplicity!

2022-01-19 17:30 UTC, yakutovicha commented on aiidalab_qe/steps.py
> +                self.tab,
> Note that this PR will also then close #109

noted, thanks!

2022-01-19 17:37 UTC, yakutovicha commented on qe.ipynb
>      "        ('Submit work chain', submit_qe_app_work_chain_step),\n",
done

2022-01-19 17:46 UTC, yakutovicha commented on aiidalab_qe/steps.py
> +                self.tab,
done.

2022-01-19 17:49 UTC, yakutovicha commented on aiidalab_qe/steps.py
> +                self._submission_blocker_messages.value = """
fixed.

2022-01-19 17:56 UTC, yakutovicha commented on aiidalab_qe/steps.py
>      def _get_default_num_mpi_tasks(self):
> This may be outside the scope of this PR, but for a remote machine like Eiger the default number of MPI tasks should probably be set to `Computer.get_default_mpiprocs_per_machine()`.

That is not always true, I guess. If the structure is too small, running on all 128 CPUs will result in a failure.

>  Also, currently the max number of MPI tasks is set to 100, so I can't even select the optimal value of 128 for Eiger.

Sorry, cannot find it. Where is it set to 100?

2022-01-19 21:20 UTC, mbercx commented on aiidalab_qe/steps.py
>      def _get_default_num_mpi_tasks(self):
> That is not always true, I guess. If the structure is too small, running on all 128 CPUs will result in a failure.

Yeah, I know... Typically you need to add parallellization to make e.g. Si2 work on such a large node. I think we'll need some basic methods to estimate the number of bands/kpoints and come up with some sensible setting to have this run by a layperson. The people in our group should be able to set these appropriately for their tests, however.

> Sorry, cannot find it. Where is it set to 100?

I think it's the default for `BoundedIntText`:

https://github.com/aiidalab/aiidalab-qe/blob/4d81d649fba4f6862aaf624c5579f7714e65f85c/aiidalab_qe/widgets.py#L404-L406

2022-01-20 18:36 UTC, csadorf commented
Create test environment:
```console
aiidalab install quantum-espresso@git+https://github.com/aiidalab/aiidalab-qe@update/move-code-selection-in-separate-step --yes -f
```

2022-01-20 19:33 UTC, csadorf commented
Everything seems to be working. I can approve this PR once the merge conflicts are resolved.

2022-01-21 10:58 UTC, mbercx commented
@csadorf @yakutovicha is this good to merge? Then this afternoon I can work on improving the resource/parallelization GUI.

2022-01-21 11:00 UTC, yakutovicha commented
> @csadorf @yakutovicha is this good to merge? Then this afternoon I can work on improving the resource/parallelization GUI.

I just got a reply from @csadorf that he is fine with merging it.

2022-01-21 11:01 UTC, merged