Limit MPI ranks for `projwfc.x` and `dos.x`
aiidalab/aiidalab-qe pull request #193
Opened 2022-01-25 20:44 UTC by mbercx

Currently the `PdosWorkChain` runs the `projwfc.x` and `dos.x`
calculations with the full number of MPI ranks specified by the user,
without any kind of parallelization. This can cause failures when the
number of MPI ranks exceeds the number of FFT slabs in the
decomposition.

Here we use the same parallelization settings for the `projwfc.x`
calculation. For the `dos.x`, there is no parallellization implemented,
but this post-processing step is typically very fast, so we simply limit
the number of MPI ranks to the value that we used to set the default
number of `npools`.

2022-01-25 21:50 UTC, unkcpz requested changes
Thanks @mbercx

I give it a quick look. Going to have a run test after.

2022-01-25 21:50 UTC, unkcpz commented on aiidalab_qe/steps.py
>          def update_builder(buildy, resources, npools=None):
What is the 'buildy'? I don't think this will affect by the scope of variable `builder` outside this local function. I guess you mean to say 'beauty' or 'buddy'? 🤣

2022-01-25 21:50 UTC, unkcpz commented on aiidalab_qe/steps.py
> +                        v["settings"] = Dict(dict={"cmdline": ["-nk", str(npools)]})
In this case if `npools` is `None`. Might be problematic.

2022-01-25 21:50 UTC, unkcpz commented on aiidalab_qe/steps.py
> +                        continue
Why `continue` the loop?

2022-01-25 22:30 UTC, mbercx commented on aiidalab_qe/steps.py
>          def update_builder(buildy, resources, npools=None):
It doesn't affect the scope, but I was still apprehensive towards using builder to distinguish it. Happy to change it to `builder` though. ^^

2022-01-25 22:32 UTC, mbercx commented on aiidalab_qe/steps.py
> +                        v["settings"] = Dict(dict={"cmdline": ["-nk", str(npools)]})
Fair point! I had set `None` as the default for `npools` when I was testing this function, but forgot to remove it. Will do so now.

2022-01-25 22:34 UTC, mbercx commented on aiidalab_qe/steps.py
> +                        continue
To avoid that the `resources` of `dos` still get updated by the recursive `update_builder` call.

The logic is a bit convoluted now, I know. It can probably be improved. I just wanted to fix this ASAP since anyone that tests the QEapp on Eiger now will probably run into parallelization issues when running the PDOS.

2022-01-25 22:35 UTC, unkcpz commented on aiidalab_qe/steps.py
>          def update_builder(buildy, resources, npools=None):
What about moving the function out and using `builder`?

2022-01-25 22:39 UTC, unkcpz commented on aiidalab_qe/steps.py
> +                        continue
Thanks for the explanation.

> I just wanted to fix this ASAP since anyone that tests the QEapp on Eiger now will probably run into parallelization issues when running the PDOS.

I see, then we leave it as it is and add a detailed comment for this.

2022-01-25 22:44 UTC, mbercx commented on aiidalab_qe/steps.py
>          def update_builder(buildy, resources, npools=None):
The function was a standalone one at the top of the module before, but since it's only used here for now, I thought it better to move it into `submit` so it's easier to spot. Let's just leave `buildy` be, so the scope is clearly different.

Besides, buildy sounds cute, no? 😬

2022-01-26 11:59 UTC, unkcpz commented on aiidalab_qe/steps.py
>          def update_builder(buildy, resources, npools=None):
> Besides, buildy sounds cute, no? 

Indeed~

2022-01-26 11:59 UTC, merged

2022-01-26 12:00 UTC, unkcpz commented
Thanks @mbercx 
I give it a run on eiger and didn't find any issue. Merged.