FIX: Running PDOS for spin-polarised system
aiidalab/aiidalab-qe pull request #206
Opened 2022-02-22 10:08 UTC by mbercx

Fixes #202 

Currently it is not possible to calculate the PDOS for a spin-polarised
system (i.e. setting Magnetism to Ferromagnetic), since the
`QeAppWorkChain` expects the `projections` output from the
`PdosWorkChain`. However, for spin-polarised systems the
`ProjwfcCalculation` returns two outputs: `projectsion_up` and
`projections_down`.

Here we adapt the `QeAppWorkChain` to check for the `projections_up`
output, and in case it is present it will add both `projections_up` and
`projections_down` to the outputs. Otherwise it will only add the
`projections` output (both only in case the `workchain_pdos` was
actually run).

To deal with plotting the corresponding (P)DOS, we simply add the total
DOS up and down states together, and separately add the PDOS orbitals
for the up and down states to the list passed to the `widget-bandsplot`.
Since the widget currently adds all the PDOS of the same orbital types
(s, p, d, f) together, there will currently not be any differentiation
between the up and down states in the visualization. This is something
that will need to be improved on the widget side.

2022-02-25 10:53 UTC, unkcpz commented
Hi @mbercx, thanks for this fix. I find another issue that when running the test on an oxygen structure with the setting `ElectronicType=insulator`, `Magnetism=ferromagnetic`, the workflow failed at a very early stage. 

It is caused by the `occupation=fixed` while no `tot_magnetization` is set in the input file. But can be in another PR.

2022-02-25 11:16 UTC, unkcpz reviewed
@mbercx thanks. I still running some tests on your branch. all looks good to me but some minor questions.

2022-02-25 11:16 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +                (work_chain_node.outputs.projections_down, "dn"),
Very interesting of this `up` and `dn` thing. They are symmetrical with a C2 operation 🤣 
Is this being show in the figure? I like it but I think it is more proper to use the 'mediocre' name `down`. If some users directly download the figure and use it in their paper, they may complain about this 'dn' legend I guess.

2022-02-25 15:00 UTC, mbercx commented on aiidalab_qe/node_view.py
> -        fermi_energy = work_chain_node.outputs.nscf__output_parameters.get_dict()[
It wasn't used, but seems to have been leftover code before we were using pre-commit hooks. 😅

2022-02-25 15:10 UTC, mbercx commented on aiidalab_qe/node_view.py
> +                (work_chain_node.outputs.projections_down, "dn"),
The widget is currently not able to plot spin up/down states. Or, more specifically: It only takes the first character of the orbital name and sums all orbitals that have the same first character in the name together, see:

https://github.com/osscar-org/widget-bandsplot/blob/8cece372479063de3e7a63877a823d2cfb784fc7/widget_bandsplot/bandsplot.py#L81-L89

So the `up` and `dn` are just for show for now. This will need to be fixed at the widget level. Happy to change `dn` to `down` though. ^^

2022-02-25 15:12 UTC, mbercx commented
> It is caused by the occupation=fixed while no tot_magnetization is set in the input file. But can be in another PR

Yeah, this is a known issue, but needs to be fixed in the plugin. Thought I already opened an issue for this, but apparently not. Will do so now.

2022-02-25 15:42 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +                (work_chain_node.outputs.projections_down, "dn"),
I see. Once you rebase the branch I will give it another look.

2022-02-25 18:04 UTC, unkcpz requested changes
@mbercx Thanks! I still have some minor questions. Bit almost there I think.

2022-02-25 18:04 UTC, unkcpz commented on src/aiidalab_qe_workchain/__init__.py
>              self.out("dos", self.ctx.workchain_pdos.outputs.dos__output_dos)
I think we are safe to replace these double underscore here too.

2022-02-25 18:05 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +            for orbital, pdos, energy in projections.get_pdos():
Hmmmm... By checking the QeApp WorkChain, this seems an `Orbital` datatype? I am a little confused.

2022-03-29 08:07 UTC, mbercx commented
Hmm, it seems to fail to initialize the pre-commit env. I'm also having this issue locally...

2022-03-29 08:47 UTC, unkcpz commented
I think it relates to the issue https://github.com/pre-commit/pre-commit/issues/1651. I encountered it also in my aiida-sssp-workflow repo, add `python -m pip install virtualenv==20.0.33` in pre-commit CI fixes it, but not sure why it happened.

2022-03-29 08:56 UTC, unkcpz commented
@csadorf do you know which cause this pre-commit issue?

2022-03-29 09:49 UTC, csadorf commented
> @csadorf do you know which cause this pre-commit issue?

Yes, I provided some summary [here](https://github.com/materials-marketplace/python-sdk/issues/1#issue-1183323844).

2022-03-30 08:27 UTC, unkcpz commented
Hi @mbercx, the pre-commit issue is temporarily fixed, can you update the branch and try it again. I think there is a minor issue with code which cause other pre-commit fail that is,

```
aiidalab_qe/node_view.py:147:54: F821 undefined name 'ProjectionData'
        for projections, suffix in projection_list:  # type: ProjectionData, str
                                                     ^
1     F821 undefined name 'ProjectionData'
```

2022-04-04 13:23 UTC, unkcpz commented
Hi @mbercx, could you have a look and we finish this PR these days? should be nothing to add and block it.

2022-04-05 09:43 UTC, unkcpz approved these changes
Thanks @mbercx, looks all good.

2022-04-05 09:45 UTC, merged