Fix SubmitQeAppWorkChainStep's `process` trait update.
aiidalab/aiidalab-qe pull request #235
Opened 2022-05-16 14:57 UTC by yakutovicha

fixes #234 

Before one could use the `process` trait of the `SubmitQeAppWorkChainStep`
class one should first update its extras. To ensure this, one needs
to put the process/extras selection under `hold_trait_notifications()`.

2022-05-16 15:08 UTC, unkcpz commented
@yakutovicha thanks a lot! It is very weird that this only shows up after your structure editor PR was merged. 

I test with your branch but I got another error. 

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    604             raise TraitError('The "%s" trait is read-only.' % self.name)
    605         else:
--> 606             self.set(obj, value)
    607 
    608     def _validate(self, obj, value):

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in set(self, obj, value)
    578 
    579     def set(self, obj, value):
--> 580         new_value = self._validate(obj, value)
    581         try:
    582             old_value = obj._trait_values[self.name]

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    610             return value
    611         if hasattr(self, 'validate'):
--> 612             value = self.validate(obj, value)
    613         if obj._cross_validation_lock is False:
    614             value = self._cross_validate(obj, value)

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   1849             return value
   1850         else:
-> 1851             self.error(obj, value)
   1852 
   1853     def info(self):

/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in error(self, obj, value, error, info)
    690                     e = "The '%s' trait expected %s, not %s." % (
    691                         self.name, self.info(), describe("the", value))
--> 692                 raise TraitError(e)
    693 
    694     def get_metadata(self, key, default=None):

TraitError: The 'structure' trait of a BasicStructureEditor instance expected an Atoms or None, not the StructureData <StructureData: uuid: 01732e84-5a48-49d8-869e-985f0f8448ba (pk: 649)>.
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNpdWF1v47oR_SuB-3plWPJH7LwtUvSh2G23zd0WRVFcUBJt06ZIhqTiKBf73ztfkpWL5EWH5JCcOXNm6N8Xbzom493iqfxlEazK
Rx-7xdPvCxWbs8m6yX3Ui6f_Lnab2uTFL4vF_2DekM_e_TYtXayXj8sDDN6RP5XVuvhR9y73Dy_fvj_8JZqHLyE-7B9Wh6dy9bTd
PPz49fmhWlXV4idYVM1VnXSinY1pVdF43HdRLnfLLVhmMCTdtx7gFcDrCX7tFezT6RSiTsnTgbbLahy3qgaoKpcl_M_AQltHtv4A
v-LGVQUmVp_h4ubjtTkr4-hkn0Zvpj3pnIpaJT73Wg7oi2CuCqDdci9LwMWvdMg1b2zbi-4GOspBEN3VpiE7j3x_l0x1zp0Vn5Ch
EFoTEyGb5QYRDNqbLoLKZzJXsbl4anwXrM50s-WKl8eTd1XRHI-G3bP-I1zUxrXGnRKPVzIe_Y32FON0X7jJgS-cBtcUJ-10VNlH
mljSupzjJ0M1xLxR1spBCWriEDKZE8A4FQcfnc80ja9ZW60avOBmyVGo_VWf6WobCnv9GqysKKvlGo9ZR5-tCezlR17VdwEYi-
tWxI4SjT-Daf3sXY7ejhboAg0OZO9top0rOkqjYzbsQLKxWu4RZZ_CNx-4OZ7eZgEHCsVWZzLDsUAk6Vw4oIay5oNPBYO881l3xh
39p9M3JjZ94hM-sllrmisA8EVeoO9CIs9puZK8GIfc0ZyKo7Facmo1jaVgnKNjUH7QgLc-qk7NIgEWWkX3OLBd_C4km4uzcq0F_g
iPZQJs6esLYJBfyx1h_mp00-eso0xFJhEX_CmqcB7mzhsaO56Lo9-qxmQ9S4xW1_2JnFXCfUtCQE-Ej1shTauPfdLte2fFqzwRNK
RR4q5qnGoSkKemeWu6-J8vyp08TYE_RFqXWBfn63p7M42kIvwjNzTktnZZUhQZizN1p4wt3iD27T1tyA0wFxzhjcscbMKyXnPSkV
OPKmUVDMdwSzMwptYTHdBxNAs4PaPvnsGeBR69yQg5_M18MHYgRGtnia-l7HguSx5nzTAtnNIcB7lQWRLmFLuCZnTBR_Rh0ems4I
7MmpLpfx8FAfd9bLASQKAquosJbT3udqDvAQ2I4koyrnjgqqPTltR2RwEFDPhPy_eUm2aKEtBsNa5DCFWrz8ammSLhEFx_JqaA3H
d-lPJ0Bwv9nrVrdSvewiUX3ZrRxfj9V-MuqmLncJAvhBTZdHq2-cXXzLpS-
HRJ3hEVRB8qwaI-8jL5TqgYaqajlx7uoWMBuQ2RIveAzWo-wvV2IxVI4Fll45JHW1zN7a6kGwGSt2-Sv8w3q-IVpAB0LY46ikex-
t20d71coQIgUycVKvle39TVy9V39Bmvrb85IfQI9eFFHceqhgfvVEbtZ7-tpYbfwcI4UCTZiFzfQW73guzpNh0kyjCeECL2SFjUB
ahMHDNoP96nCx2n8lgQu3RCARR_0Ra9zaY1TRZS4zJXgxSCwxhjrroauy-VRaRwqdMpF1RTjZdCz3DGXuSdLs6tkDvZN6NvdGve1
vkWEvdtJoxQRnUNaksE2BBzHRRBVkq4LALe6ikUG3SzD0BL1YrPdpREI3YnlDiLpND3GaqOnhGXKwKXgopvFqDJyVnVVktIeV73G
uhS4zfUkySk2grgGzgghCKJwPNEqEzmyorMWYbU8xLWir7zGRhQifnHZfAplzIwhnUlAhdqLhXcsgX9HnTDBVuQU-pnohCgZFqdo
IprSQs87HdjLfVKe1H578bl0Y28LIytF31K_y1dXSXFi6g70HHYTLASNKoqhPjBS3mnTyArRKAzWRSY7UQISj7rPt3DNqUlDoZco
B-uJguLKgpUQlGceyMNjQ-nquDuTFyOVAl5ADug3mnWqIShUSYyeys-yffh2Rz_-
W_yJxMaJvmk8qy1B2QSD1AEttRCoy998YE9OpywmqbxnjwNcgi0nFlJwrCjqd-Gl398lTZ7Tcjf1LOVtOKVfw_avbx8paWiKGHAc
zB319KyhAGQlCcfimOG1EHqjFLJN30BbUvS1rA5qjVQwbT4tRoJyiPJ9ieupVvRWxyAInRJ88wYsr80qgtCWsGiGqRLkYUfdJVyv
PB_vnz7Kkziw3zQU6QazcIjZ0wFeifEBu1gA5DjMBP3qKliq1Fld3sCX3vQK15cseSMWEHt86wFnQY6L2LJTozHZn3YP8peZLZXn
bbLQUmnhsmz_owvm7E94-LBQwUOFWOPCguBwbhFagxwvIBXROSmuOJnA-CihdyBJq2vYRT3w_KRIKud6Tt5fOCsFyj31a9RpfPsF
tDM92Hqtg6ov6Q3KJOrcrX_NKVITUeSzL5NZ22xbT6rbsbNdAaH971phV1kwmBvjxWfu8FHImcy7yy9LAbJGXiOSP4xApZ0C37J8
JTVojWySzhNLceOTgMp88ViPzGFf_MJLX5MLdOam6H0ailz5Z1AV8oqotxLERnBCDWxwICv1wdWDISHsSJhswcVogdZHOszQdphx
z-QsHKaQTWAF5KS3wbKSsCUp5cw-yJDd1b0zuB7oJV3OsKQXqoNEIsmW0lzmu5HynEi4rcRR_J3lE1Zz_Nry8zYyndUJltunrbSD
BIGOqnTrH6AJ_xcz_G7uOk6QW7oLJJFOw7wLjv9Rk0m_tSS5BFJRj6gj1KsKPjdO3ydQoizoc3W0kr14QhJXghtRjHsI5CuXvPtW
IL_pSDJh1lVfDNAQajb1FRU1JAjfFO5Obf-NLoKCXJroG-
cfoVAWsB16AXJYii_xQDYRgN9UNEpB2_GKHqy4THtIE7yC8RKyuHtrLUd-UbbU4Na1NAapOndX1GCyFDQ4E9swKTdwPfZdhpOrp7
8Ofvt6AYPoTyelYAExS37WVsDb8ep1S4lQgMwffbg_TAhkFGUw58__w_5gHIh</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

2022-05-17 13:06 UTC, unkcpz commented on qe.ipynb
> +    "                #structure_selection_step.structure = process.inputs.structure\n",
Why this line is commented out?

2022-05-17 13:08 UTC, unkcpz commented on qe.ipynb
> +    "                #structure_selection_step.structure = process.inputs.structure\n",
Thanks @yakutovicha. Which line specifically fix the issue?

2022-05-17 13:14 UTC, yakutovicha commented on qe.ipynb
> +    "                #structure_selection_step.structure = process.inputs.structure\n",
I am not actually sure why the second one is needed, tbh. Do you have an idea?

2022-05-17 13:14 UTC, yakutovicha commented on qe.ipynb
> +    "                #structure_selection_step.structure = process.inputs.structure\n",
> Thanks @yakutovicha. Which line specifically fix the issue?

The first one

2022-05-17 13:38 UTC, unkcpz commented on qe.ipynb
> +    "                #structure_selection_step.structure = process.inputs.structure\n",
I think we should keep the line there. `structure_selection_step.structure` is the input structure for that step. It will be used when you choose a finished process and reset so the input structure is being set. If you remove that line you probably also need to remove the structure set of `structure_manager_widget` line.

2022-05-17 13:38 UTC, unkcpz requested changes

2022-05-17 13:42 UTC, yakutovicha commented on qe.ipynb
> +    "                #structure_selection_step.structure = process.inputs.structure\n",
Ok

2022-05-17 13:43 UTC, unkcpz approved these changes
All good, thanks!

2022-05-17 13:49 UTC, merged