Set relax type none and no properites to run SCF only
aiidalab/aiidalab-qe pull request #274
Opened 2022-09-01 22:22 UTC by unkcpz

fixes #264

2022-11-07 11:01 UTC, superstar54 commented
One comment, after the SCF calculation, what results could the user get? Currently, the `energy` and `force` are not printed out in the result section. Better to implement this also. Otherwise, the calculation is meaningless.

2022-11-07 11:05 UTC, superstar54 commented
It is also confusing that one runs a `SCF` calculation using the `relax` port. Better to add a `SCF` workchain, to make the code clean and readable.

2022-11-07 13:55 UTC, unkcpz commented
Thanks! @superstar54 

> after the SCF calculation, what results could the user get? Currently, the energy and force are not printed out in the result section. Better to implement this also. Otherwise, the calculation is meaningless.

This is a very good point. But this issue came from the in-person testing with Nicola that when selecting not relax and no properties are chosen the qeApp will block the calculation from running by throwing a warning. 
Is that possible to leave it in the future since we do not decide yet what to show as the output of the SCF only calculation? I'll open an issue for it. 

> It is also confusing that one runs a SCF calculation using the relax port. Better to add a SCF workchain, to make the code clean and readable.

I also had same feeling when start working on this. But qeApp is simply the UI wrapper of aiida-quantumespresso, I think the change should be make there. @mbercx can you comment on if you think this is worth implementing? 
I think we can basically add an alias workchain called `PwScfOnlyWorkChain` sort of, and have it point to Relax with the parameters fixed. The question is where to put this workchain? If it is not a case to add in aiida-quantumespresso, I think it is also make sense to have the workchain here in QeApp/src. I'll add it in this PR.

2022-11-07 15:44 UTC, unkcpz commented
Hi @superstar54, I change the message show in workflow bar. But I still not add the energies showed in the output tabs. Since I don't decide yet where to add it, it can be on in the `Workflow summary` or as a new tab with all related and necessary output parameters. I open an issue at https://github.com/aiidalab/aiidalab-qe/issues/311. 
Let's focus on it with another PR.

2022-11-07 19:09 UTC, mbercx commented
Re the SCF only output: I think one of the possible outputs Nicola had in mind would be the charge density. However, I don't think it's possible to extract the charge density file atm. I'll add that originally we blocked this type of calculation for this very reason: I saw little point in running only an SCF for a layman user. The total energy of a single calculation is also not super meaningful, I'd say? The forces _could_ be useful in some cases, I suppose.

Re the relax work chain: An "SCF" work chain would simply be the `PwBaseWorkChain`, no? The `RelaxType.NONE` implementation comes from the common workflows project, there it was decided to add this relax type for technical reasons, and here we simply repurpose this to make the implementation somewhat easier. I'd have to take a closer look at the code (which I'll try to make some time for ASAP, many apologies @unkcpz!), but I think you'd also have to make quite some significant changes to the `QeAppWorkChain` to add this to a proper (optional) port. Not sure if the resulting code would be easier to maintain.

2022-11-10 13:54 UTC, unkcpz commented
@mbercx Thanks! I update the #311 with your comment. I think for the current one, it is okay to use the PwRelaxWorkChain with RelaxType.None. Since in my opinion, we should not add complexity to the workchain of QeApp but just light wrapper of what already implement in the `aiida-quantumespresso`. 

@superstar54 could you have another look and let's try get this PR done?

2022-11-10 14:41 UTC, superstar54 requested changes

2022-11-10 14:41 UTC, superstar54 commented on aiidalab_qe/process.py
> +                    relax_info = "structure is not relaxed"
```suggestion
                    relax_info = "structure is relaxed"
```

2022-11-10 14:41 UTC, superstar54 commented on aiidalab_qe/process.py
> +                if relax_type != "none":
Why is "none", not `None` or "None". Please make sure "none" is correct.

If it is correct, we need to change it to a more standard way, e.g. `None`

2022-11-10 14:41 UTC, superstar54 commented on aiidalab_qe/report.py
> +    try:
I think this `try ... except` is not used, because it will always run a relax (scf or real relax) calculation.

2022-11-10 14:41 UTC, superstar54 commented on aiidalab_qe/steps.py
> +        # skip relax sub-worflow only when RelaxType is NONE and has property calculated.
Could you explain the difference between relax (only scf) and relax sub-workflow? I am not very clear about this, thanks.

2022-11-10 14:41 UTC, superstar54 commented on aiidalab_qe/steps.py
> +        # skip relax sub-worflow only when RelaxType is NONE and has property calculated.
```suggestion
        # skip relax sub-workflow only when RelaxType is NONE and has property calculated.
```

2022-11-14 00:11 UTC, unkcpz commented on aiidalab_qe/steps.py
> +        # skip relax sub-worflow only when RelaxType is NONE and has property calculated.
You can find how this tag change the parameters set in `pw.x` input file at https://github.com/aiidateam/aiida-quantumespresso/blob/d15f8cd1032e37ae59a19d733ee5ae1ed59e1f10/src/aiida_quantumespresso/workflows/pw/relax.py#L123-L146

2022-11-16 20:43 UTC, superstar54 approved these changes
LGTM

2022-11-16 21:25 UTC, merged