band structure use dos fermi energy if exist
aiidalab/aiidalab-qe pull request #306
Opened 2022-10-21 15:34 UTC by unkcpz

fixes #268

2022-11-07 09:58 UTC, superstar54 requested changes

2022-11-07 09:58 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +        bands = []
If there is no band data, set it to `None`.
```suggestion
        bands = None
```

2022-11-07 09:58 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +    _, energy_dos, energy_units = work_chain_node.outputs.dos.get_x()
I don't understand why you remove this:
```
if "dos" in work_chain_node.outputs:
```
We should make sure that the `dos` does exist before fetching the data, right?

2022-11-07 13:00 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +    _, energy_dos, energy_units = work_chain_node.outputs.dos.get_x()
I move the `if "dos"` to `export_data` below. I think it would be more easy to maintain if the if-else checks are in one place.

2022-11-07 13:00 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +        bands = []
Yes, that's true. Thanks!

2022-11-07 14:20 UTC, superstar54 requested changes

2022-11-07 14:20 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +    _, energy_dos, energy_units = work_chain_node.outputs.dos.get_x()
This will make the `export_pdos_data` function incomplete. If one calls the function from other places, there is a risk that they will get an error. Better to keep `if` here.

Then in the `export_data` part, you can remove the `if` by:
```
dos = export_pdos_data(work_chain_node)
fermi_energy = dos["fermi_energy"] if dos else None
```

2022-11-08 13:09 UTC, superstar54 approved these changes
LGTM!

2022-11-08 13:10 UTC, merged