Bandswidget bump to 0.5.0, make the data format compatible
aiidalab/aiidalab-qe pull request #313
Opened 2022-11-14 16:39 UTC by unkcpz

fixes #229 

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/8831685/201770273-47969474-35ad-48c3-b68a-bb85c6900a1b.png">

2022-11-24 10:41 UTC, superstar54 commented
@unkcpz could you add a short description for this PR? What's the purpose and what has been added?

2022-11-24 10:45 UTC, unkcpz commented
> @unkcpz could you add a short description for this PR? What's the purpose and what has been added?

Hi @superstar54, I'd say all the changes made from bandsplot widget, here in QeApp the change is made to compatible with the new API to plot the bands and dos. 
@dou-du didn't write the CHANGELOG for the changes but from 0.5.0 I adapt the new release process which will having the CHANGELOG with release tag as we did for QeApp and AWB, which you can find from https://github.com/osscar-org/widget-bandsplot/releases/tag/v0.5.0

2022-11-24 14:43 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +    ascn = sum([ord(c) for c in label])
int.from_bytes(s.encode(), 'little')

2022-11-24 15:23 UTC, superstar54 requested changes
I got this error for "SiO2" + "fast"
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/apps/aiidalab-qe/aiidalab_qe/widgets.py in _observe_node(self, change)
    382                 clear_output()
    383                 if change["new"]:
--> 384                     display(viewer(change["new"]))
    385 
    386 

~/apps/aiidalab-widgets-base/aiidalab_widgets_base/viewers.py in viewer(obj, downloadable, **kwargs)
     81             )
     82             return obj
---> 83         raise exc
     84 
     85 

~/apps/aiidalab-widgets-base/aiidalab_widgets_base/viewers.py in viewer(obj, downloadable, **kwargs)
     73     try:
     74         _viewer = AIIDA_VIEWER_MAPPING[obj.node_type]
---> 75         return _viewer(obj, downloadable=downloadable, **kwargs)
     76     except (KeyError) as exc:
     77         if obj.node_type in str(exc):

~/apps/aiidalab-qe/aiidalab_qe/node_view.py in __init__(self, node, **kwargs)
    559 
    560         self.result_tabs.observe(on_selected_index_change, "selected_index")
--> 561         self._update_view()
    562 
    563         super().__init__(

~/apps/aiidalab-qe/aiidalab_qe/node_view.py in _update_view(self)
    586                 "band_structure" in self.node.outputs or "dos" in self.node.outputs
    587             ):
--> 588                 self._show_electronic_structure()
    589                 self._results_shown.add("electronic_structure")
    590 

~/apps/aiidalab-qe/aiidalab_qe/node_view.py in _show_electronic_structure(self)
    600         bands_data = data.get("bands", None)
    601         dos_data = data.get("dos", None)
--> 602         self._bands_plot_view = BandsPlotWidget(
    603             bands=bands_data, dos=dos_data, plot_fermilevel=True
    604         )

/opt/conda/lib/python3.9/site-packages/widget_bandsplot/bandsplot.py in __init__(self, bands, dos, fermi_energy, show_legend, plot_fermilevel, energy_range)
     72         if dos is not None:
     73             temp_dos = deepcopy(dos)
---> 74             self.tdos_x = dos['tdos']['energy | eV']['data']
     75             self.tdos_y = dos['tdos']['values']['dos | states/eV']['data']
     76             self.dos_fermienergy = dos['fermi_energy']

KeyError: 'tdos'
```
I am not testing "SiO2" + "relax" + "bands" + "pdos" + "moderate", will let you know when the test finishs.

2022-11-24 15:23 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +            curated_tag_var = orbital_name
Adding positions to the label is not common and makes the plot too much test. I suggest using the index of the atoms.

Previously, the orbital label is used. I think we can keep using the orbital label.

2022-11-24 17:10 UTC, unkcpz commented
@superstar54 thanks for testing! For the error, can you reinstall the package with `-U` to make sure you have the latest `bandsplot_widget` version installed it should be `0.5.0`.

2022-11-24 17:17 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +            curated_tag_var = orbital_name
The problem of having orbitals distinguished is will having many orbitals if having elements with d-orbital included. 
It has 1s, 3p, 5d for every element. I don't think there is a `default` way to properly show this. To me, the index of the atom has little meaning. 
Let's keep this open issue and discuss it further with other people (especially the demo testing with Nicola).

We can either keep this open, or merge this and show the non-perfect result to people and get feedback.

2022-11-24 17:22 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +            curated_tag_var = orbital_name
I really want to keep this thoroughly discussed and find and good solution on our side, however, the demo with Nicola really push us to have a "non-perfect" version. Sorry for the rush, I am not reluctant to accept your suggestion. Overall, this is to make the newly refactored `bandswidget` work, there are plenty of things to improve after, but we can leave it to the near future.

2022-11-29 11:43 UTC, merged

2022-11-29 11:44 UTC, unkcpz commented
Hi @superstar54, I'll merge this now so I can move on to test. If new things pop up we can tackle it then.