Final screenshot fixture
aiidalab/aiidalab-qe pull request #345
Opened 2023-02-06 10:52 UTC by unkcpz

fixes #343 

Using the fixture `final_screenshot` to take the screenshot for smoke tests at the end of tests.

2023-02-06 20:45 UTC, danielhollas approved these changes

2023-02-06 20:45 UTC, danielhollas commented on tests/test_qe_app.py
> +    time.sleep(15)
Why is this sleep needed? The element below should wait implicitly, no?

2023-02-06 20:45 UTC, danielhollas commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
Same question here, is this fixing some flakiness that you saw?

2023-02-07 09:33 UTC, unkcpz commented on tests/test_qe_app.py
> +    time.sleep(15)
Since the below I didn't use `WebDriverWait` for "from examples", somehow the From Examples is not clickable. I'll try again.

2023-02-07 09:33 UTC, unkcpz commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
I don't quite understand what you mean, this `60` is the timeout, it will check if the element is valid in a certain period (500ms if I remember correctly).

2023-02-07 19:17 UTC, danielhollas commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
The `find_element` waits implicitly (we set implicit wait in conftest), so I don't think this code is an improvement. What may happen I guess is that the element is located, but for some reason is not yet clickable. So I think you should use `EC.element_to_be_clickable` (which you already do below) instead of merely `EC.presence_of_element_located`.

2023-02-08 07:46 UTC, unkcpz commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
I see your point. I changed all find_element to wait at first commit without too much thinking. You are correct, for the select of Structure, this explicit wait is needless. Changed.

2023-02-08 07:52 UTC, unkcpz commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
However, for the "From examples", if I understand correctly, the `WebDriverWait` is the explicit wait in order to make sure the "From examples" tab is valid, it is not the same as the implict wait we set in conftest.

2023-02-08 08:52 UTC, danielhollas requested changes

2023-02-08 08:52 UTC, danielhollas commented on tests/test_qe_app.py
> -    time.sleep(10)
I think you need to sleep here, although probably less than 10s, to ensure the molecule is displayed for the screenshot below.

2023-02-08 08:52 UTC, danielhollas commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
```suggestion
    element = WebDriverWait(driver, 10).until(
```
I'd say 60 is an overkill (same below) but up to you.

2023-02-08 08:52 UTC, danielhollas commented on tests/test_qe_app.py
> +        EC.presence_of_element_located((By.XPATH, "//*[text()='From Examples']"))
Why not

```suggestion
        EC.element_to_be_clickable((By.XPATH, "//*[text()='From Examples']"))
```

2023-02-08 08:53 UTC, danielhollas commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
I don't understand what you mean. From examples tab should be clickable as well, no?

2023-02-08 16:19 UTC, unkcpz commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
Fair, 60 is too much.

2023-02-08 16:20 UTC, unkcpz commented on tests/test_qe_app.py
> +
```suggestion
    time.sleep(10)
    
```

2023-02-08 16:21 UTC, unkcpz commented on tests/test_qe_app.py
> -    time.sleep(10)
I see, I add it back.

2023-02-08 16:24 UTC, unkcpz commented on tests/test_qe_app.py
> +        EC.presence_of_element_located((By.XPATH, "//*[text()='From Examples']"))
This was what I try but with no luck, the test failed, and report the element is not loaded. I assume the reason is the `element_to_be_clickable` is for element that change from unclickable to clickable such as the `Confirm` button below. If the `presence_of_element_located` works fine, I think there is no harm to keep it.

2023-02-08 16:27 UTC, unkcpz commented on tests/test_qe_app.py
> +    element = WebDriverWait(driver, 60).until(
I don't know to be honest, I tried `element_to_be_clickable` but it failed and the screenshot is still the loading page.

2023-02-08 16:48 UTC, danielhollas approved these changes

2023-02-08 17:25 UTC, merged