Enhance view for the electronic structure
aiidalab/aiidalab-qe pull request #363
Opened 2023-03-06 10:51 UTC by superstar54

This PR enhances the view of electronic structure.
User can 
- select dos_type (`atom` or `orbital`).
- change the energy range.
- plot or hide the fermi level line.

Here is a screenshot:

![Screenshot from 2023-03-06 11-46-04](https://user-images.githubusercontent.com/11457659/223089828-49091157-d678-4dc3-82ea-50048e382ab1.png)

2023-03-07 15:08 UTC, superstar54 commented
As suggested by Giovanni, I removed the `energy_range` and `plot_fermi_level`.

2023-03-07 17:03 UTC, unkcpz requested changes
Thanks @superstar54 for this change. I have some requests that better to improve and more discussion maybe needed.

2023-03-15 08:29 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +    dos_group="atom",
I changed it to `group_dos_by`

2023-03-15 08:32 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +        self.result_tabs.children[2].children = [
I added a comment.
`# update the electronic structure tab`

2023-03-15 09:44 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +            )
Thanks for the suggestion. I convert the data to the correct type and try:
```python
_bands_plot_view.bands = bands_data
_bands_plot_view.dos = dos_data
```
or using the original data and
```
_bands_plot_view.__init__(bands_data, dos_data)
```
 But the widget does not update in all the cases.

Better to discuss this with Dou.

2023-03-15 09:47 UTC, superstar54 commented
As discussed with Jusong, it is better to group the orbital by angular momentum (e.g. s, p, d) instead of both angular and magnetic momentum (e.g. px, py, pz). This is implemented.

![Screenshot from 2023-03-15 10-02-19](https://user-images.githubusercontent.com/11457659/225271502-eeead442-f9e5-493f-b7df-8615da5da55d.png)

2023-03-17 12:44 UTC, unkcpz requested changes
Thanks @superstar54, just some minor things not very clear to me. Can you try running on a structure that has two atoms of the same elements in the cell, the Silicon from the example is the case. I am curious how this chang will parse it.

2023-03-17 12:44 UTC, unkcpz commented on aiidalab_qe/node_view.py
> +            )
Okay, then we don't worry about this for the moment.

2023-03-21 13:13 UTC, unkcpz commented
Hi @superstar54, are you able to manage to finish this today? I want to make a release for tomorrow's demo test.

2023-03-21 14:19 UTC, superstar54 commented on aiidalab_qe/node_view.py
> +            # by orbital label
group by:
- angular momentum, e.g. s, p, d
- -angular_magnetic momentum, e.g. px, py, pz

2023-03-21 14:32 UTC, unkcpz approved these changes

2023-03-21 14:33 UTC, merged