Feature: tot charge
aiidalab/aiidalab-qe pull request #377
Opened 2023-03-31 09:19 UTC by AndresOrtegaGuerrero

This PR add the feature to set the total charge of the system in the simulation. 

This implementation avoids the modification of the workchain, and includes the tot_charge parameter in the results

2023-03-31 15:01 UTC, superstar54 commented
Hi @AndresOrtegaGuerrero, Thanks for the implementation. 

In my option, it's better to add this parameter to the advanced setting tab. A DFT calculation for a charging system is more likely a calculation for an advanced user. In the main workflow setting, it should only show the simple "control" parameters (e.g. protocol, materials type).

2023-03-31 16:16 UTC, AndresOrtegaGuerrero commented
Hello @superstar54 , thank you. I agree it could be placed in the advanced tab. I put the tot_charge in the main menu, since our users (at EMPA) will be using this feature quite often  since they will be computing point defects (So basically routinely). @unkcpz  what do you think?.

2023-04-01 14:40 UTC, unkcpz commented
@AndresOrtegaGuerrero thanks a lot! I and @superstar54 had a discussion on how to integrate new settings into step2. 
I can image that there will be more parameters setting widget comes to QeApp after you and Xing start to add more properties. It is not very clear how such a widget can be independently displayed, not only easy to be found by user but should not entangle with the other widgets (either the base widget from the current QeApp, or the widgets from other properties, such as Xing will also add new widgets for XPS calculations.)

There are multiple options:
1. the widgets can be added to a new tab parallel to "advanced settings", only when the property is selected, the tab show up. This will make the widgets related only to the new property can be fully independent of widgets of base functionality or other widgets. The cons are it is not easy to find by users and that those are in other tabs. 
2. Same as above but the new widgets are showing in the same tab of the basic setting (the "Workflow" table of Step 2), the widgets are in a parent `VBox` widget and will be hidden if the property is not selected. One drawback of this strategy is that the widget is entangled in this table in the `ConfigureQeAppWorkChainStep`. 

As for the `total_charge` in this PR, however it is a vanilla QE parameter which can be set for all PW calculations I think it makes more sense to be added as an override of the base protocol, and the widget is displayed in "Advance setting" tab.

2023-04-01 14:53 UTC, unkcpz requested changes
@AndresOrtegaGuerrero Thanks a lot for making the ball rolling. My comments are slightly general, I'll work in parallel to have a generic interface for similar parameter control widgets. What you can try in this PR in parallel is my above comment, moving this widget to "Advance settings" tab.

2023-04-01 14:53 UTC, unkcpz commented on aiidalab_qe/steps.py
> +        ]
I find this is error-prone. Can you try to using protocol override to override the base pw protocol and let it propagate to all other sub-workchain? Let me know if this is not clear and we can arrange a meeting to discuss.

2023-04-01 14:53 UTC, unkcpz commented on aiidalab_qe/report.py
> +    yield "tot_charge", builder_parameters["tot_charge"]
I think this is a great example to push us to have an interface for adding a new widget that controls an input parameter that will be read from the output report widget. In your PR, there are four files required to change. The idealist goal is only to implement in one place and add somewhere to reference the newly added widget.

2023-04-02 10:20 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/steps.py
> +        ]
> @AndresOrtegaGuerrero Thanks a lot for making the ball rolling. My comments are slightly general, I'll work in parallel to have a generic interface for similar parameter control widgets. What you can try in this PR in parallel is my above comment, moving this widget to "Advance settings" tab.

@unkcpz Thank you I will proceed then , One question , should I create then one specific class for this "Advanced Seetings" , since the idea will be to have Tot_charge, but I guess we want in this new tab to have other advanced settings like Periodicity (I submitted the PR in the aiida-quantumespresso) or Hubbard settings?

2023-04-02 10:22 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/steps.py
> +        ]
> 

@unkcpz  Maybe I would like if we can have a small talk regarding this one. I am not sure if this requires the modification of the workchain?

2023-04-02 10:23 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/report.py
> +    yield "tot_charge", builder_parameters["tot_charge"]
@unkcpz Maybe we can discuss about this one, I think this will require modification in the workchain , right?

2023-04-03 12:10 UTC, unkcpz commented on aiidalab_qe/steps.py
> +        ]
> One question , should I create then one specific class for this "Advanced Seetings" , since the idea will be to have Tot_charge, but I guess we want in this new tab to have other advanced settings like Periodicity.

Do you mean the class of widget for "Advance setting" specifically? I didn't look at the code, but maybe it is a good idea.

2023-04-06 12:56 UTC, AndresOrtegaGuerrero commented
I have done the modifications you guys suggested, the option of tot_charge is now in the Advanced Setting tab, 
I implemented a new class in steps `class PwAdvancedSettings(ipw.VBox):` , where we can include other advanced features. I was thinking in the future implementing in this class the starting_magnetization and Hubbard here. 
For total charge i use an extra checkbox since I think in the future there would be more settings and each should have its control.

2023-04-12 11:41 UTC, unkcpz commented on aiidalab_qe/steps.py
> +            }
Thanks! This is exactly what I was thinking. I hope you don't mind if my refactoring PR include similar code. 
My goal is to make this PR become very small for adding a parameter setting widget just needs to edit a reasonable amount of lines.

2023-04-15 09:53 UTC, AndresOrtegaGuerrero reviewed
there are the changes including a tab in AdvancedSettings

2023-05-17 11:20 UTC, unkcpz commented
Hi @AndresOrtegaGuerrero, https://github.com/aiidalab/aiidalab-qe/pull/382 is merged, maybe you can rebase this or (maybe much easier to do) open a new PR to supersede this one?

2023-05-23 10:33 UTC, closed without merging