0x3 ♻️ decouple override settings of builder
aiidalab/aiidalab-qe pull request #382
Opened 2023-04-07 17:53 UTC by unkcpz

2023-04-14 22:48 UTC, unkcpz commented
Hi @superstar54 @AndresOrtegaGuerrero, I think this PR is starting shaping. Before go into more deep test, I hope you two can have a look if this make everything much clear.

2023-04-15 09:44 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/workflows.py
> +        # logic based on the properties input
Maybe add some logic if properties is None, in that scenario is just a single point ?

2023-04-17 11:44 UTC, unkcpz commented on aiidalab_qe/workflows.py
> +        # logic based on the properties input
Yes, if the properties list is an empty list, there is nothing actually running.
I try to move the logic outside of the workflow. In this workflow, the sub-workflows are run as independently as possible.
Not sure this is a good strategy, worth to discuss.

2023-04-18 13:23 UTC, superstar54 requested changes

2023-04-18 13:23 UTC, superstar54 commented on aiidalab_qe/steps.py
> +    def _create_builder(self) -> tuple[ProcessBuilderNamespace, dict[str, t.Any]]:
This function is too long. There are four steps inside the function,
- step 1, get input parameters
- step2, create the builder
- step3, post-update the builder
- step4, generate report parameters
I suggest creating a function for each step (at least steps 1 and 4)

2023-04-18 19:35 UTC, unkcpz commented on aiidalab_qe/steps.py
> +    def _create_builder(self) -> tuple[ProcessBuilderNamespace, dict[str, t.Any]]:
Good suggestion! I also find it quite long and a bit lost in second look, I'll separate in functions.

2023-04-18 19:38 UTC, unkcpz commented
@superstar54 thanks! 

> store the parameters to restore all the widgets settings in the four steps. This is important but has not been implemented yet. Please consider this in the PR.

True, I didn't add it yet. Will add it.

2023-05-06 07:40 UTC, mbercx approved these changes
Quite a bit PR, so I didn't look into every line of code in much details, but it all looks great! Much cleaner, great work @unkcpz!

I still left some comments/questions, but will already approve.

2023-05-06 07:40 UTC, mbercx commented on aiidalab_qe/workflows/__init__.py
> +                f"the `structure` must be of type `StructureData`, get {structure} of type {type(structure)}."
Will this really ever happen? I mean we're in control of what inputs are passed to the `get_builder_from_protocol()` method, no?

2023-05-06 07:40 UTC, mbercx commented on aiidalab_qe/workflows/__init__.py
> +        # pop the inputs that are exclueded from the expose_inputs
```suggestion
        # pop the inputs that are excluded from the expose_inputs
```

2023-05-06 07:40 UTC, mbercx commented on aiidalab_qe/workflows/__init__.py
> +        # pop the inputs that are exclueded from the expose_inputs
```suggestion
        # pop the inputs that are excluded from the expose_inputs
```

2023-05-06 07:40 UTC, mbercx commented on qe.ipynb
> +    "# install_create_github_issue_exception_handler(\n",
Why is this commented?

2023-05-06 07:40 UTC, mbercx commented on aiidalab_qe/app/legacy_report.py
> +"""Legacy report for the `QeAppWorkChain`, only used for the old workchains run before QeApp version < 23.10
So this one is only here for backwards compatibility? Since we use dated versioning, when would we remove this? Do we really _have_ to worry about backwards compatibility at this stage? 😉

2023-05-06 07:40 UTC, mbercx commented on aiidalab_qe/app/steps.py
> +@dataclass(frozen=True)
Me likey data class ❤️

2023-05-06 08:22 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/workflows/__init__.py
> +        relax.pop("base_final_scf", None)  # never run a final scf
I wonder why to also do this step , doesnt the workchain already removes this ?

2023-05-08 08:22 UTC, unkcpz commented on aiidalab_qe/app/legacy_report.py
> +"""Legacy report for the `QeAppWorkChain`, only used for the old workchains run before QeApp version < 23.10
Yes, it is for backward compatibility only. To be honest, I don't know when can we remove this and how can this be removed if there are workflows run with old workchain. My answer probably be this code will stay there forever or we simply don't care about it and having all workchain requires a re-run with new extra attributes attached to the node. 

@superstar54 @AndresOrtegaGuerrero, you have some node run with old workchain, do you think it is okay to not have backward compatibility considered?

2023-05-08 08:22 UTC, unkcpz commented on aiidalab_qe/workflows/__init__.py
> +                f"the `structure` must be of type `StructureData`, get {structure} of type {type(structure)}."
You are correct, removed.

2023-05-08 08:22 UTC, unkcpz commented on qe.ipynb
> +    "# install_create_github_issue_exception_handler(\n",
For test purposes, I forgot to bring it back. :sweat_smile:

2023-05-08 08:36 UTC, unkcpz commented on aiidalab_qe/steps.py
> +                "scf": pw_overrides["scf"],
Yes, bands workchain contains `relax` workchain but pdos does not. I want to keep the bands sub-workchain in qeapp workchain as similar as possible to pdos sub-workchain. 

I think the better design would be even more verbose for workchain that relax sub-workchain will always having a final_scf calculation. The caching is turned on for using this final_scf as the first step of bands/pdos workchain.

2023-05-08 09:54 UTC, unkcpz commented on aiidalab_qe/app/legacy_report.py
> +"""Legacy report for the `QeAppWorkChain`, only used for the old workchains run before QeApp version < 23.10
Just have an offline discuss with @superstar54, we think there is no harm to keep the code, I need it since otherwise I need to rerun the workchain which I did for couple of large components for MARVEL review. I think it is also good to keep it as a placeholder for future backward compatibility support of report builder parameters. We can try to keep one legacy version supported in the future and give a more verbose warning to ask to re-run the workchain if we deprecate the support for the output.

2023-05-08 19:41 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/legacy_report.py
> +"""Legacy report for the `QeAppWorkChain`, only used for the old workchains run before QeApp version < 23.10
Maybe add extra comments giving instructions that new features and modifications should not be consider in the legacy and only in node_view  ?? , or how will it work the addition of new features ? if not here maybe in the README ?? (what you do you think @unkcpz  of adding  few design guidelines for future PRs) (or maybe this is not really needed ? )

2023-05-09 07:28 UTC, unkcpz commented on aiidalab_qe/app/legacy_report.py
> +"""Legacy report for the `QeAppWorkChain`, only used for the old workchains run before QeApp version < 23.10
> Maybe add extra comments giving instructions that new features and modifications should not be consider in the legacy and only in node_view ??

Good point, I add a comment on both legacy_report.py and on the lines where the condition happened. 

> what you do you think @unkcpz of adding few design guidelines for future PRs)

You mean the guidelines for how to write workflow and add new properties? Or the guideline for the PRs?

2023-05-09 09:08 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/legacy_report.py
> +"""Legacy report for the `QeAppWorkChain`, only used for the old workchains run before QeApp version < 23.10
Yes the former

2023-05-15 12:54 UTC, mbercx commented
To supplement @AndresOrtegaGuerrero's message: I mainly raised the fact that maintaining backwards compatibility is perhaps an undue burden. I don't think there are that many heavy users yet who would lose any important data with this change. I think our policy until further notice (or until public release, tbd) should be to throw backwards compatibility to the wind so we are not limited in making improvements to the interface, and the code does not become more difficult to maintain.

2023-05-15 15:03 UTC, superstar54 commented on tests/conftest.py
> +    """Return a `UpfData` instance for the given element a file for which should exist in `tests/fixtures/pseudos`."""
Where is this folder?

2023-05-16 05:01 UTC, superstar54 requested changes
Hi @unkcpz, Thanks for implementing this. I added a few special suggestions to the review.
Here are some general comments:
- `_update_settings` method is added for each setting, but these methods are not called. Thus, when loading a previous calculation, widget values are not restored in the GUI.
- In the test, the app tested as a whole in the submit step (kind of integration test). It's nice if you also add tests for each setting (unit test), e.g. workchain, smearing, especially to override the value and then test it.

2023-05-16 06:22 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        for key in ["base", "scf"]:
@superstar54 you mean that we do not to override de` dgauss` or just the `smearing` type ?

2023-05-16 06:40 UTC, superstar54 commented on aiidalab_qe/app/steps.py
> +        for key in ["base", "scf"]:
For the `nscf` calculation, `occupations` is set to `tetrahedra` in the pdos workchain. In this case, `smearing` and `degauss` is not used. I think @mbercx knows better about this.

2023-05-16 07:06 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        for key in ["base", "scf"]:
But sometimes depending of the degauss, that value will be the one use for projwfc, so in case the user download the data it cant decrease the degauss to do a new 'gaussian broadening'. So i guess the degauss is only needed for the `scf` ? @superstar54

2023-05-16 08:06 UTC, superstar54 commented on aiidalab_qe/app/steps.py
> +        for key in ["base", "scf"]:
Thanks for pointing out this. In this case,  we need to pass the `degauss` to the `nscf` workchain, because the `dos` and 
the `projwfc` will read the input data from the `nscf` calculation.

It will be useful to add the setting for the `degauss` of dos and projwfc, and we could do this in a future PR.

2023-05-16 10:11 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        for key in ["base", "scf"]:
just to clarify, if you use a degauss in pw.x (say a small number) , you can later use a higher value for degauss in projwfc.x , and that is fine. What you cant do is to use a high degauss in pw.x  and later in projwfc decrease it. Or at least that is my experience , maybe @mbercx  could give us your opinion?

2023-05-16 12:03 UTC, unkcpz commented on tests/conftest.py
> +    """Return a `UpfData` instance for the given element a file for which should exist in `tests/fixtures/pseudos`."""
It is useless, at least for test here. I copy the fixture from qe plugin and I think it is also not used there. Open a PR at https://github.com/aiidateam/aiida-quantumespresso/pull/933, let's see if it passes all tests.

2023-05-16 12:04 UTC, unkcpz commented on tests/conftest.py
> +        for values in elements.values():
Since there is no much code for this function and the upf file is actually a fake file of every element, I think it is okay to keep it as it is.

2023-05-16 12:17 UTC, unkcpz commented on tests/conftest.py
> +    """Return a function that generates a kpoints settings dictionary."""
It can I assume but will make the code even not easy to understand. It can be a `settings_generator` with passing `workchain`, `smearing` or `kpoints_settings` with the kargs. Sometimes it is not bad pattern to repeat some code if it makes things clear and easy to implement. I'd argue to keep in this way.

2023-05-16 12:18 UTC, unkcpz commented on tests/conftest.py
> +    """Return a `UpfData` instance for the given element a file for which should exist in `tests/fixtures/pseudos`."""
The fixture is used in `aiida-quantumespresso` for sure, but not necessary here, so I update the docstring only.

2023-05-16 13:10 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                and self.workchain_settings.electronic_type.value == "metal"
> By the way, the smearing should also work for the insulator, right?

No, if select insulator, the `occupations` is set to `fixed`, the smearing and degauss are not in the input.

2023-05-16 13:44 UTC, AndresOrtegaGuerrero approved these changes
Everything looks fine to me!

2023-05-17 09:29 UTC, unkcpz commented
Per @superstar54's comment:
> _update_settings method is added for each setting, but these methods are not called. Thus, when loading a previous calculation, widget values are not restored in the GUI.

I tried with using builder_parameters  to recover the widgets, but it is a bit more complicate than I thought. The problem is the key store in the builder_parameters  extra attributes are not same for the key used in setting widgets. There are a further step to convert the paramters from setting widget to builder_parameters, to bring it back I think we need a more systematical way to do it and I prefer to do it in a separate PR. If you agree, I’ll merge it.

Moreover, when I look at the refactored architecture in https://github.com/aiidalab/aiidalab-qe/issues/383, setting widgets directly from builder_parameters  is not ideal since it bring the entanglment between viewer and controller which is we want to avoid from first place. Instead, we need introduce and use the dataclass  for all the settings object and having bilateral converters between setting wdigets and builder_parameters  and having this dataclass in the middle.

@superstar54 is working on introducing the new "plugin-like"way of adding new properties calculation, and it will be handled in the new design by the get and set methods of the panel.

2023-05-17 10:46 UTC, superstar54 approved these changes

2023-05-17 11:17 UTC, merged