add PseudoDojo
aiidalab/aiidalab-qe pull request #387
Opened 2023-04-26 14:20 UTC by superstar54

2023-04-27 06:45 UTC, AndresOrtegaGuerrero commented
I think it would be worth to also include FR and  also to add the stringent accuracy

2023-04-27 07:26 UTC, superstar54 commented
Hi @AndresOrtegaGuerrero, Thanks for your suggestions. It's good to add more pseudo-family, but this leads to a longer time for the installation, thus the user needs to wait in the first run. The idea here is only to install the most commonly used pseudo, and trigger additional downloads (FR, stringent) if an advanced calculation is needed. This may be added in a further PR. See discussion https://github.com/aiidalab/aiidalab-qe/issues/386.

2023-04-27 07:35 UTC, AndresOrtegaGuerrero commented
@superstar54  I agree, though it might be a good idea that the user gets some description that the PseudoDojo that they are using is SR, and that the accuracy is the standard

2023-04-27 08:21 UTC, superstar54 commented
> @superstar54 I agree, though it might be a good idea that the user gets some description that the PseudoDojo that they are using is SR, and that the accuracy is the standard

Thanks!. A description for Pseudodojo has been added.

2023-05-24 21:59 UTC, unkcpz commented
Hi @superstar54, I change the base to branch `main` since I decided to deprecate `master` after the change in app registry is merged, I hope you don't mind. 

Is there any block for this PR? Do we need more discussion on this? I remember we want to double-check the versioning of pseudo-dojo?

2023-06-06 07:49 UTC, AndresOrtegaGuerrero commented
I think in a previous meeting, we discussed as well that it could be useful to have normal and stringent precision

2023-06-06 08:06 UTC, superstar54 commented
> it could be useful to have normal and stringent precision

Done

2023-06-06 09:44 UTC, AndresOrtegaGuerrero commented
@superstar54  Since the code was re factored, you should do a  rebased on this branch with main , since now there is a folder named app for the files you modified

2023-06-06 09:52 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/pseudos.py
> +            options=["SSSP efficiency", "SSSP precision", "PseudoDojo"],
The ToogleButton should contained the option to differenciate with PseudoDojo you are using , stringent or standard

2023-06-08 07:03 UTC, superstar54 commented
@AndresOrtegaGuerrero Thanks for the review. I addressed the issues and rebased the branch with the main branch.

2023-06-08 07:40 UTC, AndresOrtegaGuerrero commented
@superstar54  Thank you it looks nice, I tested and didnt observe any issues, I only have one opinion an is regarding the widget. 
![Screenshot 2023-06-08 at 09 36 51](https://github.com/aiidalab/aiidalab-qe/assets/34098967/98c6a22c-e151-45c3-af75-73a6b7b709b8)
I was wondering if we should use a Dropdown ? or maybe to make like a 2x2 grid to organize the buttons? What do you think?

2023-06-08 09:04 UTC, superstar54 commented
> I was wondering if we should use a Dropdown ? or maybe to make like a 2x2 grid to organize the buttons? What do you think?

I updated the layout so that they are shown in a 2x2 grid on a large screen and 4x1 on a small one.

2023-06-08 09:10 UTC, AndresOrtegaGuerrero commented
@superstar54  It looks great to me !  thank you

2023-06-08 09:10 UTC, AndresOrtegaGuerrero approved these changes

2023-06-08 10:39 UTC, unkcpz commented on aiidalab_qe/app/report.py
> +    if pseudo_library == "SSSP":
We shouldn't put the logit in `report.py`, very error-prone.

2023-06-08 10:40 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> -                "pseudo_protocol": pseudo_family_info[3],
TBH, removing this and putting the logic to "viewer" the `report.py` is going back to where before I did the refactoring.

2023-06-08 10:43 UTC, unkcpz commented on aiidalab_qe/app/sssp.py
> +            p_family, p_version, p_func, p_type = pseudo.split("/")
Instead of if..else and calling`run_` in two place, please just construct the command options list and call `run_` once.

2023-06-08 10:45 UTC, unkcpz requested changes
Thanks @superstar54, some change requests.

2023-06-08 11:50 UTC, superstar54 commented
@unkcpz thanks for the review, I have addressed all the requests.

2023-06-08 12:10 UTC, unkcpz commented on aiidalab_qe/app/pseudos.py
> +            self.value = DEFAULT_PARAMETERS["pseudo_family"]
I am a bit worried about the complex if..else nest here. Can you check it again if you can make it more clear?

2023-06-08 12:16 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/pseudos.py
> +            self.value = DEFAULT_PARAMETERS["pseudo_family"]
@superstar54  perhaps you can put the option in a dictionary and evaluate the key ?

2023-06-19 16:16 UTC, unkcpz commented on aiidalab_qe/app/pseudos.py
> +            self.value = DEFAULT_PARAMETERS["pseudo_family"]
@AndresOrtegaGuerrero, I don't quite understand what you mean. @superstar54, can you try to address it? 
Then we can merge this PR.

2023-06-20 06:55 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/pseudos.py
> +            self.value = DEFAULT_PARAMETERS["pseudo_family"]
@superstar54 you can ignore my suggestion and merge if you want

2023-06-20 07:59 UTC, superstar54 commented on aiidalab_qe/app/pseudos.py
> +            self.value = DEFAULT_PARAMETERS["pseudo_family"]
Thanks for the suggestions. I updated the code to make the string pretty and hopefully more clear. A test is also added for the `PseudoFamilySelector` widget.

2023-06-20 08:32 UTC, merged