bump AWB to released 2.0
aiidalab/aiidalab-qe pull request #394
Opened 2023-05-08 15:26 UTC by unkcpz

2023-05-08 17:17 UTC, unkcpz commented on setup.cfg
> +    pybtex==0.24.0
This somehow has to be pinned, because of the issue https://github.com/aiidalab/aiidalab-qe/actions/runs/4917462707/jobs/8782576404. It also fails the test of aiidalab-docker-stack in https://github.com/aiidalab/aiidalab-docker-stack/pull/374

2023-05-09 07:07 UTC, superstar54 requested changes

2023-05-09 07:07 UTC, superstar54 commented on setup.cfg
> -    Jinja2~=3.0
Please keep jinjia2 and importlib-resources here. Otherwise, the dependency is not clear.

2023-05-09 07:50 UTC, unkcpz commented on setup.cfg
> -    Jinja2~=3.0
Yes, make sense. I delete it for test. You are correct, since it is used in the package, better to keep in the dependencies list.

2023-05-09 07:53 UTC, unkcpz commented on setup.cfg
> -    Jinja2~=3.0
But I loose the version a bit so it more flexible to the change from upstream packages, e.g aiida-core and aiida-quantumespresso.

2023-05-09 09:05 UTC, superstar54 approved these changes

2023-05-09 09:06 UTC, merged