seprate workchain selector to be extendable
aiidalab/aiidalab-qe pull request #401
Opened 2023-05-18 13:50 UTC by unkcpz

fixes https://github.com/aiidalab/aiidalab-qe/issues/388
This PR is also an attempt of https://github.com/aiidalab/aiidalab-widgets-base/issues/382.

2023-05-18 16:51 UTC, danielhollas commented on aiidalab_qe/app/process.py
> +    EXTRA_FIELDS = None
Since this class attribute is meant to be overriden, it probably shouldn't be in all caps? Same with `FMT_WORKCHAIN`.

2023-05-18 17:21 UTC, danielhollas requested changes
@unkcpz this looks great, thanks! Let's try it out here, and then later we can upstream to AWB.

Except for some minor comments / suggestions that you can feel free to ignore, there is one subtle thing about triggering a refresh upon submitted WorkChain completion.

2023-05-18 17:21 UTC, danielhollas commented on aiidalab_qe/app/process.py
> +    BASE_FIELDS = [("pk", int), ("ctime", str), ("state", str)]
Perhaps to make this more readable and safer, you could define a namedtuple tor the elements of this list. Maybe something like

```
WorkChainField= namedtuple("WorkChainField", "field type")

BASE_FIELDS = [WorkChainField("pk", int), WorkChainField("ctime", str), WorkChainField("state", str)] 
```

But perhaps that's too verbose, I dunno...

2023-05-18 17:21 UTC, danielhollas commented on aiidalab_qe/app/process.py
> +    def parse_extra_info(self, uuid):
In the parent class, you're passing `pk`, not `uuid`.

2023-05-18 17:21 UTC, danielhollas commented on qe.ipynb
If you look closely at the corresponding PR in my app, I've added one extra hack, where I trigger the workchain selector refresh when a submitted workflow finishes. That way the process status in the selector is updated from "Running" to "Finished". This is a bit ugly since I need to directly patch the ProcessMonitor object in one of the Step classes, the but it works. 

https://github.com/ispg-group/aiidalab-ispg/pull/177/files#diff-5c45c68ed738fa714abe5583a6dabb14053e4cc0c93d8b253292d1cca0464a6aR162

2023-05-23 22:05 UTC, danielhollas commented
@unkcpz since there is already an associated issue, I've removed this PR from the AiiDAlab project to avoid duplication. Hope that's okay.

2023-05-23 23:15 UTC, unkcpz commented
Sure, thanks! If you mean it is duplicated with https://github.com/aiidalab/aiidalab-qe/issues/388 which is already in the current sprint. I was adding this to the project in order to set it to the current sprint so I didn't forget to bring it up in the meeting (I admit this is not the original way we plan to use the sprint, but for myself it a bit easy to track everything happened. I start to have a very bad memory among a couple of things 😿 ).

2023-05-25 17:02 UTC, unkcpz commented on aiidalab_qe/app/process.py
> +    def parse_extra_info(self, uuid):
Yes, my carelessness.

2023-05-25 17:05 UTC, unkcpz commented on qe.ipynb
Interesting, this is cool. I also mad `process_monitor` the interface of `ViewQeAppWorkCHainStatusAndStep` so it is designed to be used as such, then it is not very hacked.

2023-05-25 17:11 UTC, unkcpz commented on aiidalab_qe/app/process.py
> +    BASE_FIELDS = [("pk", int), ("ctime", str), ("state", str)]
It is a bit redundant to me, in design the `WorkChainSelector` will be used as the parent class, and having the extra_fields override, it means the `WorkchainField` also need to be imported, not very convenient in my opinion.

2023-05-25 17:12 UTC, unkcpz commented on aiidalab_qe/app/process.py
> +    EXTRA_FIELDS = None
Yep, changed and add a docstring for how to subclass and extend it.`

2023-05-25 17:30 UTC, danielhollas approved these changes
Just a two short suggestions, otherwise I am approving....

2023-05-25 17:31 UTC, danielhollas commented on qe.ipynb
Fair enough. The `on_sealed` callbacks are called when the process finishes. Normally one should passed them via the class constructor, so what I am doing is definitely hacky, since I am touching the internal implementation of ProcessMonitor.

2023-05-25 20:44 UTC, danielhollas requested changes
@unkcpz have you tested your latest changes? Found a bug while I was transplanting this into my app.

2023-05-25 20:44 UTC, danielhollas commented on aiidalab_qe/app/process.py
> +    EXTRA_FIELDS = [("formula", str), ("relax_info", str), ("properties_info", str)]
```suggestion
    extra_fields = [("formula", str), ("relax_info", str), ("properties_info", str)]
```

2023-05-25 20:51 UTC, danielhollas commented on aiidalab_qe/app/process.py
> +    @abc.abstractmethod
Indeed, I just tested that the `@abc.abstractmethod` decorator does not work in this case (i.e. I can instantatiate a subclass that does not implement this method). For it to work, you'd need to inherit from the ABC class.

https://docs.python.org/3/library/abc.html#abc.abstractmethod

2023-05-25 21:07 UTC, unkcpz commented on aiidalab_qe/app/process.py
> +    EXTRA_FIELDS = [("formula", str), ("relax_info", str), ("properties_info", str)]
oops! I just did a quick test by launching a calculation, and didn't find this. BIG FAILURE 😿

2023-05-25 21:07 UTC, unkcpz commented on aiidalab_qe/app/process.py
> +    FMT_WORKCHAIN = "{wc.pk:6}{wc.ctime:>10}\t{wc.state:<16}"
Good idea, changed.

2023-05-25 21:09 UTC, unkcpz commented on aiidalab_qe/app/process.py
> +    @abc.abstractmethod
Yeah, I try to use it as a placeholder. The parent class here is not an `ABCMeta`.

2023-05-25 21:11 UTC, unkcpz commented on aiidalab_qe/app/process.py
> +    @abc.abstractmethod
But seems this is a misuse 🙅

2023-05-26 00:03 UTC, danielhollas approved these changes
Awesome. I've transplanted this to my app and everything is much cleaner now, thanks!

2023-05-26 08:48 UTC, merged