Feature/adv tot charge
aiidalab/aiidalab-qe pull request #402
Opened 2023-05-23 10:32 UTC by AndresOrtegaGuerrero

This PR updates #377 to be compatible with the new re factoring

2023-05-24 13:50 UTC, AndresOrtegaGuerrero commented
@mbercx  I was wondering if maybe you could give me a hint of what could be the sources in the failure of our test with python 3.9 and 3.8 ??

2023-05-24 15:47 UTC, mbercx commented
@AndresOrtegaGuerrero thanks for the ping! Yeah our nightly builds also started failing, not sure what's going on, but will prioritise fixing it! Very weird that even the released version `4.3.0` is suddenly failing...

2023-05-24 16:14 UTC, mbercx commented
Probably related to https://github.com/explosion/spaCy/issues/12659

2023-05-24 16:51 UTC, mbercx commented
Was most likely due to a bug in `pydantic~=1.10`, now fixed in `1.10.8`. I've opened a PR to adapt the dependency:

https://github.com/aiidateam/aiida-quantumespresso/pull/941

I reran some tests that were failing for an `aiida-quantumespresso` PR, which now pass. But here the `pydantic` version seems somehow restricted, since the CI is installing version `1.10.2`. Not sure why, but let's see what happens after my PR is merged and release a hotfix version `3.4.1`.

2023-05-24 18:28 UTC, AndresOrtegaGuerrero commented
> Was most likely due to a bug in `pydantic~=1.10`, now fixed in `1.10.8`. I've opened a PR to adapt the dependency:
> 
> [aiidateam/aiida-quantumespresso#941](https://github.com/aiidateam/aiida-quantumespresso/pull/941)
> 
> I reran some tests that were failing for an `aiida-quantumespresso` PR, which now pass. But here the `pydantic` version seems somehow restricted, since the CI is installing version `1.10.2`. Not sure why, but let's see what happens after my PR is merged and release a hotfix version `3.4.1`.

Thank you !

2023-05-24 23:35 UTC, unkcpz requested changes
@AndresOrtegaGuerrero thanks a lot! 

I am wondering how we categorize parameters as "advanced". One option is anything beyond protocol is advanced. Or the smearing and kpoints overrides are categorized as advance setting as well. 

And what confuses me most is that we already have the `Advance Setting` tab but it has another advance setting. I think it is true we need a parent widget to collect all such "advance setting" widgets in one. Why not we put all the widgets in "Advance Settings" tab to a widget called `AdvanceSettings` and manage the display there solely?

2023-05-24 23:35 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        if builder.relax.base["pw"]["parameters"]["SYSTEM"]["tot_charge"]:
```suggestion
        tot_charge = builder.relax.base["pw"]["parameters"]["SYSTEM"]["tot_charge"]
        if total_charge:
```
This better move to above under the comment where said why the value getting from `builder.relax.base` is feasible.  

I also don't quite understand, the `tot_charge` can be a `None`?

2023-05-24 23:35 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                    ] = self.pw_advanced_settings.tot_charge.value
Can we always have this value in the workflow input, the default value is `0.0`. When pass from widget to workchain, it assure it is not `None`. This will make the workflow (model) part more clear.

2023-05-24 23:35 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        <h4>Pw Advanced Settings</h4></div>"""
"Pw" is not easy to be understood by people who don't very familiar with QE. I was wondering, can we have the widget called `AdvancedSettings` and having all tricky parameters setting included parameters of dos.x and projwfc.x if we have it in the future.

2023-05-24 23:35 UTC, unkcpz commented on aiidalab_qe/app/static/workflow_summary.jinja
> +      {% if tot_charge %}
I don't think this logic is needed, if tot_charge not set, it is `0` by default, we can show it as well.

2023-05-24 23:35 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        self.tot_charge = ipw.IntSlider(
The total change can be a real number accourding to https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm289. I also prefer using the text input widget which is conformed with smearing width and k-distance widgets.

2023-05-26 06:45 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        if builder.relax.base["pw"]["parameters"]["SYSTEM"]["tot_charge"]:
Yeah it can be done, it they do not apply advanced settings

2023-05-26 06:47 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/static/workflow_summary.jinja
> +      {% if tot_charge %}
Is needed, since if the user doesnt activate the tot_charge , that value should be None. Thats why the widget has a general override, so the user can determine if advanced setting will be use, and then tot_charge ,( or any future option) should have also an override (to determine if you want to use it)

2023-05-26 06:50 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        self.tot_charge = ipw.IntSlider(
Ok, I will do this change. (i need to check , if there should be some logic in case the user user letters instead of number)

2023-05-26 06:50 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        <h4>Pw Advanced Settings</h4></div>"""
Yes, I will do this change as well

2023-05-26 06:51 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +            if self.pw_advanced_settings.override_pw_advanced_settings.value:
Yes, for sure I will modify this name

2023-05-26 06:53 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +                    ] = self.pw_advanced_settings.tot_charge.value
I would prefer that is applied in all the steps, in any case i think is save. regarding the `None` that is why I use an override for the tot_charge, so it only checks or assigns if the user wanted to defined a tot_charge, otherwise why to assign it as `0.0`

2023-05-26 06:57 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +                    ] = self.pw_advanced_settings.tot_charge.value
Regarding having all widgets, would you prefer to be now included in `AdvancedSettings` ?

2023-05-30 15:07 UTC, AndresOrtegaGuerrero commented
> @AndresOrtegaGuerrero thanks! Look at the failed test on py3.10, the change on total charge is expected but I am worried about the kpoints_distance also changing. Can you check if the widget worked as expected that the kpoints can be correctly overrided?
> 
> To get the new regression tast data you just need to run `pytest tests/ --force-regen` (https://pytest-regressions.readthedocs.io/en/latest/overview.html#force-regen).

@unkcpz  I just updated the conftest

2023-05-30 15:13 UTC, AndresOrtegaGuerrero commented
@unkcpz  , there was a change in the [557a460](https://github.com/aiidalab/aiidalab-qe/pull/402/commits/557a460901fe99dd42f7d694a16397dacdf0ea69) I need to another commit

2023-05-30 15:20 UTC, AndresOrtegaGuerrero commented
@unkcpz  Now it should be fine

2023-05-30 21:02 UTC, unkcpz requested changes
@AndresOrtegaGuerrero Thanks again! Still, some minor requests, but the overall shape is very satisfactory.

2023-05-30 21:02 UTC, unkcpz commented on aiidalab_qe/app/static/workflow_summary.jinja
> +      {% if tot_charge %}
> if the user doesnt activate the tot_charge , that value should be None.

If tot_charge widget not activate, can it be set to `0.0`, then we don't need this `if tot_charge`. We can always have tot_charge in pw input file.

2023-05-31 08:11 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/static/workflow_summary.jinja
> +      {% if tot_charge %}
@unkcpz  The issue (i feel, not sure about it) is about compatibility (if we care at this point) , if calculations do not have the tot_charge in the parameters, an error will always be present to visualize the results. What do you think ?

2023-05-31 09:39 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/static/workflow_summary.jinja
> +      {% if tot_charge %}
I removed the logic

2023-05-31 14:05 UTC, unkcpz requested changes
Almost there, three tiny requests.

2023-05-31 14:05 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                        pw_overrides[key]["pw"]["parameters"]["SYSTEM"][
Why you remove the `setdefault` clause? Python dictionary method `setdefault()` is similar to get(), but will set dict[key]=default if key is not already in dict.

2023-05-31 14:05 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        tot_charge = builder.relax.base["pw"]["parameters"]["SYSTEM"]["tot_charge"]
It will fail if SYSTEM namelist don't have `tot_charge`, correct?

2023-05-31 14:05 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +
```suggestion
        parameters["tot_charge"] = builder.relax.base["pw"]["parameters"]["SYSTEM"].get("tot_charge", 0.0)
```

And probably better having a `_DEFAULT_TOT_CHARGE` for the class.

2023-05-31 14:16 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +                        pw_overrides[key]["pw"]["parameters"]["SYSTEM"][
@unkcpz  Because if `self.advanced_settings.override.value` can control if you are going to use overrides , and the next line already creates the dictionary `pw_overrides[key]["pw"] = {"parameters": {"SYSTEM": {}}}`.

2023-05-31 14:17 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        tot_charge = builder.relax.base["pw"]["parameters"]["SYSTEM"]["tot_charge"]
Yes, I will modify this

2023-05-31 14:36 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +
@unkcpz I  solve it but i didnt implement the _DEFAULT_TOT_CHARGE for the class, since that is a function

2023-05-31 14:47 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +
if i use the traitlets.Instance , it complaints is not defined , However it is not needed since the traitlets is now on `AdvancedSettings,` like it was for SmearingSettings and KpointsSettings in `ConfigureQeAppWorkChainStep` and `SubmitQeAppWorkChainStep`. So there shouldn't be an issue here

2023-05-31 15:10 UTC, unkcpz approved these changes
Two nitpicks, then it is fine to go. I approved it.

2023-05-31 15:10 UTC, unkcpz commented on aiidalab_qe/app/report.py
> +    yield "tot_charge", builder_parameters.get("tot_charge", None)
```suggestion
    yield "tot_charge", builder_parameters["tot_charge"]
```
We can do this now.

2023-05-31 15:10 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +
Okay, no problem from my side. Thanks!

2023-05-31 15:10 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                        pw_overrides[key]["pw"]["parameters"]["SYSTEM"][
I see, this is more clear, nice!

2023-05-31 15:10 UTC, unkcpz commented on tests/conftest.py
> +    # workchain_advanced_settings_generator,
```suggestion
```

2023-05-31 15:20 UTC, AndresOrtegaGuerrero commented
@unkcpz  I accepted your changes, thank you for all the input and help!

2023-05-31 21:52 UTC, unkcpz commented
@AndresOrtegaGuerrero thanks a lot for such nice work! Looking forward to reviewing more for new features.

2023-05-31 21:56 UTC, merged