Feature: Starting Magnetization
aiidalab/aiidalab-qe pull request #409
Opened 2023-06-01 11:09 UTC by AndresOrtegaGuerrero

This PR implements a class  `MagnetizationSettings` for Advanced Settings in the QE App, to be able to set initial_magnetic_moments in the calculations. 
The user can select the magnetization per kind defined in the `input_structure` 
![Screenshot 2023-06-01 at 13 06 46](https://github.com/aiidalab/aiidalab-qe/assets/34098967/0ab6d502-0aa3-4df1-936e-a5ca57fcae47)

2023-06-01 11:52 UTC, mbercx commented
Hi @AndresOrtegaGuerrero and @unkcpz! I will be very busy the next few weeks on other projects, so unless there is something specific needed from my end (i.e. on the `aiida-quantumespresso` plugin), I will not have time to review PRs on the QEapp.

In general, I've been less and less involved on the development there. I am simply spread too thin otherwise and then no work gets done anywhere. Apologies.

2023-06-28 08:03 UTC, unkcpz commented
A quick comment, if I didn't select structure, there is a dangling "override" checkbox there which looks a bit weird. I'd suggest having a text under the "Total charge" showing it is the placeholder for setting the initial magnetic moments.

![image](https://github.com/aiidalab/aiidalab-qe/assets/8831685/7fb12d6d-d241-482c-81aa-8076ec717445)

2023-06-28 08:35 UTC, unkcpz requested changes
@AndresOrtegaGuerrero thanks for adding this! I only have some minor requests, the overall implementation looks fine, cheers!

2023-06-28 09:56 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +    def _disable_kings_widgets(self, _=None):
hahahahah!

2023-06-29 09:17 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/static/workflow_summary.jinja
> +        <td>Init. Magnetic Moments</td>
I will update this

2023-06-29 09:30 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +                    and self.workchain_settings.spin_type.value == "collinear"
To define if you are using spin is 
```
        self.spin_type = ipw.ToggleButtons(
            options=[("Off", "none"), ("On", "collinear")],
            value=DEFAULT_PARAMETERS["spin_type"],
            style={"description_width": "initial"},
        )
```

2023-06-29 09:36 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +            initial_magnetic_moments=starting_magnetization,
i will update this

2023-06-30 14:58 UTC, AndresOrtegaGuerrero commented
@unkcpz  Thank you for your suggestions and help. I just added another test for advanced settings and adapted your suggestions. Let me know what you think.

2023-07-01 22:29 UTC, unkcpz requested changes
Thanks @AndresOrtegaGuerrero, three minor requests. It is all fine then.

2023-07-01 22:29 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +    """Widget to set the initial_magnetic_moments from each Kind in StructureData
```suggestion
    """Widget to set initial magnetic moments for each `Kind` (usually the element name, but you can use `Fe1`, `Fe2` to distinguish iron atoms of different sites) of `StructureData`
```

Am I rephrasing it correctly? Please feel free to polish what I wrote.

2023-07-01 22:29 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                float_widget = ipw.BoundedFloatText(
No a big issue since it as a local variable, but I prefer `bounded_float` or simply `w`. `float_widget` seems a bit like a widget that can float on the webpage. Feel free to ignore this comment.

2023-07-01 22:29 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +            kinds_widget = ipw.VBox([ipw.HTML("Define magnetization")] + widgets_list)
Here you didn't use HTML tags for formatting, is `ipw.HTML` really needed?

2023-07-01 22:29 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                float_widget = ipw.BoundedFloatText(
And why not do like this?

```python
hbox = ipw.HBox(
    children=[
        ipw.BoundedFloatText(...
    ]
)
```

2023-07-01 22:29 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                self.kinds.children[i].children[0].value = 0.0
I understand why it has to set the value like this, from range 1 to skip the HTML widget of index 0, and second children for the `HBox`.  But it is a bit complex and error-prone when looking at this loop independently. Not sure there is a better way, I think having a Kind widget might be too much. 
Just think about it, if there is not better way to make it clear, leave it as this and add a comment for why start loop from index 1 and what the second children refer to.

2023-07-01 22:29 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +                    and self.workchain_settings.spin_type.value == "collinear"
I see, fair. 👍

2023-07-01 22:29 UTC, unkcpz commented on tests/test_submit_qe_workchain.py
> +    """ "Test the creation of the workchain builder.
```suggestion
    """Test the creation of the workchain builder.
```

2023-07-01 22:29 UTC, unkcpz commented on tests/test_submit_qe_workchain.py
> +def test_create_builder_advanced_settings(
Thanks a lot for this test, very useful!

2023-07-02 14:25 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +    """Widget to set the initial_magnetic_moments from each Kind in StructureData
Thank you i will expand this 👍

2023-07-02 17:08 UTC, AndresOrtegaGuerrero commented on tests/test_submit_qe_workchain.py
> +def test_create_builder_advanced_settings(
Yes i think here we can add the test for new advanced settings :)

2023-07-02 17:09 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +                self.kinds.children[i].children[0].value = 0.0
I will update in such a way that is a VBox instead and to access the valees is `self.kinds.children[i].value`

2023-07-02 17:09 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +            kinds_widget = ipw.VBox([ipw.HTML("Define magnetization")] + widgets_list)
I will modify this

2023-07-02 17:13 UTC, AndresOrtegaGuerrero commented
@unkcpz  Let me know i adapted the code :)

2023-07-03 13:29 UTC, unkcpz approved these changes
Hi @AndresOrtegaGuerrero, It is all fine. I have one question about the `PYTEST_CURRENT_TEST`, but I approve it anyway since the logic is all great for me.

2023-07-03 13:29 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        if "PYTEST_CURRENT_TEST" not in os.environ and self.kinds:
Interesting, I didn't know this `PYTEST_CURRENT_TEST`. Can you double check this is really needed here? I think even is a test it should be found to clear_output and display. Am I missing something?

2023-07-03 13:54 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        if "PYTEST_CURRENT_TEST" not in os.environ and self.kinds:
If i dont use this , it will return the widget during the pytest, so to avoid this behaviour i use the display and clear only if i am not in a pytest , but i do the update before.

2023-07-03 22:12 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        if "PYTEST_CURRENT_TEST" not in os.environ and self.kinds:
Sorry, I didn't understand, what will happen if the widget is returned during pytest, the test will fail? with what exception?

2023-07-04 06:55 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        if "PYTEST_CURRENT_TEST" not in os.environ and self.kinds:
@unkcpz  The test wont fail , but during the test in the terminal it will print the widget as text

2023-07-04 07:37 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        if "PYTEST_CURRENT_TEST" not in os.environ and self.kinds:
Did you use `pytest -s`?  Other wise it should not print things. If this is not needed, I'd not add it. 
Sorry for the back-and-forth on this PR.

2023-07-04 08:07 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/steps.py
> +        if "PYTEST_CURRENT_TEST" not in os.environ and self.kinds:
@unkcpz  I did the test without with `pytest -s` without this and the issue occurs, the test passed but it returns the object in this case a VBox

2023-07-04 13:38 UTC, unkcpz commented on aiidalab_qe/app/steps.py
> +        if "PYTEST_CURRENT_TEST" not in os.environ and self.kinds:
> I did the test with `pytest -s`

Yep, `-s` is to print things to the stdout. I think it is fair to suppress it with your way, otherwise run with `-s` locally would be a mess. 

All good to me now. Do you mind merge this one with writing a description of the commit message? Just click the "squash and merge" below and input the message in the dialog.

2023-07-04 14:35 UTC, merged