Feature/ Tags editor to define Kinds in StructureData
aiidalab/aiidalab-qe pull request #410
Opened 2023-06-01 11:33 UTC by AndresOrtegaGuerrero

This PR implements an Editor for the QE App, to enable the user to define extra kinds within a structure. For example if you have a system compose with Fe atoms, you can define Fe1, and Fe2 based on a selection. This editor is intended to facilitated spin polarisation calculations with #409 

![Screenshot 2023-06-01 at 13 24 14](https://github.com/aiidalab/aiidalab-qe/assets/34098967/f952b23c-b574-441a-940e-e62bfb68ed9c)

2023-06-19 16:18 UTC, unkcpz commented
@superstar54, can you give this one a review? Thanks!

2023-06-20 08:12 UTC, superstar54 requested changes
@AndresOrtegaGuerrero Thanks for adding this. It would be very useful for advanced calculation.
Could you add a section to show all tags of all atoms? In this case, the user can make sure the tag is updated successfully.

2023-06-20 08:12 UTC, superstar54 commented on aiidalab_qe/app/widgets.py
> +            description="Define kind", value="", layout={"width": "initial"}
```suggestion
            description="Index of atoms", value="", layout={"width": "initial"}
```

2023-06-20 08:12 UTC, superstar54 commented on aiidalab_qe/app/widgets.py
> +            new_tags[selection] = 0
When clearing tags, you set the tag value to 0. It is more like `reset` , so maybe change `clear` to `reset`.

2023-06-20 11:11 UTC, AndresOrtegaGuerrero commented
> @AndresOrtegaGuerrero Thanks for adding this. It would be very useful for advanced calculation. Could you add a section to show all tags of all atoms? In this case, the user can make sure the tag is updated successfully.

@superstar54 How would you suggest to do the visualisation (Is something i have been wondering) ? Because the system can have a good amount of atoms.

2023-06-20 13:31 UTC, superstar54 commented
> Because the system can have a good amount of atoms.

One option would be only to show the tags of the selected atoms.

2023-06-30 14:59 UTC, AndresOrtegaGuerrero commented
@superstar54 I just adapted the changes you suggested , let me know.

2023-07-05 07:53 UTC, superstar54 commented
Thanks!  I see the tags of selected atoms. Not it shows in one line, e.g.:

`Id: 5 O4 ; Id: 1 Si ; Id: 2 Si2 ; Id: 3 O2`

Better to make a table like this:
| Index | element| tag|
|--|--|--|
|5|O|4|
|1|Si||
|2|Si|2|
|3|O|2|

2023-07-05 09:41 UTC, superstar54 approved these changes
Perfect! Thanks!

2023-07-05 12:08 UTC, merged