Plugin UI
aiidalab/aiidalab-qe pull request #428
Opened 2023-06-28 07:16 UTC by superstar54

This is still a draft.

- create a QeApp class
- for each step, the class has a parent attribute
- `workchain_settings` is split into basic settings (spin, electronic type ...) and `workflow`.
- `pseudo_family_selector` and `advanced_settings` are merged into `advance_settings`
- link basic protocol to all plugin-specific protocols
- removed the `workchain_settings`, `pseudo_family_selector` and `advanced_settings` traitlets because they are not used anymore. They can be read by other steps (e.g., step 3 submit) from the parent.

2023-07-06 11:52 UTC, superstar54 commented
@unkcpz @mbercx Please review this PR after the AiiDA coding week.

@AndresOrtegaGuerrero Please review this PR when you have time.

2023-07-06 11:53 UTC, unkcpz commented
Thanks @superstar54, super great! Let's have a quick touch base in 7 mins. I also ask @mikibonacci to join and to review this one. It is a huge PR, better to get more opinions and ideas on it.

2023-07-06 11:54 UTC, unkcpz commented
There are lots of conflicts, are you manage to resolve those?

2023-07-10 06:57 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/app.py
> +class QEApp:
Maybe lets include some Docstring on this class

2023-07-10 07:03 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +    title = "Advanced Settings"
I am more incline to have an override per setting, I think the user can be prone to set things they arent meant to modify.

2023-07-10 07:06 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +
Does this set_panel_value works as a reset? We should have a single method to reset this class so when the user click new workflow we can guarantee all these variables were properly reset,

2023-07-10 09:30 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +            self.tot_charge,
Could you include the one of magnetization? and the editor

2023-07-13 11:03 UTC, superstar54 commented on aiidalab_qe/app/app.py
> +class QEApp:
Done!

2023-07-13 11:06 UTC, superstar54 commented on aiidalab_qe/app/configure/advanced.py
> +
In the `Panel` class, there is a method called `reset()` which will use `DEFAULT_PARAMETERS` to reset the panel. I updated this method for the settings (basic, advanced)

2023-07-13 11:08 UTC, superstar54 commented on aiidalab_qe/app/configure/advanced.py
> +            self.tot_charge,
Yes, I added `magnetization` (in `advanced` panel) and `editor` ( in `structure.py` file). For the `magnetization`, I updated the `_set_magnetization_values` method and also the test. Please check.

2023-07-13 14:34 UTC, superstar54 commented
> There are lots of conflicts, are you manage to resolve those?

I fixed the conflicts. Please have a look.

2023-07-18 07:37 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +                    min=-1,
Could you increase the min=-4 and max=4 , I realize that -1, and 1 could be to small in some cases

2023-07-20 10:25 UTC, mikibonacci commented on aiidalab_qe/app/configure/advanced.py
> +    def create_kinds_widget(self):
The kind feature may be useful also for other properties (hubbard, charge). If I get it correctly, here is only activated for magnetization, right?

2023-07-20 10:43 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +    def create_kinds_widget(self):
The kinds are define first in the StructureData, using the AddingTags editor , so the Magnetization can use these kinds to set the starting_magnetization per kind in StructureData

2023-07-20 11:50 UTC, mikibonacci commented on aiidalab_qe/app/submit/resources.py
maybe we need to set separately resources for different codes. But I'll open an issue on github after the merge

2023-07-20 12:23 UTC, superstar54 commented on aiidalab_qe/app/submit/resources.py
Yes, it would be nice to have this feature. This is supposed to be the third step. #426

2023-07-24 07:04 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/parameters/qeapp.yaml
> +    kpoints_distance_override:
perhaps put total charge as `0`

2023-07-24 12:17 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +        self.kpoints_distance = ipw.FloatText(
We should change this one to a BoundedFloatText and prevent the widget to get negative values

2023-07-24 12:18 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +        self.pseudo_family_selector = PseudoFamilySelector()
When you start the app , the override from the PseudoFamilySelector is active

2023-07-24 12:21 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/plugins/bands/setting.py
> +            description="Bands path:",
What is the purpose of this widget ? should we using SeekPath and display the path from the structure ? Perhaps some docstring for these panels is necessary

2023-07-24 12:23 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/plugins/bands/setting.py
> +    title = "Bands Structure Settings"
This title is quite long, and it doesn't display completely. appears as `Bands Structure Setti`

2023-07-24 12:25 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/configure/advanced.py
> +        self.pseudo_family_selector = PseudoFamilySelector()
The same applies to the MagnetizationSettings()

2023-07-27 08:23 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/plugins/bands/workchain.py
> +        "scf": parameters["advanced"],
Here we should include nscf , because if we update the kpoints_distance , when you decrease the value it doesnt update nscf

2023-07-27 14:50 UTC, unkcpz requested changes
Thanks @superstar54, thanks a lot for the work! 

The moving of files and modules seems not very clear to me, do you have guidelines on how to organize the modules and files? Originally, in the `app` folder there are files contains widgets for specific functionality widgets (maybe not very strict but it is still easy to find where the widgets are located). It is confused because there are folder "configure", what is that for? The "structures.py" and "steps.py" which are still dangling in the "app" folder. 

You said this PR is only about the UI, so I'd prefer you roll back the folder reorganization and leave it to another PR, is that too much work for you? From what you write here (https://hackmd.io/Pze_b838SIKx150NAnFP1w#Step-1-PR-for-UI), the reorganization of the files seems not in the tasks. 
I personally would be more cautious about always making unnecessary changes. Maybe you can:
1. first add features and make "must happened" changes in the PR. 
2. then use another PR to move modules and files for the clear organization of components for feature adding.

2023-07-27 14:50 UTC, unkcpz commented on aiidalab_qe/app/__init__.py
> +# 2) tp speed up import
Do you really sure this will speed up the import? In the qe.ipynb you're import modules anyway.

> they are not used elsewhele

This is not true, depends on how you import modules in the `qe.ipynb`, you can use the full path or use the shortcut path if the modules are exposed in this file.

2023-07-27 14:50 UTC, unkcpz commented on qe.ipynb
> +    "from aiidalab_qe.app.app import QEApp\n",
TBH, I don't think this is a good idea to tuck everything in `app.app` which is already confused in the module name. 

The notebook should be structured enough to should the basic function of the app (TBD). The changes to me didn't make things more clear.

2023-07-27 14:59 UTC, unkcpz commented on aiidalab_qe/app/__init__.py
> +# 2) tp speed up import
With a second look, I think the `QeApp` class should be moved to this file. 
Any thoughts @AndresOrtegaGuerrero @mikibonacci?

2023-08-07 09:39 UTC, superstar54 commented on aiidalab_qe/app/plugins/bands/setting.py
> +    title = "Bands Structure Settings"
I changed the title to "Bands Structure". This panel is only for illustration and will be deleted before mering this PR.

2023-08-10 09:19 UTC, superstar54 commented on aiidalab_qe/app/parameters/qeapp.yaml
> +    kpoints_distance_override:
Sure, I added `tot_charge` as 0.

2023-08-10 09:20 UTC, superstar54 commented on aiidalab_qe/app/configure/advanced.py
> +        self.kpoints_distance = ipw.FloatText(
Sure, I changed it to `BoundedFloatText` and set the `min` as 0.

2023-08-10 09:26 UTC, superstar54 commented on aiidalab_qe/app/configure/advanced.py
> +        self.pseudo_family_selector = PseudoFamilySelector()
Thanks! I changed the override to inactive.

2023-08-10 09:53 UTC, AndresOrtegaGuerrero commented on aiidalab_qe/app/plugins/bands/workchain.py
> +        "scf": parameters["advanced"],
ok , yes, it is needed otherwise it is not consistent with the Pdosworkchain

2023-08-13 09:50 UTC, superstar54 commented
@unkcpz Thanks for the discussion.
I made all the changes:
- rename `submit.py` to  `__init__.py` file, same to `configure` and `app`.
- the `common` folder is used.


## Folder structure

There are four steps in QeApp. There were all in the `step.py` file before, which made the code hard to read and maintain. I split the file and put them in different folders/files.

- step 1: **structure.py** file. We can create a folder for this step, if more settings are added in the future.
- step 2: **configure** folder
  - configure.py (can be renamed to \_\_init\_\_.py)
  - workflow.py
  - basic.py
  - advanced.py
- step 3: **submit** folder
  - submit.py
  - resources.py
- step 4: **result** folder
  - result.py
  - node_view.py
  - summary_view.py
  - electronic_structure.py

There is a new folder `plugins`, in which the settings for each plugin are stored.

- **plugins** folder
  - relax folder
  - bands folder
  - pdos folder

Here are the other files:

- pseudos.py ( step 2 configure)
- sssp.py ( step 3 submit)
- steup_codes.py (common)
- process.py (common)
- widgets.py (common)
- utils.py (common)
- panel.py (common)

2023-08-13 09:59 UTC, superstar54 commented on aiidalab_qe/app/configure/advanced.py
> +                    min=-1,
Yes, I changed the values to -4 and 4.

2023-08-13 13:27 UTC, superstar54 commented on aiidalab_qe/app/configure/advanced.py
> +    title = "Advanced Settings"
I think putting an override box for each parameter is unnecessary. The panel already shows the warning message at the top. When the user ticks the override box, they confirm that they know the meaning of the settings. If a user still wants to set things they do not understand, adding another override box will not stop them from doing it. Also, it makes the code hard to maintain and the UI not pretty.

2023-08-14 09:07 UTC, unkcpz requested changes
Hi @superstar54, thanks, have a go-through for all changes. It is still not easy to review I have to say.

2023-08-14 09:07 UTC, unkcpz commented on aiidalab_qe/workflows/__init__.py
> +            get_builder as get_relax_builder,
Is these modules loaded can be dynamically? The current implementation means adding a new property calculation need add a new import clause here.

2023-08-14 09:07 UTC, unkcpz commented on aiidalab_qe/workflows/__init__.py
> +        builder.relax = relax_builder
I think you use `get_builder` from class and `get_**_builder` from sub module, can you make this more clear? If this need to do with next PR you are going to implemented, let's do it later. This is confusing.

2023-08-15 09:36 UTC, unkcpz commented
Hi @superstar54, if I understand correctly, the plugin mechanism is based on the "entry_points" defined globally, and different components get the information and show the tabs accordingly. 
Can you explain a bit about how selecting different properties in step 2 make the results panel changes tabs? I cannot figure out what information pass from step 2 to step 4. Is there an interface defined as the traitlets that can influence how the step 4 panel show the tabs?

2023-08-15 09:45 UTC, superstar54 commented on aiidalab_qe/app/result/node_view.py
> +            self.result_tabs.set_title(len(self.result_tabs.children) - 1, result.title)
@unkcpz Here, it mounts all panels to the result step. Later, in lines 314-322, it will only show the panel if the result is ready.

2023-08-15 09:51 UTC, unkcpz commented on aiidalab_qe/app/result/node_view.py
> +                        else "orthographic"
Why the structure view related widget is in the workchain viewer?

2023-08-15 09:52 UTC, unkcpz commented on aiidalab_qe/app/result/node_view.py
> +            self.result_tabs.set_title(len(self.result_tabs.children) - 1, result.title)
Okay, thanks. Is that possible to make this a common pattern and having a generic widget that accept list entry_points and then shows tabs accordingly?

2023-08-15 20:18 UTC, unkcpz commented
I had a close look at you code, I am more sure that it is better to separate it to small things. You did the refactoring and the implementing a new “plugin” feature. But this plugin feature can be more clear implemented with a generic Accordin widget that tab dynamiclly changed with the inputs. 
I'd suggest to separate this large PR into following small PRs:
1. moving the modules and files to folders with desired categories.
2. reorganizing the basic setting and moving parameters setting widgets to new tabs (hard coded the tabs, "bands", "pdos")
3. Improve the Tab based step widget so the tab can be dynamically changed with one of its interfaces.
4. Use the improved widget to make the step 2 and step 4 can dynamically change the tab.

The new widgets you introduced in this large PR such as "Panel" can be the components of task 3 above. 

Let me know if this is feasible. I really like the design of the plugin, the final outcome looks more easy to add new properties and show the results clearly. I looking forward to getting it merged. However in the meantime I want to be a bit cautious about the robustness and ease of future maintenance, so I'll be a bit picky on some details.

2023-08-17 05:56 UTC, superstar54 commented on aiidalab_qe/app/common/panel.py
> +        pass
No. When the structure is confirmed in step 1, in step 2 (configure),  this method is called for every setting tab. Users can implement it when needed. But if nothing needs to be updated when the structure changed, just let it pass. and should not raise an error if not.

2023-08-17 05:58 UTC, superstar54 commented on aiidalab_qe/app/common/panel.py
> +DEFAULT_PARAMETERS = {}
For each setting panel, the user should provide the `DEFAULT_PARAMETERS`, which will be used to reset the panel. It can be either read from the `qeapp.yaml`, or provided by the user in the plugin.

2023-08-17 06:07 UTC, superstar54 commented on aiidalab_qe/app/common/panel.py
> +        # Checkbox to see if the abc should be calculated
It is the `property`, e.g. bands, pdos, xps. I changed it to `property`.

2023-08-17 06:08 UTC, superstar54 commented on aiidalab_qe/app/common/utils.py
> +    print(get_entries())
Yes, I removed it.

2023-08-17 06:16 UTC, superstar54 commented on aiidalab_qe/app/configure/basic.py
> +DEFAULT_PARAMETERS = QEAPP_DEFAULT_PARAMETERS["basic"]
It is used in the `reset` method, in principle, it should not be changed. But, yes, there is a risk that the developer change it unintentionally. One solution is to provide a `yaml` file for each plugin, what do you think?

2023-08-17 06:27 UTC, superstar54 commented on aiidalab_qe/app/plugins/bands/setting.py
> +    * Xing Wang <xing.wang@psi.ch>
This is copied from a template by accident. I removed it.

2023-08-17 07:27 UTC, superstar54 commented on aiidalab_qe/app/result/summary_view.py
> +                str(report_dict[f"K-point mesh distance ({calc})"][0])
I don't understand your question. By the way, this function `generate_report_text` is not used anywhere. We may open another PR if a change is needed.

2023-08-17 07:30 UTC, superstar54 commented on aiidalab_qe/app/result/summary_view.py
> +    report_string += "."
`kpoints_calculations` is a list, and `join` is more convenient in this case. We may open another PR if a change is needed.

2023-08-17 07:32 UTC, superstar54 commented on aiidalab_qe/app/submit/__init__.py
> +    # TODO This should be rewrite using more general way for the plugin
Sure, I changed it to a comment. will open an issue when the PR get merged.

2023-08-17 07:38 UTC, superstar54 commented on aiidalab_qe/workflows/__init__.py
> +            get_builder as get_relax_builder,
Yes, this will be implemented in another PR that adds entry points to the workchain. For this PR, this is hard coded.

2023-08-17 07:39 UTC, superstar54 commented on aiidalab_qe/workflows/__init__.py
> +        builder.relax = relax_builder
Le's discuss this in the PR related to the workchain.

2023-08-17 07:55 UTC, superstar54 commented on aiidalab_qe/app/result/node_view.py
> +            self.result_tabs.set_title(len(self.result_tabs.children) - 1, result.title)
I think it is possible, and this is the direction we should go in the future.

2023-08-18 09:27 UTC, unkcpz commented on aiidalab_qe/app/common/panel.py
> +DEFAULT_PARAMETERS = {}
So it is not a constant? What will it change during the app's lifetime?

2023-08-18 09:30 UTC, unkcpz commented on aiidalab_qe/app/common/panel.py
> +        pass
Okay, since you have docstring, `pass` is not needed https://realpython.com/python-pass/#docstrings

2023-08-30 22:56 UTC, unkcpz commented on aiidalab_qe/app/plugins/bands/setting.py
> +            description="Bands path:",
Hi @superstar54, I saw in couple of places you resolve the conversation without changing the code. Did you forget to push?

2023-08-30 23:06 UTC, unkcpz commented
Hi @superstar54, I had another look at this PR. I really believe you can use band structure as the example to show most of things of this Panel concept. To me it looks like a new designed widget that will dynamically show in the step as a tab. Literally you can implement it without all other refactoring (and plus we already did most of modules/files moving).

2023-09-14 11:49 UTC, unkcpz commented
Hi @superstar54, can we close this one? Since we split it into small PRs.

2023-09-14 15:03 UTC, superstar54 commented
> Hi @superstar54, can we close this one? Since we split it into small PRs.

Yes.

2023-09-14 15:03 UTC, closed without merging