DOC: add xps to howto
aiidalab/aiidalab-qe pull request #438
Opened 2023-08-16 22:41 UTC by superstar54

This PR adds the doc for XPS calculation using the `plugin_workchain` branch of aiidalab-qe.

2024-02-22 16:57 UTC, PNOGillespie requested changes
Hi @superstar54, good work putting together a simple documentation set.

I've added some suggested some minor changes to fix typos and grammar in some places.

The more substantive changes are:
1. Step 2 is missing a picture of the XPS Settings tab.
2. There are parts towards the end which talk about the `offset energies` and the spin-orbit splitting, but lacks a prior step which explains how to export the data (beyond reading the value from the Plotly widget)
3. The real world example of ETFA doesn't seem to give much useful information for the user about the plugin (see the relevant comment for more information).

2024-02-22 16:57 UTC, PNOGillespie commented on docs/source/howto/xps.rst
> +This tutorial will guide you through the process of setting up and running a XPS calculation for CH\ :sub:`3`\CHO molecule.
```suggestion
This tutorial will guide you through the process of setting up and running an XPS calculation for CH\ :sub:`3`\CHO molecule.
```

2024-02-22 16:57 UTC, PNOGillespie commented on docs/source/howto/xps.rst
> +For this tutorial task, please use the `From Exmple` tab, and select the CH\ :sub:`3`\CHO molecule structure.
```suggestion
For this tutorial task, please use the `From Example` tab, and select the CH\ :sub:`3`\CHO molecule structure.
```

2024-02-22 16:57 UTC, PNOGillespie commented on docs/source/howto/xps.rst
> +    At present, the core-hole pseudopotential for Si and O only available in PBE functional.
```suggestion
    At present, core-hole pseudopotentials for Si and O are only available for the PBE functional.
```

2024-02-22 16:57 UTC, PNOGillespie commented on docs/source/howto/xps.rst
> +- In the **Select core-level** section, select ``C_1s``.
```suggestion
- In the **Select core-level** section, select ``C_1s`` by ticking the appropriate box.
```

2024-02-22 16:57 UTC, PNOGillespie commented on docs/source/howto/xps.rst
> +For this small system, we can use the local computer (``localhost``) to run the calculation. The code ``pw-7.2@localhost`` is already selected by default.
This is just to clarify for the user that this *should* be the case (and that there is an issue somewhere if it isn't). I know that QE fails to install on my own machine, for instance.
```suggestion
For this small system, we can use the local computer (``localhost``) to run the calculation. The code ``pw-7.2@localhost`` should already be selected by default.
```

2024-02-22 16:57 UTC, PNOGillespie commented on docs/source/howto/xps.rst
> +   Take `f` orbit as a example, we need subtracting :math:`3/7` of the experimental spin-orbit splitting or adding :math:`4/7` of the DFT calculated value, to get the position of the :math:`4f_{7/2}`
This section here could be useful, but (unless I'm mistaken) there is no way to extract the exact binding energy values from AiiDALab-QE.

If there is a way to do this, then please update some part of the text with instructions on how to do so, otherwise this doesn't provide much utility and should be removed for simplicity.

2024-02-22 16:57 UTC, PNOGillespie commented on docs/source/howto/xps.rst
> +
This last example doesn't seem to provide much for the user's benefit, for a few reasons:
1. The calculated and experimental spectra aren't plotted together for comparison.
2. Without a set of instructions, or source for the structure, the user can't use this like some sort of complex "real-world" example as an extension of the documentation and so it doesn't really add much.

I would suggest either removing the section or replacing the example with one for Phenacetylene, which we have tested already and can provide figures/data for.

2024-02-26 15:07 UTC, superstar54 commented on docs/source/howto/xps.rst
> +   Take `f` orbit as a example, we need subtracting :math:`3/7` of the experimental spin-orbit splitting or adding :math:`4/7` of the DFT calculated value, to get the position of the :math:`4f_{7/2}`
Thanks for pointing out this. I add the detail text to tell user how to find the exact binding energies.

2024-02-26 15:24 UTC, superstar54 commented
@PNOGillespie thanks for the review. I revised the page based on your suggestions. 

> Step 2 is missing a picture of the XPS Settings tab.

I added a picture.

> There are parts towards the end which talk about the offset energies and the spin-orbit splitting, but lacks a prior step which explains how to export the data (beyond reading the value from the Plotly widget)

I added a detailed instruction.

> The real world example of ETFA doesn't seem to give much useful information for the user about the plugin (see the relevant comment for more information).

I replied after your comment.

Please have a second review.

2024-02-29 15:01 UTC, PNOGillespie requested changes
Hi @superstar54. Looks good for the most part, particularly in providing a contrast between ETFA and Phenylacetylene. Just a few proofreading changes to make, then I think this is good to go.

Since you have added a spectrum upload tool (which seems to work fine, from what i can see) I would suggest (in a different PR) one improvement, which would be to add a UI element to scale the intensities of the computed XPS traces so as to make it easier to compare the profile of (in particular) the total XPS to the experimental data.

Again, I would just suggest you open an `improvements` issue for that and address that at a later time.

2024-02-29 15:36 UTC, superstar54 commented
Thanks @PNOGillespie . I created an issue as you suggested. #627

2024-02-29 15:46 UTC, PNOGillespie approved these changes
Good to go. Nice work @superstar54! Thanks also for adding the issue page.

2024-02-29 16:14 UTC, merged