Move to MainApp widget and call from notebook
aiidalab/aiidalab-qe pull request #442
Opened 2023-08-18 13:30 UTC by unkcpz

For the test purpose of https://github.com/aiidalab/aiidalab-qe/pull/428 proposed by @superstar54, we think moving the code from `qe.ipynb` into a module and creating an App class would make it not only more maintainable and easy for integrate unit test of the whole app as an widget.

2023-08-18 13:34 UTC, unkcpz commented
@superstar54 you mentioned the dlink may not necessary. I think it depends on the scenario and if you can decouple step widgets by adding another "data" layer in between. If you want to make such a change, please make a dedicated PR for that.

2023-08-24 12:22 UTC, superstar54 requested changes

2023-08-24 12:22 UTC, superstar54 commented on src/aiidalab_qe/app/main.py
> +class MainApp(ipw.VBox):
`MainApp` may mean there are other apps somewhere. Better use `App` or `QeApp`.

2023-08-24 12:22 UTC, superstar54 commented on src/aiidalab_qe/app/__init__.py
>      "WorkChainSelector",
we don't need to import these sub-modules here. they will not be used anywhere.

2023-08-24 14:35 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +class MainApp(ipw.VBox):
I was thinking of using the "main" as the C main function as the entry. No preference here. 

> MainApp may mean there are other apps somewhere.

So you think it will be other apps or not? `App` to me is too general `QeApp` is a bit redundant, because the whole thing is called QeApp already. 
Any preference from others @AndresOrtegaGuerrero @mikibonacci?

2023-08-24 14:37 UTC, unkcpz commented on src/aiidalab_qe/app/__init__.py
>      "WorkChainSelector",
True, it was there so I didn't delete it. But since we move things to a file, we can remove this.

2023-08-29 14:33 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +class MainApp(ipw.VBox):
Had an offline discussion with @superstar54 (we didn't fight, but almost :smile: ) Agreed on the compromised `App`. We think in two years, there won't be any new "Other" app added.

2023-08-29 15:05 UTC, superstar54 approved these changes
LGTM!

2023-08-29 15:16 UTC, merged