Advanced override setting unification
aiidalab/aiidalab-qe pull request #457
Opened 2023-09-04 14:43 UTC by unkcpz

- Remove override of sub-widgets of advanced setting
- Proper white box tests are added for widgets
- Move kpoints setting and totalchange setting into the advanced setting.

2023-09-04 14:44 UTC, unkcpz commented
There is a follow-up PR required to improve the magnatization setting widget and add a unit test for it.

2023-09-05 12:30 UTC, superstar54 requested changes
Thanks for the PR. I added a few suggestions.

2023-09-05 12:30 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/__init__.py
This is repeated. Please delete.

2023-09-05 12:30 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/advanced.py
> +        self.value = {k: v for k, v in kwargs.items()}
```suggestion
        self.value = kwargs
```

2023-09-05 12:30 UTC, superstar54 commented on tests/configuration/test_advanced.py
> +def test_advanced_kpoints_settings():
For the `kpoints_distance` and `total_charge`, because they are basic ipywidget, I think it doesn't need to test them separately. You already tested them when testing the advanced setting as a whole.

2023-09-05 13:01 UTC, superstar54 approved these changes

2023-09-05 14:13 UTC, merged