move get_configuration_parameters from submission to configuration
aiidalab/aiidalab-qe pull request #462
Opened 2023-09-08 11:47 UTC by superstar54

- move get_configuration_parameters from submission to configuration
- link the value of the `configuration  step` to the `input_parameters` of the submit step

2023-09-08 13:36 UTC, unkcpz commented on tests/conftest.py
> +        submit_step = app.steps[2][1]
```suggestion
        submit_step = app.submit_qe_app_work_chain_step
```

2023-09-08 13:40 UTC, unkcpz requested changes
Thanks! Two minor comments.

2023-09-08 13:40 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +            protocol=parameters["protocol"],
As we discussed offline, we agree keep on using dataclass is better for the moment.

2023-09-13 09:16 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +            protocol=parameters["protocol"],
After another discussion, it is better to use `dict` directly. Because the `value` of the configure step is now a traitlet and linked to the `input_parameters` (also a trailet) of the submit step. 

```
    # output dictionary
    value = tl.Dict()
```

2023-09-13 09:20 UTC, superstar54 commented
@unkcpz Thanks for the comments. I updated:
- In the report, remove `if` and use `.get(key, None)`, and remove all `None` values in the final step.
- Use the name of the step directly instead of steps[0][1]. Also, I renamed the step using a short name.

Please have another look.

2023-09-14 11:23 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +            protocol=parameters["protocol"],
Can we name it `configuration_parameters` as the function name has. The `value` of the step makes no much sense and is confusing.

2023-09-14 11:35 UTC, unkcpz requested changes
@superstar54 Thanks! Just minor requests.

2023-09-14 11:35 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +        return self._wizard_app_widget.steps
Not sure I understand this. Where is this property used?

2023-09-14 11:35 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +    yield "pdos_computed", builder_parameters.get("run_pdos", None)
The `None` is the default return value if the key not defined when using `.get`. So just do `builder_parameters.get("relax_type")`

2023-09-14 11:35 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +    report = {key: value for key, value in report.items() if value is not None}
:+1:

2023-09-14 11:35 UTC, unkcpz commented on tests/test_submit_qe_workchain.py
> +    #     assert parsed.find("initial_magnetic_moments").text == "None"
This actually change the behaviour of the original test and skipped the thing we want to test initially, that when the initial_magnetic_moment not set the report dict will not contain it.

Instead, of the changes, you can call `_generate_report_dict` and still have this behaviour tested.

2023-09-14 13:54 UTC, superstar54 commented on src/aiidalab_qe/app/main.py
> +        return self._wizard_app_widget.steps
It was used for tests before, e.g. self.steps[1][1]. Now, we can use self.configure_step directly. So I removed it.

2023-09-14 13:54 UTC, superstar54 commented on src/aiidalab_qe/app/result/report.py
> +    yield "pdos_computed", builder_parameters.get("run_pdos", None)
:+1: , i removed the `None`.

2023-09-14 13:56 UTC, superstar54 commented on tests/test_submit_qe_workchain.py
> +    #     assert parsed.find("initial_magnetic_moments").text == "None"
I find that there is nothing needs to be changed here, so I revert it.

2023-09-14 13:59 UTC, superstar54 commented
> @superstar54 Thanks! Just minor requests.

Hi @unkcpz  Thanks! I changed as you suggested.

2023-09-14 14:09 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +            protocol=parameters["protocol"],
yes, i changed it to `configuration_parameters`

2023-09-14 14:17 UTC, unkcpz approved these changes
All good! thanks!

2023-09-14 14:18 UTC, merged