add plugin page
aiidalab/aiidalab-qe pull request #463
Opened 2023-09-08 13:53 UTC by superstar54

2023-10-09 07:22 UTC, unkcpz requested changes

2023-10-09 07:22 UTC, unkcpz commented on docs/source/development/plugin.rst
> +        }
This is quite an essential specification of the workchain definition. If I understand correctly, the key name and the value type can not be changed.  So I would recommend to add a validator to the function who use this value and raise proper exception if the user passes an invalid dictionary.

2023-10-10 07:47 UTC, superstar54 commented on docs/source/development/plugin.rst
> +        }
Yes, I opened issue #503 for this.

2023-10-10 12:27 UTC, unkcpz requested changes
Thanks @superstar54.  Here is first go, I add some comments. I think there are more need to change can you first try to add a line break to every sentence so it is easy to review?

2023-10-10 12:27 UTC, unkcpz commented on docs/source/development/plugin.rst
> +    "result": Result,
```suggestion
        "outline": Outline,
        "setting": Setting,
        "workchain": workchain_and_builder,
        "result": Result,
```

2023-10-10 12:27 UTC, unkcpz commented on docs/source/development/plugin.rst
> +                )
This seems not properly indented as well.

2023-10-22 13:39 UTC, unkcpz requested changes
Thanks @superstar54, the reading experience is smooth. I have quite some nitpick changes please have a look. I'd ask @mikibonacci to have a look as well because he is the real user of this new feature.

Two points require discussion:
- Using the name "Hello world" or "Structure Render" for the demo plugin? 
- Using a gif to show the tabs displayed or two static figures?

I'd just wait for you two to vote and then Xing can start to change, no need to involve more people from the team I guess, better if @AndresOrtegaGuerrero also want to have a look and vote? 😄

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/architecture.rst
> +which is linked to the ``input_parameters`` ``trail`` of the next submit step.
```suggestion
The parameters from these panels are generated and stored as a dictionary, which is linked to the ``input_parameters`` trait of the next submit step widget.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/architecture.rst
> +Please take into account the following facts:
Is this a rule for developers or it is a thing to note?

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/architecture.rst
> +- the analysis of the results of the properties is also independent.
```suggestion
- the analysis of the results of the properties is independent.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/architecture.rst
> +The GUI of the PDOS plugin is only loaded when the user selects to run the PDOS property.
```suggestion
The GUI of the PDOS plugin is only loaded when the user selects it.

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/architecture.rst
> +.. figure:: ../_static/images/plugin_example.png
See my comment on this file, I think it maybe better to have two static figures to show before and after the property being selected?

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/architecture.rst
> +A QuantumESPRESSO app plugin will typically register new panels (setting, result), and workchain to extend the app's functionality.
```suggestion
A QuantumESPRESSO app plugin will register new corresponding panels (setting, result), and workchain to extend functionalities of the App.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/architecture.rst
> +So the developer can maintain their plugin as a separate folder in the QuantumESPRESSO app (even a separate package).
```suggestion
As a result, the developer can maintain their plugin in a separate folder in the QuantumESPRESSO app code base or even as a separate package.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/index.rst
> +This guide explains how to extend the functionality of the app.
```suggestion
This guide explains the architecture of the application and how to extend the functionality of the app by implementing the new feature as a plugin.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +Here is the simplest plugin to print the formula of the input structure:
```suggestion
Here is an example plugin to print the formula of the input structure:
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +A  :class:`~aiidalab_qe.common.panel.Outline` will add an item in the properties section of the workflow panel.
```suggestion
A  :class:`~aiidalab_qe.common.panel.Outline` is a panel widget that can add an item in the properties section of the workflow panel.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +For this example, we'll add the ``Hello World`` item, as shown below.
```suggestion
In this example, we add the ``Structure render`` item, as shown below.
```
If the example plugin has a specific functionality, I would expect the name to explain it. 
If you adopt this change, remember to update the figure as well.

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +The **Outline** will be shown as a checkbox.
```suggestion
The newly added **Outline** panel is a checkbox.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +        title = "Hello World"
```suggestion
        title = "Structure Render"
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +
```suggestion
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +
```suggestion
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +A  :class:`~aiidalab_qe.common.panel.Panel` will register a new panel in the configuration step, e.g. the ``Hello world`` panel.
A bit confusing to me. Does a panel register a new panel? Can you be more specific?

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +In this class, one can add widgets (e.g. Float, Int) to the GUI.
```suggestion
In this class, one can add widgets to the GUI.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +One needs to override the ``get_panel_value`` method to tell QuantumESPRESSO app how to use the values from the widgets.
```suggestion
One needs to override the ``get_panel_value`` method to tell the app how to use the values from the widgets.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +One also need to override the ``set_panel_value`` method to tell QuantumESPRESSO app how to reload the panel values from previous calculation, and the ``reset`` method to reset the panel to the defau
```suggestion
The developer is supposed to override the ``set_panel_value`` method to tell the app how to reload the panel values from the previous calculation, and the ``reset`` method to reset the panel to the default values.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +A  :class:`~aiidalab_qe.common.panel.ResultPanel` will register a new panel in the Results Step, e.g., the ``Hello world`` panel.
Same here, maybe "register" -> "render"

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +A  :class:`~aiidalab_qe.common.panel.ResultPanel` will register a new panel in the Results Step, e.g., the ``Hello world`` panel.
```suggestion
A  :class:`~aiidalab_qe.common.panel.ResultPanel` will render a new panel in the results step of the corresponding panel.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +In this class, one needs to specific the `workchain_labels` to tell QuantumESPRESSO app which workchain the panel is for.
```suggestion
In this class, the plugin developer needs to specify the `workchain_labels` to tell the app which workchain the panel associated.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +Then, one needs to implement the ``_update_view`` method to tell QuantumESPRESSO app how to show the results of the workchain.
```suggestion
Then, the ``_update_view`` method requires to be overridden to tell the app how to show the results of the workchain.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +        title = "Hello world"
In my opinion, "hello world" example is used very specifically for programming language, I guess even aiida plugin didn't use a "hello world" example. Here more specific name could be better. Please consider to change it.

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +**Bringing It All Together**, You can find all the code above in this github repository: https://github.com/superstar54/aiidalab-qe-hello-world
Please create a specific repo for it.

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +**Bringing It All Together**, You can find all the code above in this github repository: https://github.com/superstar54/aiidalab-qe-hello-world
```suggestion
**Bringing It All Together**, You can find all the code above in this github repository: https://github.com/aiidalab/aiidalab-qe-hello-world-demo
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +You can also use them as templates to create your own plugins.
```suggestion
You can also use them as a start point to create your own plugins.
```

2023-10-22 13:39 UTC, unkcpz commented on docs/source/development/plugin.rst
> +Your second plugin
I don't think naming it "second plugin" is good. The name should be more specific, maybe "A result plugin that can combine the results and render", with put under the section "Advanced usage".

```
Advanced usage
-----------------
```

2023-10-24 19:53 UTC, mikibonacci commented on docs/source/development/plugin.rst
> +        title = "Hello world"
should we use the "MultiplyAddWorkChain" from AiiDA tutorial? https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/tutorial.html . This is just a detail, but maybe we can make the very same example.

2023-10-24 19:57 UTC, mikibonacci commented on docs/source/_static/images/plugin_example.png
I will vote for Hello world (if we do not use MultiplyAdd instead) and for the gif, as it will be more dynamic and less tedious.

2023-11-03 09:00 UTC, AndresOrtegaGuerrero commented on docs/source/_static/images/plugin_example.png
Sorry for being late, I am pro Hello world since this is more a feature for developers, though i would be more incline to specify something like "Plugin: Custom Property" or "Plugin: Your New Feature" (or property) i think is more related to the idea that each plugin is linked to a new property

2023-11-03 09:13 UTC, superstar54 commented on docs/source/_static/images/plugin_outline.png
I removed this description line from the plugin.

2023-11-03 09:18 UTC, superstar54 commented on docs/source/development/architecture.rst
> +Quantum ESPRESSO app (QeApp) uses the Wizards UI, which divides one calculation into four steps. Each step may contain several sections (panels), as shown below.
I prefer to use the `Wizards UI` instead of the class name `WizardAppWidget`. Here we give the overview of the architecture instead of detailed code.

2023-11-03 09:34 UTC, superstar54 commented on docs/source/development/architecture.rst
> +In the configuration step, there are several panels.
:+1:

2023-11-03 09:40 UTC, superstar54 commented on docs/source/development/architecture.rst
> +Please take into account the following facts:
I changed it to ```This integration is made possible due to several key aspects:```

2023-11-03 09:45 UTC, superstar54 commented on docs/source/development/architecture.rst
> +A QuantumESPRESSO app plugin will typically register new panels (setting, result), and workchain to extend the app's functionality.
I prefer to keep `typically`, and not add `corresponding`.

2023-11-03 10:01 UTC, superstar54 commented on docs/source/development/plugin.rst
> +A  :class:`~aiidalab_qe.common.panel.Panel` will register a new panel in the configuration step, e.g. the ``Hello world`` panel.
I changed it to `A setting Panel widget will register a new panel in the configuration step`. 
In the feature, we may create a `SettingPanel` class for the setting.

2023-11-03 10:06 UTC, superstar54 commented on docs/source/development/plugin.rst
> +A  :class:`~aiidalab_qe.common.panel.ResultPanel` will register a new panel in the Results Step, e.g., the ``Hello world`` panel.
I prefer to use `register`.

2023-11-03 15:42 UTC, superstar54 commented on docs/source/development/plugin.rst
> +**Bringing It All Together**, You can find all the code above in this github repository: https://github.com/superstar54/aiidalab-qe-hello-world
I created one in `aiidalab`. https://github.com/aiidalab/aiidalab-qe-plugin-demos

2023-11-03 15:57 UTC, superstar54 commented
Hi @unkcpz @mikibonacci @AndresOrtegaGuerrero , thanks all for reviewing the PR and suggestions.

I replaced the ``hello_world`` plugin with a new example plugin: ``Equation of State (EOS)``. I think it is a good example because:
- it's simple and often used as an example for the first-principles calculation, e.g., in [ASE](https://wiki.fysik.dtu.dk/ase/tutorials/eos/eos.html), so many people know.
- it's also used as a [real-world example](https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/sections/writing_workflows/realworld.html) in AiiDA.
- it uses almost all the parameters from QeApp core, including the ``advanced`` settings; thus, it is a good example to tell developers how to use parameters from the GUI.

I also add examples of the latest features:
- structure importer and editor
- result panel for multiple plugins
- add new code 

Please give it another review.

2023-11-03 16:00 UTC, unkcpz commented on docs/source/_static/images/plugin_result.png
Super cool!

2023-11-06 10:44 UTC, AndresOrtegaGuerrero approved these changes
Nice work, LGTM!

2023-11-06 14:17 UTC, mikibonacci approved these changes
Thank a lot for the work Xing!

2023-11-07 14:19 UTC, unkcpz requested changes
Thanks a lot! Some tiny requests, ready to ship then. @superstar54

2023-11-07 14:19 UTC, unkcpz commented on docs/source/development/architecture.rst
> +QuantumESPRESSO app uses the [Wizards-like UI design](https://en.wikipedia.org/wiki/Wizard_(software)), which divides one calculation into four steps.
```suggestion
QuantumESPRESSO app uses the `Wizards-like UI design <https://en.wikipedia.org/wiki/Wizard_(software)>`_, which divides one calculation into four steps.
```

Here we use rst not markdown.

2023-11-07 14:19 UTC, unkcpz commented on docs/source/development/plugin.rst
> +    }
```suggestion
    eos ={
        "outline": EosOutline,
        "setting": Setting,
        "workchain": workchain_and_builder,
        "result": Result,
    }
```

2023-11-07 14:19 UTC, unkcpz commented on docs/source/development/plugin.rst
> +        },
```suggestion
    entry_points={
        "aiidalab_qe.properties": [
            "eos = aiidalab_qe_plugin_demos.eos:eos",
        ],
    },
```

2023-11-07 14:19 UTC, unkcpz commented on docs/source/development/plugin.rst
> +    }
```suggestion
    surface ={
        "importer": SurfaceImporter,
        "editor": SurfaceEditor,
    }
```

2023-11-07 14:19 UTC, unkcpz commented on docs/source/development/architecture.rst
> +The GUI of the PDOS plugin is only loaded when the user selects to run it.
```suggestion
The GUI of the PDOS plugin is only loaded when the user selects to run it, by ticking the checkbox in the workflow setting.
```

2023-11-07 14:22 UTC, unkcpz commented on docs/source/development/architecture.rst
> +The GUI of the PDOS plugin is only loaded when the user selects to run it.
Most are indentation fixes and a hyperlink fix. Please see if you think this is better phrased. In case you don't know, there is a tip in github that you can use `Commit suggestion` button above to quickly accept and submit the commit.

2023-11-08 08:10 UTC, superstar54 commented on docs/source/development/architecture.rst
> +The GUI of the PDOS plugin is only loaded when the user selects to run it.
I'd rather not add this `, by ticking the checkbox in the workflow setting.` . This is the introduction of the architecture, it's better not to go into the detail usage. 
I know the `commit suggestion`, thanks.

2023-11-08 08:25 UTC, unkcpz commented on docs/source/development/architecture.rst
> +The GUI of the PDOS plugin is only loaded when the user selects to run it.
Okay~

2023-11-08 08:26 UTC, unkcpz approved these changes
Looks all good to me. thanks and nice work! @superstar54

2023-11-08 08:53 UTC, merged