add test for workchain
aiidalab/aiidalab-qe pull request #472
Opened 2023-09-18 13:56 UTC by superstar54

This PR adds tests for the QeAppWorkChain, and also includes the plugins: `bands` and `pdos`.

The test generates the `projection` data and `bands` data, then mounts them to the QeAppWorkChain. The final result is then checked.

2023-09-19 11:16 UTC, unkcpz commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "miscellaneous/structures/Si.xyz")),
Try using `pathlib.Path`?

2023-09-19 11:16 UTC, unkcpz commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "miscellaneous/structures/Si.xyz")),
BTW, why is this change needed?

2023-09-20 22:04 UTC, unkcpz requested changes
@superstar54 thanks a lot! These are very useful tests. I only have minor requests good to me overall.

2023-09-20 22:04 UTC, unkcpz commented on tests/conftest.py
> +        projection_data = ProjectionData()
Here the datatype is not created from the data factory, please try to use the same way to create the data type.

2023-09-20 22:04 UTC, unkcpz commented on tests/conftest.py
> +            # list_of_projections=projections,
If it is not used, remove it.

2023-09-20 22:04 UTC, unkcpz commented on tests/conftest.py
> +        label="pw", executable="bash", entry_point="quantumespresso.pw"
The label is the full label, why the computer is removed?

2023-09-20 22:04 UTC, unkcpz commented on tests_notebooks/test_qe_app.py
> +        time.sleep(10)
Very useful! thanks!

2023-09-21 07:13 UTC, superstar54 commented on .github/workflows/ci.yml
> +                image: postgres:12
Yes, you are right. Postgres is not needed here.

2023-09-21 07:15 UTC, superstar54 commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "examples/Si.xyz")),
I don't know how this `/` works on a Windows machine. So I will use `os.path.join` here, which is safe for sure.

2023-09-21 07:15 UTC, superstar54 commented on tests/conftest.py
> +        ylabel = ylabel  # ["dos"]
I removed the comments and added a short description on the docstring.

2023-09-21 07:16 UTC, superstar54 commented on tests/conftest.py
> +        BandsData = DataFactory("core.array.bands")
Sure

2023-09-21 07:17 UTC, superstar54 commented on tests/conftest.py
> +        # projections = np.array([[1]])
Yes, I removed the lines.

2023-09-21 07:18 UTC, superstar54 commented on tests/conftest.py
> +            # list_of_projections=projections,
Yes, I removed it.

2023-09-21 07:19 UTC, superstar54 commented on tests/conftest.py
> +        label="pw", executable="bash", entry_point="quantumespresso.pw"
The label is the code label, not the full label.

2023-09-21 07:27 UTC, superstar54 commented on tests/conftest.py
> +        projection_data = ProjectionData()
Sure, I used the `DataFactory` for all.

2023-09-21 07:28 UTC, unkcpz commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "examples/Si.xyz")),
No, we never need to consider the windows, the AiiDAlab is supposed to run in a container, no matter whether we use aiidalab-launch or deployed somewhere else.

2023-09-21 07:31 UTC, unkcpz commented on tests/conftest.py
> +        label="pw", executable="bash", entry_point="quantumespresso.pw"
But why `pw@localhost` was worked before? It must be somewhere else you change the corresponding code to use the label, no?

2023-09-21 07:39 UTC, unkcpz commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "examples/Si.xyz")),
Meanwhile, the pathlib is also abstract for windows, it creates a path object that can easily convert to windows path later on. See https://docs.python.org/3/library/pathlib.html

2023-09-21 07:50 UTC, superstar54 commented on tests/conftest.py
> +        label="pw", executable="bash", entry_point="quantumespresso.pw"
It works even when you use `pw@localhost` as the label, but when you print out the code, it shows `pw@localhost@localhost`.

2023-09-21 07:56 UTC, unkcpz commented on tests/conftest.py
> +        label="pw", executable="bash", entry_point="quantumespresso.pw"
I see, thanks for the explanation.

2023-09-21 08:00 UTC, superstar54 commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "examples/Si.xyz")),
> the AiiDAlab is supposed to run in a container, no matter whether we use aiidalab-launch or deployed somewhere else.

Running in a container is a nice way, also the recommended way, to use AiiDAlab. However, since AiiDAlab is pure Python. The users can use it in a normal notebook. Especially after we define the aiidalab-qe app as an `App Class`, the user can easily import it and use it in a normal notebook as long as they have a aiida environment. 

>  the pathlib is also abstract for windows, it creates a path object that can easily convert to windows path later on. 

Unless we test it in Windows. Otherwise, and for the moment, I'd like to use `os.path`. Please open an issue to test it and update it if you prefer `pathlib` with `/`.

2023-09-21 08:48 UTC, unkcpz commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "examples/Si.xyz")),
As I said, using os.path is not windows support but pathlib will.

2023-09-21 08:50 UTC, unkcpz commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "examples/Si.xyz")),
> Unless we test it in Windows

To be honest, we will never do this. And I don't think we should mix using os.path and pathlib. You can change everything back to os.path, I am okay with that.

2023-09-21 09:08 UTC, superstar54 commented on src/aiidalab_qe/app/structure/__init__.py
> +    ("Silicon (diamond)", os.path.join(file_path, "examples/Si.xyz")),
Thanks! I searched for the difference. The `pathlib` is indeed a more modern method.  I changed it to use `pathlib` here.

2023-09-21 09:24 UTC, unkcpz approved these changes
Thanks for the work! @superstar54 
The chrome test failed with an error, I retrigger it and let's see if it is because of timeout.

2023-09-21 09:31 UTC, merged

2023-09-21 09:31 UTC, unkcpz commented
:clinking_glasses: