remove hard coded codes
aiidalab/aiidalab-qe pull request #474
Opened 2023-09-19 12:32 UTC by superstar54

The codes (`pw_code`, `dos_code`, `projwfc_code`) are hardcoded in the builder. This PR removes this.

2023-09-20 18:32 UTC, unkcpz requested changes
Thanks! Just minor requests. @superstar54

2023-09-20 18:32 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +        #
```suggestion

```

2023-09-20 18:32 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +        codes = {
```suggestion
        """Return the dict of code name as key and code node UUID as value"""
        codes = {
```

2023-09-20 18:32 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +            "projwfc_code": self.projwfc_code.value,
```suggestion
            "pw": self.pw_code.value,
            "dos": self.dos_code.value,
            "projwfc": self.projwfc_code.value,
```

2023-09-20 18:32 UTC, unkcpz commented on src/aiidalab_qe/workflows/__init__.py
> +            code=codes.get("pw_code"),
```suggestion
            code=codes.get("pw"),
```

2023-09-21 08:26 UTC, superstar54 commented
@unkcpz I changed as you suggested. Since we replaced the `pw_code` with `pw`, the `qeapp.yaml` and the workchains are also updated.

2023-09-21 19:19 UTC, unkcpz approved these changes
Thanks! Looks all good. 

I just merge https://github.com/aiidalab/aiidalab-qe/pull/449, and what to use it as a test. So I'll rebase this PR and see if from PR everything is built correctly. Hope you don't mind.

2023-09-21 19:19 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +                    code_widget = getattr(self, f"{code}_code")
Ah, I didn't notice this is directly used in `getattr`. Then the original code is good enough.

2023-09-21 19:58 UTC, unkcpz commented
Hi @superstar54, after rebasing the tests failed. But I compared the two branches and didn't find the difference. Do you have any clue why it is happening, can you check the changes are all correct?

2023-09-21 22:05 UTC, merged