Feature periodicity
aiidalab/aiidalab-qe pull request #479
Opened 2023-09-19 18:23 UTC by AndresOrtegaGuerrero

The current PR allows QE app to use 1D along x-axis and 2D -xy materials 
- [X] Updata aiidalab-widget-base to newer version to allow periodicity view
- [X] Modify AddTagEditor to StructureData to allow to change of periodicity of StructureData
- [X] Removing constraint of 3D systems only
- [X] Generation of kpoints for 1D and 2D points based on kpoints_distance 
- [X] Selection of 2D symmetry path in Settings

2023-09-20 06:04 UTC, superstar54 requested changes
@AndresOrtegaGuerrero Thanks for the PR. Two comments:
- periodicity belongs to the cell. I think moving it to the `Edit Cell` tab is better.
- The test coverage is down, but don't worry. I have a draft PR to test the plugin. So, for now, it's fine leave it

2023-09-20 06:34 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/setting.py
> +            "two_dim_kpoints_path": self.two_dim_kpoints_path.value,
@superstar54 Thank you i will do the modifications, the only thing about the tab, if i do that change it will mean to do a PR in aiidalab widgets base , and then it means to close this PR until that one is approved. What do you think ?

2023-09-20 07:41 UTC, unkcpz requested changes
This PR will fix https://github.com/aiidalab/aiidalab-qe/issues/211.

Thanks a lot for the nice work! I am looking forward to getting this new feature so we can get rid of the 2d dimension warning.

I have some minor requests, I think this is a feature that requires a clear description in UI, so that user will not get confused.

2023-09-20 07:41 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +                AddingTagsEditor(title="Edit StructureData"),
The `StructureData` is aiida specific and I'd suppose QeApp user don't understand it, so maybe call it "Edit site tags"?

2023-09-20 07:41 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +
Why this appear here? I guess it is from https://github.com/aiidalab/aiidalab-qe/pull/446 but that PR is now empty?

2023-09-20 07:41 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/setting.py
> +            description="Select 2D symmetry path:",
I remember there is a paper about how to select kpath for 2D: https://www.sciencedirect.com/science/article/pii/S0927025610002697?via%3Dihub

Is the method from this paper? Anyway, I think we should add a detailed description of what this path is about and how it is created. I'll be better an `ipw.HTML` widget for it dedicately.

2023-09-20 07:41 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/setting.py
> +        self.two_dim_kpoints_path = ipw.Dropdown(
```suggestion
        self.kpath_2d = ipw.Dropdown(
```
I guess this is better?

2023-09-20 07:41 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/workchain.py
> +def one_two_dim_kpoints_path(structure, kpoints_distance, two_dim_kpoints_path):
Why this is 1d or 2d but only gets `two_dim_kpoints_path` as input? Is that possible to have a function for 1D and function for 2d seperated?

2023-09-20 07:43 UTC, unkcpz commented
> The test coverage is down, but don't worry. I have a draft PR to test the plugin. So, for now, it's fine to leave it

@superstar54 If possible, please add a new commit to this PR, it is better to have implementation and test together.

2023-09-20 07:47 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/report.py
> +
This is because , since the kpoints for 1D and 2D are defined via kpoints instead of bands_kpoints_distance, so since that information wont be in the extras of the workchain, i can call it here to print in the report.

2023-09-20 07:49 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/setting.py
> +            description="Select 2D symmetry path:",
@unkcpz as a reference i defined the 5 symmetries , like here https://pubs.acs.org/doi/10.1021/acs.jpclett.2c02972 , i will add a description

2023-09-20 07:50 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/workchain.py
> +def one_two_dim_kpoints_path(structure, kpoints_distance, two_dim_kpoints_path):
yes i can split this into two functions, to make it clear , I will modify the code to have two independent functions

2023-09-20 09:33 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/main.py
> +                AddingTagsEditor(title="Edit StructureData"),
The issues is that i added the periodicity in this editor since a change in cell editor will require a PR to aiidalab-widget-base

2023-09-20 09:36 UTC, superstar54 commented on src/aiidalab_qe/plugins/bands/setting.py
> +            "two_dim_kpoints_path": self.two_dim_kpoints_path.value,
For me, it's OK to keep it here for the moment. Then, maybe you can add an issue to update it when it is added in aiidalab widget base.

2023-09-20 09:45 UTC, superstar54 commented
> @superstar54 If possible, please add a new commit to this PR, it is better to have implementation and test together.

I can do this. I need to first fix the problem in the draft PR #472.  @AndresOrtegaGuerrero Would you mind if I push some common this branch?

2023-09-20 09:48 UTC, AndresOrtegaGuerrero commented
> > @superstar54 If possible, please add a new commit to this PR, it is better to have implementation and test together.
> 
> I can do this. I need to first fix the problem in the draft PR #472. @AndresOrtegaGuerrero Would you mind if I push some commit to your PR?

Please go ahead, I already add the changes that @unkcpz  suggested. There is editor thing pending for discussion :D

2023-09-20 12:20 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +
Okay, then we can close #446?

2023-09-20 12:21 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +                AddingTagsEditor(title="Edit StructureData"),
No problem, I am fine with implement it here and open an issue on aiidalab-widgets-base. Please also add a comment here link to the issue you open so we remember to replace it in the future.

2023-09-20 13:02 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/workchain.py
> +    for branch in branches:
you meant using for `for branch in zip(*[iter(path)*2]:` ?

2023-09-20 13:07 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/workchain.py
> +    for branch in branches:
I tried it doesnt work

2023-09-20 13:20 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/workchain.py
> +    kpoints.labels = [[0, "\u0393"], [len(points) - 1, "X"]]
Will do!

2023-09-20 13:31 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/workchain.py
> +    list_kpoints = [item for sublist in points_branch for item in sublist]
@unkcpz  you mean like this 
`list_kpoints = []
for sublist in points_branch:
    for item in sublist:
        list_kpoints.append(item)`

because basically since points_branch is a list of list , the goal of the list comprehension is to concatanate into a single list , should i split it into two for loops or i put some comments to explain this step ?

2023-09-20 13:55 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/report.py
> +
No this issue is not related

2023-09-20 18:38 UTC, unkcpz commented
> is not related to https://github.com/aiidalab/aiidalab-qe/pull/446 , that one is for the nscf calculation

I see, sorry for the misunderstanding. I am curious why #446 has no code changes.

```
 PROTOCOL_BANDS_KPOINTS_MAP = {
    "fast": 0.1,
    "moderate": 0.025,
    "precise": 0.1,
}
```

Is this from aiida-quantumespresso protocol or it is defined by you? If it is from QE plugin, can you simply use the value from there, so in the future these values are synchronized with QE plugin?

2023-09-20 18:39 UTC, unkcpz commented on src/aiidalab_qe/common/widgets.py
> +        self.structure = deepcopy(new_structure)
Fair, thanks for the explanation! Let's keep deepcopy for safty.

2023-09-20 18:43 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/workchain.py
> +    for branch in branches:
I see, then what about:

```python
for branch in zip(path[:-1], path[1:]):
    print(branch)
```

I think this will do the trick and be easy to understand.

2023-09-20 18:46 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/workchain.py
> +    list_kpoints = [item for sublist in points_branch for item in sublist]
I see, this is flat a 2D list. Then the list comprehension is the best. Can you add a comment on it? Thanks!

2023-09-20 18:47 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +
Very sad, I got a thumbs down 😂

2023-09-20 19:34 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/report.py
> +
sorry!  hahah

2023-09-20 19:34 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/bands/workchain.py
> +    for branch in branches:
It did! thanks!

2023-09-20 22:23 UTC, unkcpz requested changes
Thanks for updating the PR, just some very small further changing requests.

2023-09-20 22:23 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +        ),
@superstar54 Can you check if, under the current design, the bands_kpoins_distance can be stored somewhere to restore the report back, rather than use a function?  

When I created this `_generate_report_dict` function, I planned that there would be only the final value to yield, the logic process needed to happen before the parameters passed in.

2023-09-20 22:23 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +    yield "periodicity", builder_parameters.get("periodicity", "xyz")
Similar here, the default value `"xyz"` should be set as default value in `builder_parameters`.

2023-09-20 22:23 UTC, unkcpz commented on src/aiidalab_qe/app/structure/__init__.py
> -from pymatgen.analysis.local_env import CrystalNN
I am very happy that we can potentially get rid of `pymatgen`.

2023-09-20 22:23 UTC, unkcpz commented on src/aiidalab_qe/common/widgets.py
> +from aiida.orm import Data as orm_Data
I'd use `from aiida import orm` and `orm.CalcJobNode` and `orm.Data`.

2023-09-20 22:23 UTC, unkcpz commented on src/aiidalab_qe/common/widgets.py
> +    structure_node = traitlets.Instance(orm_Data, allow_none=True, read_only=True)
```suggestion
    structure_node = traitlets.Instance(orm.StructureData, allow_none=True, read_only=True)
```
This is a structure data, no?

2023-09-20 22:23 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/setting.py
> +            If your system has periodicity xy. Please select one of the five 2D Bravais lattices corresponding to your system.
```suggestion
            If the structure is two-dimensional, please select 2-dimensional Bravais lattices corresponding to the structure.
```

2023-09-20 22:24 UTC, unkcpz commented on src/aiidalab_qe/app/result/report.py
> +        ),
But you can leave this one, and I'll have a quick discussion with @superstar54.
@AndresOrtegaGuerrero if you don't mind, I can directly add commits for this?

2023-09-20 22:27 UTC, unkcpz commented
> I update the PR i am waiting for Marnik for the review. 

Do you mean the bands kpoints distance protocol? @mbercx Can you have a look at it?

> I can do this. I need to first fix the problem in the draft PR https://github.com/aiidalab/aiidalab-qe/pull/472. @AndresOrtegaGuerrero Would you mind if I push some commit to your PR?

@superstar54, I give a go on #472, you can continue adding tests after that one is merged.

2023-09-21 06:30 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/report.py
> +        ),
Yes go ahead!

2023-09-21 06:30 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/report.py
> +    yield "periodicity", builder_parameters.get("periodicity", "xyz")
that or we use a function to get the pbc from the StructureData

2023-09-21 09:11 UTC, mbercx commented
> @mbercx Can you have a look at it?

I'm confused. It this PR blocked by https://github.com/aiidalab/aiidalab-qe/pull/446? I left some comments there as I remember. I'm not sure if we have reached a conclusion, but I think I was leaning towards the following:

If the user wants to override the SCF k-points distance, we shouldn't ad-hoc override the NSCF k-points distance according to a somewhat arbitrary approach. It seems better to me that there is also an override for the NSCF k-points distance in this case. 

But I suppose this should be discussed on https://github.com/aiidalab/aiidalab-qe/pull/446, not sure why I was tagged for this here. ^^

2023-09-21 09:36 UTC, unkcpz commented
If I understand correctly, in this PR it defines a new "protocol" for kpoints distance, I think @AndresOrtegaGuerrero want you to have a look? 

I was confused about #446 because there is no code change, as I mentioned many times. See the screeshot, that's why I think @AndresOrtegaGuerrero move implementations to this PR. Can you double check you push your changes? 

![image](https://github.com/aiidalab/aiidalab-qe/assets/8831685/98b5ebbd-2767-4080-8d90-c92c01f2c6a8)

Sorry if there is any misunderstanding. :pray:

2023-09-21 10:47 UTC, superstar54 commented
@AndresOrtegaGuerrero @unkcpz I added the test for 1d and 2d bands. Now the codecov +0.22%.

I also deleted the old `path` and `npoint`, which are used for illustration only.

2023-09-21 10:48 UTC, superstar54 commented on src/aiidalab_qe/app/result/report.py
> +    "precise": 0.1,
```suggestion
    "precise": 0.01,
```

2023-09-21 22:54 UTC, unkcpz commented
I removed the logic in the report part, instead, the complex logic all happened when generating the builder parameters in the submission step. Please have a look at https://github.com/aiidalab/aiidalab-qe/pull/479/commits/b76bd70e840e54f9bfc5c584547a43344f05174d for moving "periodicity" and https://github.com/aiidalab/aiidalab-qe/pull/479/commits/358cd1d9624d2f629b7210654e1214dd135ce04c for moving the `bands_kpoints_distance`. In this way, we don't need to reclaim the protocol mapping because `bands_kpoints_distance` is stored in the builder. Actually, part of the code was implemented by @superstar54 already but comment out. I think this more or less conflicts with plugin design and remember you said you'll have a further PR to fix it, can you give it a look? Thanks.

2023-09-22 07:29 UTC, superstar54 commented
> I removed the logic in the report part, instead, the complex logic all happened when generating the builder parameters in the submission step. Please have a look at [b76bd70](https://github.com/aiidalab/aiidalab-qe/commit/b76bd70e840e54f9bfc5c584547a43344f05174d) for moving "periodicity" and [358cd1d](https://github.com/aiidalab/aiidalab-qe/commit/358cd1d9624d2f629b7210654e1214dd135ce04c) for moving the `bands_kpoints_distance`. In this way, we don't need to reclaim the protocol mapping because `bands_kpoints_distance` is stored in the builder. Actually, part of the code was implemented by @superstar54 already but comment out. I think this more or less conflicts with plugin design and remember you said you'll have a further PR to fix it, can you give it a look? Thanks.

In  #481 , I refactor the report code, so that all the report-related parameters are handled in, and only in, the result step. and the `builder_parameters` is not needed anymore.

2023-09-22 08:04 UTC, unkcpz commented
So maybe we can merge this one first and then #481? I think this PR is all ready @AndresOrtegaGuerrero please have a look and we can merge.

2023-09-22 08:45 UTC, unkcpz approved these changes
I think this one is ready, and just had a quick chat with @superstar54 he is okay with all the changes.

2023-09-22 10:05 UTC, merged