adding HTML to visualise the kpoints mesh
aiidalab/aiidalab-qe pull request #480
Opened 2023-09-19 19:32 UTC by AndresOrtegaGuerrero

This PR adds a HTML displaying the mesh that is going to be use in the calculations based on the kpoints_distances used. This was one issue in #418

2023-09-19 19:51 UTC, unkcpz requested changes
Thanks! I have two minor requests. Since we have a mature test framework and get more experience on writing unit test for widgets can you add a test for this class and test the function added here.

2023-09-19 19:51 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +                mesh = self.create_kpoints_from_distance(
I don't think you need a modified version of this function. It is a calcification in QE plugin and aiida now support passing regular data type and aiida will convert to aiida datatype for you. So here you can import the function from QE plugin, only need to take care of the output to the correct datatype.

2023-09-19 19:51 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +        if self.input_structure is not None:
```suggestion
        if self.input_structure is None:
        return
```
Then the left part of code in this function has no need to be indented.

2023-09-20 06:35 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced.py
> +                mesh = self.create_kpoints_from_distance(
@unkcpz Thank you i will adapt the code and write the test

2023-09-20 08:57 UTC, AndresOrtegaGuerrero commented
@unkcpz  Do you have any suggestion on why the test is failing? , locally the advanced test is passing

2023-09-20 09:36 UTC, unkcpz commented
I think that is because you call calcfunction but you don’t have rabbitmq. Please try adding this section https://github.com/aiidalab/aiidalab-widgets-base/blob/2c29a9eac70e9f0773fd93165daccc14c304919b/.github/workflows/ci.yml#L113

2023-09-20 10:45 UTC, unkcpz requested changes
Just one minor request, all good then.

2023-09-20 10:45 UTC, unkcpz commented on tests/configuration/test_advanced.py
> +    structure = StructureData(
```suggestion
    structure = orm.StructureData(
```
We usually have this in other packages.

2023-09-20 11:53 UTC, AndresOrtegaGuerrero commented on tests/configuration/test_advanced.py
> +    structure = StructureData(
no problems i will call the StructureData via from aiida import orm,

2023-09-20 12:04 UTC, unkcpz approved these changes
Thanks! all great. @AndresOrtegaGuerrero

2023-09-20 12:06 UTC, merged