add code entry point
aiidalab/aiidalab-qe pull request #487
Opened 2023-09-23 07:08 UTC by superstar54

This is still a draft!

2023-10-19 14:29 UTC, mikibonacci commented
Thank Xing, this is super nice! 

I have few comments:
1 - do you think we can easily integrate some automatic code installation (if the specific version/instruction on how to do it is provided in the plugin setup specification)
2 - code-wise resource & parallelization widgets? maybe we can integrate ResourceSelectionWidget and ParallelizationSettings in the ComputationalResourcesWidget, so it is all related to the specific code? 

This may produce conflict if >1 plugins have the same codes, with different definitions. But maybe these will be very specific cases that we can solve ad hoc. 

what do you think? I can also work on comment 2. comment 1 is not so important I think, at least for now

2023-10-19 15:55 UTC, PNOGillespie commented
Just to add my perspective, having tested this system for developing a new plugin, the process to do so is now a lot easier in terms of what one has to do in order to incorporate a new plugin into the rest of the App - so, very nicely done.

No other comments really, I think it just needs some brief documentation for developers to be added at a later date - essentially just to clarify how to add a new plugin to the App.

2023-10-20 07:31 UTC, superstar54 commented
@mikibonacci @PNOGillespie Thanks for the test.

> do you think we can easily integrate some automatic code installation (if the specific version/instruction on how to do it is provided in the plugin setup specification)

This is code dependent. For code that can be installed using `conda/pip`, it's easy to integrate the automatic code installation. Please check the `setup_codes.py` file.

> code-wise resource & parallelization widgets? maybe we can integrate ResourceSelectionWidget and ParallelizationSettings in the ComputationalResourcesWidget, so it is all related to the specific code?
> I can also work on comment 2. comment 1 is not so important I think, at least for now

We had such a discussion before, about adding different resources for `pw`, `dos`, etc. You can mention this in the AiiDAlab meeting, and good if you have time to work out a prototype. 


> I think it just needs some brief documentation for developers to be added at a later date

Yes, a clear doc will be added.

2023-10-20 09:57 UTC, unkcpz requested changes
Some minor requests.

2023-10-20 09:57 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +        # s
```suggestion
```

2023-10-20 09:57 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +        # disable all codes except pw
Instead of disable, maybe we hide? set visible -> "none"? But this is a layout-related comment, I don't want to block the PR with it. Please ignore if you don't agree.

2023-10-20 09:57 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +                continue
I know the `pw` is essential code should always be there. So why not separated it as a new widget and only leave the entry point implementation for plug-in codes?

2023-10-20 09:57 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +        for identifer, codes in self.code_entries.items():
```suggestion
        # Update the layout of code widgets
        for identifer, codes in self.code_entries.items():
```
Another nitpick, possible to simplify this for..if..for ?

2023-10-20 09:57 UTC, unkcpz commented on src/aiidalab_qe/plugins/pdos/workchain.py
> +        not any(
Cool, much clear that this check is moved to here for pdos only.

2023-10-20 10:58 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +                continue
It is convenient to manipulate the code widgets, e.g. `set` and `get` the code widget values, if all widgets are stored together, and treated equally.

2023-10-20 11:12 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +        for identifer, codes in self.code_entries.items():
I removed the `if`.

2023-10-20 11:13 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +        # disable all codes except pw
Good idea. I used the visibility.

2023-10-20 11:49 UTC, unkcpz approved these changes
Thanks @superstar54. All good to me. Ready to :ship:

2023-10-20 12:10 UTC, merged