Feature/kill button
aiidalab/aiidalab-qe pull request #500
Opened 2023-10-09 10:20 UTC by mikibonacci

adding the kill button to support live-killing of a workchain, just selecting it from the list and clicking on the button.

2023-10-09 10:34 UTC, unkcpz requested changes
Thanks @mikibonacci. Just two small comments.

2023-10-09 10:34 UTC, unkcpz commented on src/aiidalab_qe/common/process.py
> +        if isinstance(self.work_chains_selector.value, int):
I guess this condition is to avoid click when no workchain is selected ("No process")?  If so, maybe it is more proper to disable the kill button so user can not click on it.

2023-10-09 10:34 UTC, unkcpz commented on src/aiidalab_qe/common/process.py
> +            control.kill_processes(processes)
```suggestion
            message = 'Killed through `AiiDAlab app interface`'
            control.kill_processes(processes, message=message)
```

2023-10-09 10:38 UTC, unkcpz commented
> adding the kill button to support live-killing of a workchain, just selecting it from the list and clicking on the button.

I think for this button, it should be only enabled only when the workchain is in "running" state, so the state of the button should be update when the new process is selected from the workchain selector list.

2023-10-09 12:09 UTC, danielhollas commented
Cool, I might steal this, wanted to have this feature for a while :-) Hower, my plan was to implement the button next somewhere next to the NodeTree widget of a running process. It seems a bit out of place in the Workchain selector, I would worry about accidentally clicking it. WDYT?

2023-10-09 12:39 UTC, unkcpz commented
> It seems a bit out of place in the Workchain selector, I would worry about accidentally clicking it. WDYT?

@danielhollas thanks a lot for chime in. It is a great point. My plan was to bring in this concept to the QeApp and we think about the layout afterward. 
For the misclick, I won't worry about it too much, the `window-close` icon contains the cross, so I suppose the user will notice it will cause some fatal consequence (although we can not predict too much but how fatal it can be?).  You idea of put it in the node tree is great, but I am afraid it is straightforward to implement especially when we have some issues concerned about improve the nodetree in general.

2023-10-09 12:43 UTC, danielhollas commented
Just to clarify, I did not mean to implement it directly in the Node tree widget, just as a simple standalone button somewhere next to it. You also highlight an important point, having just an icon without any explanation is very cryptic, whereas an big red scary "Kill workflow" button would be more obvious.

2023-10-09 13:57 UTC, mikibonacci commented
Dear @danielhollas  thank you for your feedback! indeed, I think that the button should be somewhere near the workchain tree. Maybe for this release we can still have the button near the other two (new and refresh), and then in the future put it in a more reasonable place?

2023-10-10 09:05 UTC, unkcpz requested changes
One more minor thing to change, others are all good to me.

2023-10-10 09:05 UTC, unkcpz commented on src/aiidalab_qe/common/process.py
> +        )
Instead of using `dlink`, I think it is more proper to set the disable of the button in the callback function `_observe_value`. Because:
1. the `dlink` is a bit complex with the transform from uuid to the running status, which will be clear if it is a regular code block in the function.
2. In the `refresh_work_chain` method, the disable of the button is check and set, this has the same logic as `dlink` here and the refresh should trigger the callback (it is already the case I assume, if not we need to fix it).

2023-10-10 09:12 UTC, unkcpz commented
> Just to clarify, I did not mean to implement it directly in the Node tree widget, just as a simple standalone button somewhere next to it.

I see, sorry for misunderstanding it. I guess you mean add it here, https://github.com/aiidalab/aiidalab-qe/blob/967c3f8d5a4347b69e9b2a0093e94be6bef26695/src/aiidalab_qe/app/result/__init__.py#L25-L30

I can see the advantage of putting the button here, but I also thing having the kill button with "new", "refresh" is compatible with its usage. Let's discuss this in the meeting and see what others think.

2023-10-16 09:23 UTC, unkcpz commented
Hi @mikibonacci, as we discussed during the meeting, we agree on that this button better to be placed above the node tree. Can you move it to there, thanks.

2023-10-19 16:25 UTC, unkcpz approved these changes
We had an offline pair coding and tidying up a bit on the implementation. All good from me. Thanks a lot! @mikibonacci

2023-10-19 16:29 UTC, merged

2023-10-19 16:43 UTC, danielhollas commented
Nice, can you post a screenshot of the final product? When thinking about
this, I couldn't figure out where is the best place to put it.

Dne čt 19. 10. 2023 17:29 uživatel Jusong Yu ***@***.***>
napsal:

> Merged #500 <https://github.com/aiidalab/aiidalab-qe/pull/500> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/aiidalab/aiidalab-qe/pull/500#event-10714501979>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACIY64OED5IBHMYLAIWUHLLYAFIN3AVCNFSM6AAAAAA5YR6TOOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJQG4YTINJQGE4TOOI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>