check if code is none
aiidalab/aiidalab-qe pull request #505
Opened 2023-10-13 19:20 UTC by superstar54

2023-10-16 15:40 UTC, unkcpz requested changes
Thanks @superstar54, I guess the issue only happens if there are other code, e.g xps involved in the calculation, correct? 
The change looks all good for me, can you add a unit test to it?

2023-10-17 11:32 UTC, superstar54 commented
> I guess the issue only happens if there are other code, e.g xps involved in the calculation, correct?

For all codes. e.g if not calculate `pdos`, and codes `dos` is not selected. The `dos` code is passed as `None` to the builder.

2023-10-17 11:32 UTC, superstar54 commented
> The change looks all good for me, can you add a unit test to it?

Thanks for the suggestion. I have added the test.

2023-10-18 00:35 UTC, unkcpz commented on tests/test_submit_qe_workchain.py
> +    app.submit_step._create_builder()
Thanks for adding the test. But I didn’t see what you were testing for. Maybe add an assert statement, what is the value of dos code in the builder? 
I also don’t understand why dos code will be None, the drop-down widget only has its value equal to None right after initialization but we already have localhost code for it as default. 

But I agree the change is needed for the case such as xps code.

2023-10-18 10:41 UTC, PNOGillespie commented on tests/test_submit_qe_workchain.py
> +    app.submit_step._create_builder()
> I also don’t understand why dos code will be None, the drop-down widget only has its value equal to None right after initialization but we already have localhost code for it as default.

If I may add something here (as the person that found this bug originally): I confirm that Xing's fix does work, though I agree that the nature of the issue is strange. From my own testing:
* Running Bands or Xps alone without dos or pdos set returns the error: `ValueError: one of the parameters 'identifier', pk', 'uuid' or 'label' has to be specified`. You can actually request a Pdos calculation in step 2, set the dos.x and projwfc.x codes in step 3, then un-tick the Pdos calculation in step 2 to avoid the error without running Pdos.
* Removing the line `codes = {key: orm.load_node(value) for key, value in codes.items()}` and just passing `codes` without converting the inputs (i.e. `codes = parameters["codes"]`) works without issues for Bands and Xps, but causes a different crash for Pdos. Unfortunately, I can't find the traceback for that one right now, but it seemed to be that the values for dos and pdos codes were in the form of their UUID, rather than a node like for pw.x.

Hope this helps a little in diagnosing the problem.

2023-10-18 11:54 UTC, unkcpz commented on tests/test_submit_qe_workchain.py
> +    app.submit_step._create_builder()
Thanks a lot for the details @PNOGillespie very helpful.

> but it seemed to be that the values for dos and pdos codes were in the form of their UUID, rather than a node like for pw.x.

I have a feeling this could be related to the source of issue. The change look all good and I should not block the PR. approved.

2023-10-18 11:54 UTC, unkcpz approved these changes

2023-10-18 13:18 UTC, merged