Fix tot magnetization
aiidalab/aiidalab-qe pull request #512
Opened 2023-10-17 14:20 UTC by AndresOrtegaGuerrero

This PR solves #412

2023-10-17 14:22 UTC, AndresOrtegaGuerrero commented
@unkcpz  This is a draft, but in order for me to continue there must be a PR (in aiida-quantumespresso) to deal with the logic that if the system has` tot_magnetization` , it should remove `starting_magnetization `for PwBaseWorkChain. Likewise that the logic in PdosWorkChain and BandsWorkchain is not affected

2023-11-07 15:32 UTC, unkcpz requested changes
Thanks a lot for trying this @AndresOrtegaGuerrero, The logic looks all good, but I think it requires some iron-up on the clarity of implementation. Can you fix the conflicting and we arrange a pair coding session to check things together?

2023-11-07 15:32 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +        self.magnetization.electronic_type = change["new"]
I like this, very clear to me and I saw you made `electronic_type` a trait of `MagnetizationSettings`, exactly what I think about ;)

2023-11-07 15:32 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +
Can you write a comment here for all conditions? 
For instance:

```
# insulator and colliner: xxxx
# metal and collinear: xxx
```

Can the if..else clause below can be simplified with inverse and break return?

2023-11-07 15:32 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +                self.pseudo_setter._reset()
Why can not call pseudo_setter.structure = None if input_structure is not `None`? If I understand correct, the reset should also do `self.structure=None` first.

2023-11-07 15:32 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +        self.tot_magnetization.value = 0.0
I'd suggest making the default value defined as class attribute `_DEFAULT_TOT_MAGNETIZATION`.

2023-11-07 15:32 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +                "<b>Magnetization: Input structure not confirmed</b>"
This also appears in the `__init__`, which should be a way to only define it once in a single place.

2023-11-07 15:32 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/advanced.py
> +    def _display_starting(self, value):
```suggestion
    def _render(self, value):
```

2023-11-07 15:32 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/workchain.py
> +        bands.bands["pw"]["parameters"]["SYSTEM"].pop("starting_magnetization", None)
If I understand correctly, the code here is for when `tot_magnetization` is set, the `starting_magnetization` should not be set, but this exclusive existence can be guaranteed when the builder is created, no?

2023-11-29 11:58 UTC, AndresOrtegaGuerrero commented
To complete this PR the following requirements should be met

- [ ] PdosWorkChain should be adapted to run calculations using tot_magnetization https://github.com/aiidateam/aiida-quantumespresso/issues/988
- [ ] the logic of the qe app should be adapted for having two fermi energies (up/down): get_pdos_data, projections, bands-widget

2024-04-03 16:01 UTC, superstar54 approved these changes
@AndresOrtegaGuerrero , thanks for the work!  LGTM!

There are two things we could improve:
- If users set `Magnetism` to `Off`, the Magnetization section could be hidden.
- When switching on `Magnetism`, the pdos plot could has an optios to plot `up` and `down` in two sides.
Could you create issues on this? so that we can do these in the future PRs.

2024-04-03 16:10 UTC, superstar54 commented
Before merging the PR, two small changes are needed:

- the `tot_magnetization` should be an integer for a `fixed` occupation.
- There are two `tot_magnetization` when I load the previous job.
![image](https://github.com/aiidalab/aiidalab-qe/assets/11457659/ea52be08-64b6-4132-8a7c-89e7569fa61b)

2024-04-03 16:44 UTC, AndresOrtegaGuerrero commented
@superstar54 thank you for the review, I thought i fixed the duplication i will have a look. Regarding the tot_magnetization , i kept as a Real number since in the pw.x manual is a real.

2024-04-03 17:22 UTC, superstar54 commented
In the fixed occupation, if one sets a non-integer value for the `tot_magnetization,` pw will raise an error. In the smearing case, it will not.

2024-04-03 19:44 UTC, AndresOrtegaGuerrero commented
> In the fixed occupation, if one sets a non-integer value for the `tot_magnetization,` pw will raise an error. In the smearing case, it will not.

Then i guess it should be conditioned then , thank you !

2024-04-05 12:43 UTC, merged