Add plugin: XPS
aiidalab/aiidalab-qe pull request #518
Opened 2023-10-20 12:14 UTC by superstar54

This is still a draft.

2024-01-30 13:34 UTC, superstar54 commented
It seems that the plugins still use the default pseudo family from pw workchain.
```
ValueError: required pseudo family `SSSP/1.2/PBEsol/efficiency` is not installed. Please use `aiida-pseudo install` toinstall it.
```

2024-02-01 15:33 UTC, PNOGillespie requested changes
Hi @superstar54, I've had a look at the code and, generally speaking, it looks good. I've left some suggested changes here and there to improve readability and clean up commented-out blocks of code.

The only important change IMO is a selection widget for the element to display in the `Result` panel - see the [relevant comment](https://github.com/aiidalab/aiidalab-qe/pull/518#discussion_r1474614565) for discussion.

2024-02-01 15:33 UTC, PNOGillespie commented on src/aiidalab_qe/plugins/xps/setting.py
> +        <h4>Pseudopotential</h4></div>"""
Just to make things easier to read:
```suggestion
        <h4>Core-Hole pseudopotential group</h4></div>"""
```

2024-02-01 15:33 UTC, PNOGillespie commented on src/aiidalab_qe/plugins/xps/setting.py
> +    )
Would something like this make sense for readability? "Core-Hole" or "Core-Level" seems like it would be more intuitive, but if "Peak" is the correct technical term in this case then don't worry.
```suggestion
    peak_title = ipw.HTML(
        """<div style="padding-top: 0px; padding-bottom: 0px">
        <h4>Select core-level</h4></div>"""
    )
    peak_help = ipw.HTML(
        """<div style="line-height: 140%; padding-top: 6px; padding-bottom: 0px">
        The list of core-levels to be considered for analysis.
        </div>"""
    )
```

2024-02-01 15:33 UTC, PNOGillespie commented on src/aiidalab_qe/plugins/xps/setting.py
> +            # ),
There are quite a few commented-out sections here which should be cleaned up if possible:
```suggestion
            self.pseudo_title,
            self.pseudo_help,
            self.pseudo_group,
            self.peak_title,
            self.peak_help,
            ipw.HBox(
                [self.peak_list],
            ),
```

Does this also mean (based on the fact that `supercell_min_parameter` is not used) that the supercell size used in calculation is defined entirely by the protocol?

2024-02-14 11:50 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/setting.py
> +    )
Thanks! I change it to core-level

2024-02-14 11:54 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/result.py
> +                g.add_scatter(x=d[0], y=d[1], fill="tozeroy", name=f"{element}_{site}")
Thanks! I added the selection dropdown for different elements, like in the XAS plugin.

2024-02-14 11:55 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/result.py
> +        )
I added a description for the parameters and also a link to Wikipedia.

2024-02-14 11:55 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/setting.py
> +        <h4>Pseudopotential</h4></div>"""
I changed as you suggested.

2024-02-14 11:58 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/setting.py
> +            # ),
Yes. This would be more user friendly

2024-02-14 12:07 UTC, superstar54 commented
@PNOGillespie Thanks for your review. I made the changes as you suggested. I added the dropdown button to select the spectrum for different elements. I also added a table to show the offset energies, which are used to calibrate the calculated binding energy.

2024-02-14 15:55 UTC, PNOGillespie requested changes
Hi @superstar54. Code looks good for the most part. I've added a few final changes, after which I think this PR is complete.

2024-02-14 15:55 UTC, PNOGillespie commented on src/aiidalab_qe/plugins/xps/result.py
> +        )
I didn't know that Python strings could use non-ASCII characters :laughing:. While these don't raise an error at the moment, I'd suggest encoding these properly just to avoid any potential problems elsewhere:
```suggestion
        gamma = ipw.FloatSlider(
            value=0.3,
            min=0.1,
            max=1,
            description="Lorentzian profile ($\gamma$)",
            disabled=False,
            style={"description_width": "initial"},
        )
        sigma = ipw.FloatSlider(
            value=0.3,
            min=0.1,
            max=1,
            description="Gaussian profile ($\sigma$)",
            disabled=False,
            style={"description_width": "initial"},
        )
```

2024-02-14 15:55 UTC, PNOGillespie commented on src/aiidalab_qe/plugins/xps/result.py
> +                        )
This section here causes a crash because you're calling the value from the UI element rather than converting it to a type of fill method (e.g. "tozeroy"):
```suggestion
                        if fill.value:
                            fill_type = "tozeroy"
                        else:
                            fill_type = None
                        g.add_scatter(
                            x=d["x"], y=d["y"], fill=fill_type, name=d["site"]
                        )
```

2024-02-14 15:55 UTC, PNOGillespie commented on src/aiidalab_qe/plugins/xps/result.py
> +        )
The first sentence should remind the user how the correction energies are used in practice:
```suggestion
        correction_energies_table = ipw.HTML(
            """<h4>Offset Energies (δ)</h4>
            <div>When comparing binding energies reported by AiiDALab-QE to experimental data, these should be corrected by the given offset listed below</div>
            <table><tr><th>Core-level</th><th>Value (eV)</th></tr>"""
        )
```

I would also recommend moving the second sentence (or maybe the relevant concept or description) to the documentation since this is not really needed here.

2024-02-14 15:55 UTC, PNOGillespie commented on src/aiidalab_qe/plugins/xps/result.py
> +        return correction_energies_table
Just a little addition to make things clearer:
```suggestion
        for core_level, value in correction_energies.items():
            element = core_level.split("_")[0]
            if element not in self.spectrum_select_options:
                continue
            exp = value["exp"]
            if exp >= 0.0:
                sign = "+"
            elif exp < 0:
                sign = ""
            correction_energies_table.value += (
                f"<tr><td>{core_level}</td><td>{sign}{exp}</td></tr>"
            )
        return correction_energies_table
```

If the values can be positive or negative, then it's usually a good idea to give the sign explicitly even if the number is positive.

The string for the core level name should probably also have the underscore removed, since this doesn't format so well in non-monospace text. I understand this is also the way that the labels for the core levels are written in the `Setting` panel, but I wouldn't worry about changing those at this stage.

2024-02-14 16:29 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/result.py
> +                        )
thanks! I changed it.

2024-02-14 16:34 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/result.py
> +        return correction_energies_table
thanks! The sign is indeed very important.

2024-02-14 17:32 UTC, superstar54 commented on src/aiidalab_qe/plugins/xps/result.py
> +        )
thanks! I made the changes.

2024-02-14 17:47 UTC, superstar54 commented
@PNOGillespie, thanks for your review and very useful suggestions! I made all the changes as suggested.

2024-02-14 21:06 UTC, PNOGillespie approved these changes
Looks good to me, nice work @superstar54!

2024-02-15 07:35 UTC, merged