add `electronic_structure` plugin
aiidalab/aiidalab-qe pull request #522
Opened 2023-10-21 06:19 UTC by superstar54

This PR supports showing the result from multiple plugins.

2023-10-23 11:17 UTC, unkcpz requested changes
Thanks @superstar54, I have two things ask to change, please have a look.

2023-10-23 11:17 UTC, unkcpz commented on tests/test_result.py
> -        == wcv.result_tabs.children[2].children[0].children[0].children[0].value
I have no idea of all these children are, a detailed comment will be very useful.
Since now things are implemented as "Panel", is some of these children are panel? If so, I think `Panel` can have some way to associate children with name to make it easy to access.

2023-10-23 11:17 UTC, unkcpz commented on src/aiidalab_qe/plugins/electronic_structure/result.py
> +        )
Please avoid a deep nest of widgets, if there are many, define it outside with a comment on what the box is for and where it is displayed.

2023-10-23 11:18 UTC, unkcpz commented
BTW, there is no need to always merge the branch, if I find time to review I'll merge the main before I review. Usually, this happens before the final merge if there is no conflict.

2023-10-27 13:04 UTC, superstar54 commented on tests/test_result.py
> -        == wcv.result_tabs.children[2].children[0].children[0].children[0].value
The test here is too detailed, and not necessary, so I removed it. A new test that checks the length of the panel children is added.

2023-10-27 13:05 UTC, superstar54 commented on src/aiidalab_qe/plugins/electronic_structure/result.py
> +        )
I refactored the code. Now, it's become more simple and clear.

2023-10-27 13:25 UTC, superstar54 commented
@unkcpz I refactored the code and added detailed comments. It's ready for review. 

Please focus on the plugin part, which is the primary purpose of this PR.

The part of plotting the electronic structure is simply copied and pasted from the previous code, with few updates. If the code needs polished, it is better to open another PR.

2023-10-27 15:25 UTC, unkcpz requested changes
Hi @superstar54, thanks a lot for refactoring, very beautiful! Just some minor questions.

2023-10-27 15:25 UTC, unkcpz commented on src/aiidalab_qe/app/result/workchain_viewer.py
> +                    if False not in results_ready:
```suggestion
                    if all(results_ready):
```

2023-10-27 15:25 UTC, unkcpz commented on src/aiidalab_qe/app/result/workchain_viewer.py
> +                            len(self.result_tabs.children) - 1, result.title
I guess `len(self.result_tabs.children) - 1` is the idx of the tab. Please have a variable for it with comment.

2023-10-27 15:25 UTC, unkcpz commented on src/aiidalab_qe/plugins/bands/result.py
> +    workchain_labels = ["bands"]
What is this labels for? If there are more than one where will those shown?

2023-10-27 15:25 UTC, unkcpz commented on tests/test_result.py
> -        == wcv.result_tabs.children[2].children[0].children[0].children[0].value
Nice, that is better!

2023-10-27 15:25 UTC, unkcpz commented on tests/test_plugins_electronic_structure.py
> +        if getattr(tab, "identifier", "") == "electronic_structure"
I assume `identifier` is a mendatory attribute of panel, so get this be: 
```suggestion
        if tab.identifier == "electronic_structure"
```

2023-10-27 19:04 UTC, superstar54 commented on src/aiidalab_qe/plugins/bands/result.py
> +    workchain_labels = ["bands"]
One can use the workchain_labels to specify which plugins (outputs) are needed for this result panel. For example, the electronic_structure result panel needs pdos and bands.
 ```
 workchain_labels = ["bands", "pdos"]
 ```
To make this clear, I added a comment in the `ResultPanel`.

2023-10-27 19:05 UTC, superstar54 commented
@unkcpz  I updated the code based on your suggestions. It's ready for another review.

2023-10-29 00:05 UTC, unkcpz approved these changes
Thanks @superstar54 ! All good for me. Ready to 🚢

2023-10-29 06:05 UTC, merged