Pining the lowest version of aiida-pseudo
aiidalab/aiidalab-qe pull request #524
Opened 2023-10-21 16:17 UTC by unkcpz

2023-10-21 16:18 UTC, unkcpz commented
Slightly blocked by #523 where the modules are restructured.

2023-10-23 21:59 UTC, unkcpz commented
Blocked by https://github.com/aiidateam/aiida-pseudo/issues/165

2023-10-25 12:58 UTC, unkcpz commented on src/aiidalab_qe/common/setup_pseudos.py
> +    print(p.stderr.decode())
```suggestion
    run(cmd, env=env, cwd=cwd, capture_output=True, check=True)
```

2023-10-25 12:58 UTC, unkcpz commented on src/aiidalab_qe/common/setup_pseudos.py
> +        print(cmd)
```suggestion
```

2023-10-25 12:58 UTC, unkcpz commented on src/aiidalab_qe/workflows/__init__.py
> +        print(parameters["advanced"]["pw"])
```suggestion
```

2023-10-27 20:29 UTC, superstar54 requested changes
Great job on working on this feature. It will improve the user experience. I added a few change requests.

2023-10-27 20:29 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/pseudos.py
> +                f"PseudoDojo/{PSEUDODOJO_VERSION}/{functional}/SR/{accuracy}/upf"
Becareful here. The `setup_pseudos` in the `common` folder is something we want to move to the `aiidalab-widgets-base`, so it's better not to import the `PSEUDODOJO_VERSION` from the `setup_pseudos`. The pseudo version is a local configuration parameter belonging to the app itself.

2023-10-27 20:29 UTC, superstar54 commented on src/aiidalab_qe/common/setup_pseudos.py
> +            cmd.extend(["--from-download", file_path])
this part can be moved into the `_construct_cmd` function, so that the code is more clear.

2023-10-27 20:29 UTC, superstar54 commented on tests/test_codes.py
> +@pytest.mark.usefixtures("sssp")
there is one blocker here: ['The SSSP library is not installed.'], can you fix it?

2023-10-27 20:29 UTC, superstar54 commented on tests/test_pseudo.py
> +    [_ for _ in _install_pseudos(EXPECTED_PSEUDOS)]
```suggestion
    _install_pseudos(EXPECTED_PSEUDOS)
```
Same for others.

2023-10-28 23:28 UTC, unkcpz commented on docker/Dockerfile
>       # It is important to install from `aiidalab install` to mimic the same installation operation from the app store.
The change is made in https://github.com/aiidalab/aiidalab-qe/pull/532

2023-10-28 23:29 UTC, unkcpz commented on docker/Dockerfile
>       # It is important to install from `aiidalab install` to mimic the same installation operation from the app store.
It is important because from the app store `aiidalab install` is the actual operation.

2023-10-28 23:29 UTC, unkcpz commented on docker/Dockerfile
> +     # Because we only need the dependencies to be installed.
It was installed from `pip install`, but it does not go through the actual `aiidalab install`.

2023-10-28 23:30 UTC, unkcpz commented on docker/before-notebook.d/71_install-qeapp.sh
>  if aiida-pseudo list | grep -q "no pseudo potential families"; then
Good catch, I forgot to check it.

2023-11-02 14:52 UTC, unkcpz commented on src/aiidalab_qe/common/setup_pseudos.py
> +            cmd.extend(["--from-download", file_path])
I move it to `_construct_cmd`. There is pros and cons but I think move it to `_construct_cmd` is better, please have a look.

2023-11-07 09:17 UTC, superstar54 requested changes
A few small changes are needed.

2023-11-07 09:17 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/pseudos.py
> +                f"PseudoDojo/{PSEUDODOJO_VERSION}/{functional}/SR/{accuracy}/upf"
Since you already move it outside the app folder, please define the version in the `qeapp.yaml`.

2023-11-07 10:08 UTC, unkcpz commented on src/aiidalab_qe/__main__.py
> +@click.option("-p", "--profile", default="default", help="AiiDA profile name.")
Sure!

2023-11-07 10:11 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/pseudos.py
> +                f"PseudoDojo/{PSEUDODOJO_VERSION}/{functional}/SR/{accuracy}/upf"
I am not sure it is doable, the `SSSP_VERSION` is defined in `common/setup_pseudos.py` which is not in the `app` module in order to avoid loading profile when calling `aiidalab-qe install`. The `qeapp.yaml` is in the `app` module instead.

2023-11-07 10:13 UTC, unkcpz commented on docker/Dockerfile
> +     # Because we only need the dependencies to be installed.
Sure, I'll update the comment.

It is needed since `aiidalab install` will use `setup.py` and parse requirements list from it, and it is exactly what happened in appstore installation.

2023-11-07 10:20 UTC, unkcpz commented on docker/Dockerfile
> +     # (for `aiidalab/aiidalab<23.03.2` the `setup.py` should be in the root folder of the app https://github.com/aiidalab/aiidalab/pull/382).
Hope this is clear?

2023-11-08 08:50 UTC, superstar54 requested changes

2023-11-08 08:50 UTC, superstar54 commented on docker/Dockerfile
> +     # (for `aiidalab/aiidalab<23.03.2` the `setup.py` should be in the root folder of the app https://github.com/aiidalab/aiidalab/pull/382).
What will happen if I git clone the repo and install it using pip?

2023-11-08 08:50 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/pseudos.py
> +                f"PseudoDojo/{PSEUDODOJO_VERSION}/{functional}/SR/{accuracy}/upf"
> in order to avoid loading profile when calling aiidalab-qe install

You mean `aiidalab-qe install_pseudos`. I checked this function, it needs load the profile at the beginning. 

The problem here is: we want to make the `setup_pseudos.py` as a common function, but it doesn't allow users to customize the pseudos.
I would suggest passing the pseudo info into the `install` method in the `setup_pseudos.py`.

2023-11-08 09:30 UTC, unkcpz commented on docker/Dockerfile
> +     # (for `aiidalab/aiidalab<23.03.2` the `setup.py` should be in the root folder of the app https://github.com/aiidalab/aiidalab/pull/382).
As a developer, you can install it with pip, but from appstore it calls `aiidalab install`. Here in `Dockerfile` I use it to test the appstore installation behavior is correct. You can have a look at https://github.com/aiidalab/aiidalab-qe/pull/532 why I changed it to this to spot the error which not raised before.

2023-11-08 09:38 UTC, unkcpz commented on tests/conftest.py
> +    app.submit_step.sssp_installation_status.installed = True
Add a comment on why this mock needed.

2023-11-08 14:03 UTC, unkcpz commented
The issue is opened in https://github.com/aiidalab/aiidalab-qe/issues/550 for future enhancement on the generic pseudo setup tool.

2023-11-08 14:17 UTC, superstar54 approved these changes
LTGM.

2023-11-08 21:58 UTC, merged

2023-11-08 21:58 UTC, unkcpz commented
@superstar54 thanks a lot for the review!