Feature/edit step
aiidalab/aiidalab-qe pull request #537
Opened 2023-10-26 16:23 UTC by superstar54

2023-10-27 08:43 UTC, unkcpz requested changes
Thanks a lot! Some requests and I find some small issues in the behavior, here is how to reproduce:
1. select structure
2. confirm the configuration
3. now it is in step3, go back to step2 and change, without save.
4. not go back to step2 but to step1 or step4 and then go to step 2 to confirm.
5. it leads me to step3 but this blocker is still there.

2023-10-27 08:43 UTC, unkcpz commented on src/aiidalab_qe/app/configuration/__init__.py
> +        self.is_confirmed = False
And why don't we name it `self.saved`?

2023-10-27 08:43 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +    _app_submission_blockers = tl.List(tl.Unicode())
Please just use `_submission_blocker`.

2023-10-27 08:43 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +            previous_step = self.steps[change["old"]][1]
"previous_step" sound more like step2 for step3, if I understand correctly, this is for the step where the old index point to.
Maybe name it "step_old_idx" and "step_new_idx".

2023-10-27 10:22 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/__init__.py
> +        self.is_confirmed = False
I used `saved` before, but since the button is `confirm`, and the text will be strange with both `saved` and `confirm` in the code, but mean the same thing.

2023-10-27 10:29 UTC, superstar54 commented on src/aiidalab_qe/app/main.py
> +    _submission_blockers = tl.List(tl.Unicode())
Here needs to be a trait, because we need to link it to the `_app_submission_blocker` in the submit_step.

2023-10-27 10:34 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/__init__.py
> +        self.is_confirmed = False
> It is an attribute that be called by other widgets, I think it will be better to make it a trait.

I think `trait` is not needed here, it is static data and we don't need to synchronize it with others.

2023-10-27 10:36 UTC, superstar54 commented
Thanks @unkcpz for reviewing the code. 

> Some requests and I find some small issues in the behavior, here is how to reproduce:

This is fixed.

For our comment on `trailt`. I kind of disagree. Please give a more clear description of why you think the change is needed.

2023-10-27 18:47 UTC, superstar54 commented
After a discussion with @unkcpz , we decided to make the following changes:
- only when entering the submit step, do we update the blocker messages
- select a new structure will partially reset the structure step, thus enabling the `confirm` button

We also agreed that in the submit step, updating the blocker_message inside the `_update_date` method is not a good way. I tried to separate it from the `_update_date` method, but I found that several other codes, e.g. `qe_setup_status` and `sssp_installation_status` also depend on this, and some logic and more codes need to update to make this happens,  thus better to do this in another PR in the future. Anyway, for this PR, the current code works without a problem.

@unkcpz Please have another check.

2023-10-28 23:22 UTC, unkcpz commented
Emm... no need to make complex changes actually. You can have a look at https://github.com/aiidalab/aiidalab-qe/pull/539/commits/5a775ea4fa6f82d495182ec65486f8d33817aba2 how the logic can be improved for the submission blocker message by separate the internal blocker and external blocker.
Can you adopt the changes from https://github.com/aiidalab/aiidalab-qe/pull/539 to this PR and fix the unit test?

2023-10-28 23:24 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +    _outside_submission_blockers = tl.Dict()
In fact, my "picky" review starts from here, I smell a not-good implementation because the object with the same functionality has a different type, it will subtlely cause the problem and make future maintenance not easy.

2023-11-07 10:02 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +        """Check unsaved change in the step when leaving the step."""
I did some iron-up for this method in https://github.com/aiidalab/aiidalab-qe/pull/539, can you adopt it as well?

2023-11-07 10:05 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +        blockers = self.internal_submission_blockers + self.external_submission_blockers
Is that possible that blockers are `None` then you cannot use `+`. 
The `change` is not used, please use `_` in as argument.

2023-11-07 10:07 UTC, unkcpz requested changes
Thanks @superstar54, some more requests. Should be all fine then, I'll give it a through test then.

2023-11-08 09:16 UTC, superstar54 commented on src/aiidalab_qe/app/main.py
> +        """Check unsaved change in the step when leaving the step."""
Thanks. I adopted it.

2023-11-08 09:17 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +        blockers = self.internal_submission_blockers + self.external_submission_blockers
Thanks for the suggestion. I change it to `_change`. The blockers are always `list`, I think we don't need to check `None` here.

2023-11-08 10:56 UTC, unkcpz commented on src/aiidalab_qe/app/main.py
> +        with self.submit_step.hold_sync():
I think this is not needed, only at very end the `submit_step` is updated.

2023-11-08 11:08 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +        blockers = self.internal_submission_blockers + self.external_submission_blockers
If the variable is not used usually we use `_` in widget callback.

2023-11-08 11:13 UTC, unkcpz approved these changes
Thanks! Looks good.

2023-11-08 14:01 UTC, merged