fix logic of band_kpoints_distance for periodicity x and xy
aiidalab/aiidalab-qe pull request #547
Opened 2023-11-06 10:21 UTC by AndresOrtegaGuerrero

this PR fixes a bug on the bands (summary_viewer.py) logic when running a bands for periodicity x and xy. The bug rises for not having bands_kpoints_distance in the input for periodicity x and xy

2023-11-07 14:56 UTC, unkcpz requested changes
Thanks @AndresOrtegaGuerrero. But I guess there may be a more proper solution for this, let's see how @superstar54's idea.

2023-11-07 14:56 UTC, unkcpz commented on src/aiidalab_qe/app/result/summary_viewer.py
> +    "precise": 0.015,
Emmm.... Where are those values come from? I think we need a centrailse place for such value, is `qeapp.yaml` a good place for it? If it is from the `aiida-quantumespresso` protocol, then there is `PwBaseWorkChain.get_protocol_inputs(protocol)` to get it rather than define it again here.

2023-11-07 14:56 UTC, unkcpz commented on src/aiidalab_qe/app/result/summary_viewer.py
> +        else:
@superstar54 there are still hardcoded code for bands and pdos here, are these able to be removed by the plugin implementation?

2023-11-07 15:14 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/summary_viewer.py
> +    "precise": 0.015,
@unkcpz  so these values come from the protocol from bands in the quantum espresso plugin.  For 1D and 2D we have to remove `bands_kpoints_distance` from the inputs.

2023-11-08 09:50 UTC, superstar54 commented
I think there are ways to show the plugin's summary info.
- Add an entry point in the `Summary` panel, which can append a new section for each plugin. The plugin developer only needs to implement a `get_report` function (like the `get_builder` function in the workchain entry point). This function takes the `ui_parameters` and the workchain's output as inputs, and returns a dict to be printed out.
- The plugin developer adds a new tab in the plugin's result panel. and we don't need to change anything on the qeapp side.

What are your opinions? @AndresOrtegaGuerrero @unkcpz

2023-11-08 10:09 UTC, AndresOrtegaGuerrero commented
> I think there are two ways to show the plugin's summary info.
> 
> * Add an entry point in the `Summary` panel, which can append a new section for each plugin. The plugin developer only needs to implement a `get_report` function (like the `get_builder` function in the workchain entry point). This function takes the `ui_parameters` and the workchain's output as inputs, and returns a dict to be printed out.
> * The plugin developer adds a new tab in the plugin's result panel. and we don't need to change anything on the qeapp side.
> 
> What are your opinions? @AndresOrtegaGuerrero @unkcpz

In the first one, the entry can just append in the same tab of 'Workflow Summary' without generating another tab? , Because if that is the case, is nice since there you can get like different sections of the options for each plugin, like one for pdos, for bands, and for future ones. 

I am assuming this requires a different PR to address this?, right @superstar54 ?
If this is the case, then at least we should provide a temp solution  to enable displaying bands for 1D and 2D systems, currently with a bug.

2023-11-08 10:14 UTC, superstar54 commented
> the entry can just append in the same tab of 'Workflow Summary' without generating another tab?

Yes

> I am assuming this requires a different PR to address this?

Yes.

> then at least we should provide a temp solution to enable displaying bands for 1D and 2D systems, currently with a bug.

I agree.

2023-11-08 11:16 UTC, unkcpz commented
> If this is the case, then at least we should provide a temp solution to enable displaying bands for 1D and 2D systems, currently with a bug.

I agree, please open an issue and add a comment so we remember to clean up the code after the plugin is there in the future.

2023-11-08 11:56 UTC, AndresOrtegaGuerrero commented
@unkcpz @superstar54  do you maybe know why i cant get all the checks to be completed?

2023-11-08 13:08 UTC, unkcpz commented
>  do you maybe know why i cant get all the checks to be completed?

There is only one test that failed which is arm64 test. I guess it was some problem on the self-runner (Marnik's mac workstation), I'll check it after. There is nothing to worry about if the amd64 checks are passed, hopefully.

2023-11-08 13:09 UTC, unkcpz commented on src/aiidalab_qe/app/result/summary_viewer.py
> +    "precise": 0.015,
My point is if it is from protocol, you can read it by `PwBaseWorkChain.get_protocol_inputs(protocol)`, is that work?

2023-11-09 09:41 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/summary_viewer.py
> +    "precise": 0.015,
I modified as you suggested , and it works :)

2023-11-09 10:18 UTC, unkcpz commented on src/aiidalab_qe/app/result/summary_viewer.py
> +
I think this is not correct, this will make the report distance only rely on the protocol. 
The if..else is still needed as your previous change. 
If the user sets the `bands_kpoints_distance`, it needs to be updated in the report. Am I missing something?

2023-11-09 10:19 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/summary_viewer.py
> +
So far the user doesnt have that option from the bands plugin (qe app)

2023-11-09 10:32 UTC, unkcpz commented on src/aiidalab_qe/app/result/summary_viewer.py
> +
Good! Then it is all fine for me.

2023-11-09 10:32 UTC, unkcpz approved these changes
@AndresOrtegaGuerrero thanks!

2023-11-09 10:33 UTC, merged