Improve setup code performance
aiidalab/aiidalab-qe pull request #565
Opened 2023-11-21 10:54 UTC by superstar54

Reported by @unkcpz in #564  that, it takes 1-2 sec to set up a code, and we have 14 codes, so around 20 sec in total. Which is not good, and it takes too long to load the container.
We can remove some of the codes, and only keep the ones that will used in the present plugin, as suggested in #564 . There are still 6 codes, which need around 10 secs. 

I looked into the issue and found that most of the time is used to set up the verdi command, profile and database. Thus it's would be good to combine all code set up as one.

Since the code setup is run in a different thread, thus, using the `InstalledCode` directly will fail when storing the code. This PR uses the `python -c` command to run in the `subprocess`. 
The total time to set up all 14 codes now reduced to 2-3 secs.

2023-12-12 13:38 UTC, unkcpz commented on src/aiidalab_qe/common/setup_codes.py
> +        run(["python", "-c", python_code], capture_output=True, check=True)
I just realized this change might be a bit flaky because it is not very common way we setup codes in aiida. 
It looks still like a workaround. The ideal solution will be calling the API to setup the codes instead of creating a script and run it with `subprocess.run`. 

On the other hand, we already know that the performance issue comes from every time calling `verdi` it takes time to import the modules which improved in `v2.5.0` and will be released soon. 

Let's hold the solution of this PR or maybe you try using calling API directly?

2023-12-12 13:40 UTC, unkcpz requested changes
@superstar54 thanks! Please see my comment above, I propose to hold this PR at the moment to see if there are better solutions and see if `aida-core==2.5.0` will fix the performance issue.

2023-12-12 13:40 UTC, unkcpz commented on src/aiidalab_qe/common/setup_codes.py
> +        run(["python", "-c", python_code], capture_output=True, check=True)
I just realized this change might be a bit flaky because it is not very common way we setup codes in aiida. 
It looks still like a workaround. The ideal solution will be calling the API to setup the codes instead of creating a script and run it with `subprocess.run`. 

On the other hand, we already know that the performance issue comes from every time calling `verdi` it takes time to import the modules which improved in `v2.5.0` and will be released soon. 

Let's hold the solution of this PR or maybe you try using calling API directly?

2024-03-03 09:47 UTC, superstar54 commented
Will make another PR from my forked repo.

2024-03-03 09:47 UTC, closed without merging