Feature/new computational resource widget
aiidalab/aiidalab-qe pull request #566
Opened 2023-11-21 15:09 UTC by superstar54

2023-11-21 16:00 UTC, superstar54 commented
@AndresOrtegaGuerrero @mikibonacci , It would be great if you could test this PR in your plugins.

@mbercx , do you think we still need to add the `number of k-pools` here? Does the new QE version support setting the parallelization automatically?

2023-11-22 13:38 UTC, AndresOrtegaGuerrero commented
> @AndresOrtegaGuerrero @mikibonacci , It would be great if you could test this PR in your plugins.
> 
> @mbercx , do you think we still need to add the `number of k-pools` here? Does the new QE version support setting the parallelization automatically?

I think the k-pools should be somehow controlled, for example if you want to run the Berry phase code in pw.x you cant use pools. What it could be nice is to have a dummy run. , or a method that given the structure and the input parameters, it can tell you how many k-point you will have, like that we can provide the user a suggestion for the pools to use

2023-11-22 13:44 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/submission/__init__.py
> +        """Update the resources and parallelization of the ``relax`` builder."""
This update  should also affect the other plugins right ?

2023-11-22 13:47 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +class PWscfWidget(ComputationalResourcesWidget):
Maybe add docstring in this one

2023-11-22 13:49 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +    nodes = traitlets.Int(default_value=1)
should it be docstring for the nodes and cpus traitlets ?

2023-11-22 13:54 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/plugins/pdos/workchain.py
> +    pw_code = codes.get("pw")["code"]
Would this affect how you call the codes in the workchain of external plugin?

2023-11-22 15:14 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +        """Update the resources and parallelization of the ``relax`` builder."""
If other plugins use the same `pw` code as the `relax` workchain, yes.

2023-11-22 15:19 UTC, superstar54 commented on src/aiidalab_qe/plugins/pdos/workchain.py
> +    pw_code = codes.get("pw")["code"]
Yes, I have updated the doc.

2023-11-22 15:19 UTC, superstar54 commented on src/aiidalab_qe/common/widgets.py
> +class PWscfWidget(ComputationalResourcesWidget):
thanks. I added the docstring.

2023-11-23 10:46 UTC, mbercx commented
> do you think we still need to add the number of k-pools here? Does the new QE version support setting the parallelization automatically?

New QE versions (I forgot from which one, but def v7.2) indeed support setting k-pools automatically.

> I think the k-pools should be somehow controlled, for example if you want to run the Berry phase code in pw.x you cant use pools.

Hmm, I'm not familiar with this use case, but give running on of these calculations a try _without_ specifying k-points and see if the header mentions k-point parallelization. I hope the automated k-pool configuration won't be used in this case then. ^^

> What it could be nice is to have a dummy run. , or a method that given the structure and the input parameters, it can tell you how many k-point you will have, like that we can provide the user a suggestion for the pools to use

I haven't tried this, but figuring out the number of k-points can be a bit tricky since you need to determine the symmetries _exactly_ like Quantum ESPRESSO does. A dummy run is useful in some cases (e.g. we do this to figure out the number of q-points in the [`PhParallelizeQpointsWorkChain`](https://github.com/aiidateam/aiida-quantumespresso-ph/blob/3e99a1ef776882e1a543727b0b816add386f20d2/src/aiida_quantumespresso_ph/workflows/ph/parallelize_qpoints.py#L38)), but I'm not sure it's worth it for `pw.x` k-points because typically you have so many it doesn't matter that much.

2023-11-23 15:33 UTC, mikibonacci commented on src/aiidalab_qe/common/widgets.py
> +        self.num_nodes = ipw.BoundedIntText(
In principle, same code for different step may require different resources. 
In my opinion this can be achieved by defining multiple QEAppComputationalResourcesWidget, e.g. one for relax, one for bands (where we may want to add the -nband...).

So we may have PwRelaxWidget, PwBandsWidget... do you think it is the right way to do it? In this way multiple codes which share the same executable (same aiida node) may be used differently by different plugins. I am thinking about for example a case in which we start from a primitive cell, then we compute something for a big supercell. Using the same resources for the simulations would be not efficient

2023-11-23 19:28 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +        self.num_nodes = ipw.BoundedIntText(
@superstar54 @mikibonacci , there could be many examples , like in the vibroscopy plugin, the PhononWorkChain can use npools, but the Dielectric cannot , or for example in the case of the one i am developing for spin orbit coupling, i might need more resources than the ones use for PwRelax (with out SOC) , though it might create a lot of instances in the step 3

2023-11-29 22:27 UTC, unkcpz requested changes
If you don't override the methods of a class to create a new class, but simply extend it with more methods, please don't use class inherit. 
If I understand correctly, there is no modification of `ComputationalResourceWidget`, but add two more widgets on top of it. So why not using composite widget design? Am I miss something?

2023-11-29 22:27 UTC, unkcpz commented on src/aiidalab_qe/common/widgets.py
> +from aiidalab_widgets_base import ComputationalResourcesWidget as AiiDACodeWidget
The name `AiiDACodeWidget` easily get confused with `AiiDACodeSetup` in AWB: https://github.com/aiidalab/aiidalab-widgets-base/blob/aba0bdb3dc7a7e1af268145a0fd643194e681523/aiidalab_widgets_base/computational_resources.py#L1086 which is for detailed code setup specificly. 

I didn't see the point of renaming the class.

2023-11-29 22:27 UTC, unkcpz commented on src/aiidalab_qe/common/widgets.py
> +    @traitlets.observe("value")
I know this `value` comes from `ComputationalResourceWidget` but the interface is not clearly exposed. 
Instead of inherit from `ComputationalResourceWidget`, this case fit the composite object quite well. Please consider using `ComputationalResourceWidget` as sub-widget in this widget you defined.

2023-12-13 16:06 UTC, AndresOrtegaGuerrero commented
> > do you think we still need to add the number of k-pools here? Does the new QE version support setting the parallelization automatically?
> 
> New QE versions (I forgot from which one, but def v7.2) indeed support setting k-pools automatically.
> 
> > I think the k-pools should be somehow controlled, for example if you want to run the Berry phase code in pw.x you cant use pools.
> 
> Hmm, I'm not familiar with this use case, but give running on of these calculations a try _without_ specifying k-points and see if the header mentions k-point parallelization. I hope the automated k-pool configuration won't be used in this case then. ^^
> 
> > What it could be nice is to have a dummy run. , or a method that given the structure and the input parameters, it can tell you how many k-point you will have, like that we can provide the user a suggestion for the pools to use
> 
> I haven't tried this, but figuring out the number of k-points can be a bit tricky since you need to determine the symmetries _exactly_ like Quantum ESPRESSO does. A dummy run is useful in some cases (e.g. we do this to figure out the number of q-points in the [`PhParallelizeQpointsWorkChain`](https://github.com/aiidateam/aiida-quantumespresso-ph/blob/3e99a1ef776882e1a543727b0b816add386f20d2/src/aiida_quantumespresso_ph/workflows/ph/parallelize_qpoints.py#L38)), but I'm not sure it's worth it for `pw.x` k-points because typically you have so many it doesn't matter that much.

I think the number of k-points ("having so many") can be debatable when using a system with a big unit cell

2023-12-13 16:34 UTC, mbercx commented
> I think the number of k-points ("having so many") can be debatable when using a system with a big unit cell

Sure, that's true. But anyways QE should now be able to figure out how to parallellize over the k-points itself, so adding a dummy run to any of the `aiida-quantumespresso` work chains is currently not on the agenda.

2023-12-13 16:47 UTC, AndresOrtegaGuerrero commented
> > I think the number of k-points ("having so many") can be debatable when using a system with a big unit cell
> 
> Sure, that's true. But anyways QE should now be able to figure out how to parallellize over the k-points itself, so adding a dummy run to any of the `aiida-quantumespresso` work chains is currently not on the agenda.

Even for the pools? QE can now do this?

2023-12-13 17:35 UTC, mbercx commented
> Even for the pools? QE can now do this?

Yup ^^. Give it a try with QE v7.2

2024-01-19 11:44 UTC, unkcpz commented
Update on the PR, @mikibonacci has a use case require this feature. So we need to try to get it merged ASAP.
@superstar54 and I had a in person quick chat, we agree on combine the widgets instead of using class inherit might be better solution.

2024-01-21 19:56 UTC, AndresOrtegaGuerrero commented
@unkcpz This PR is also important for #577 since something the dos.x and projwfn.x require at least 2 nodes when using DFT+U (if a system is big)

2024-01-21 21:32 UTC, unkcpz commented
Thanks @AndresOrtegaGuerrero for the remind. 

@superstar54, can you update the PR and address the comments that not answered? It is also worth to check the new default QE feature for the npool setting as mentioned in by @AndresOrtegaGuerrero above. We can have a chat this week to see what should be in this PR and what should do after to not block it to be merged.

2024-01-22 10:48 UTC, superstar54 commented
Thanks all for the review. I made changes based on your suggestions:

1. Use composite widget design for `QEAppComputationalResourcesWidget`. It now use `ComputationalResourcesWidget` as a sub-widget.
2. Add an override box for `parallelization` so that advanced users can set the `number of k-pools` for `pw`; otherwise, it will be determined by QE if not set. 


> same code for different step may require different resources.. ...So we may have PwRelaxWidget, PwBandsWidget... do you think it is the right way to do it?

For the moment, I suggest not adding this because our users may be confused, otherwise, there will be a lot of codes. Users may not be confused about which codes are for which. I think they don't need to understand the steps of the workchain. Users can set the max (cpus) resource anyway for all steps.

Do you think we also need to add this `parallelization` (`npool`) for the `projwfc`? For the moment, I disabled this options.

2024-01-25 09:57 UTC, unkcpz requested changes
Me and @superstar54 discussed in person on the PR, and now I get most of the idea of the changes. 
Another small milestone to the fully plugin design of the QeApp, thanks a lot for the great work @superstar54 

I only have a small request on the naming convention and probably also add a small test for the widget that when the checkbox ticked you test the k-point override is shown. 

@mikibonacci, can you give these change a test for the code setup you need?

2024-01-25 09:57 UTC, unkcpz commented on src/aiidalab_qe/app/submission/__init__.py
> +from aiidalab_qe.common.widgets import PWscfWidget, QEAppComputationalResourcesWidget
The name makes more sense if we call:
- `PWscfWidget` -> `PwCodeResourceSetupWidget`
- `QEAppComputationalResourcesWidget` -> `ComputationalResourceSetupWidget` (Mind with the "s", I think it is good to use singular format.)

The naming in AWB for `ComputationalResourcesWidget` might not ideal, and we can probably change it to `ComputationalResourceSelctionWidget`.

2024-01-29 15:15 UTC, AndresOrtegaGuerrero commented
@superstar54  I think this PR should include an option for `--ntasks-per-node` , when using QE 7.2 with gpu, this parameters becomes quite important , I have been experiencing this issue. So please provide this extra option for the `pw.x`

2024-04-05 15:42 UTC, AndresOrtegaGuerrero commented
@superstar54 Currently in the app, `dos.x `and `projwfn.x ` , use the same number of resources assigned to `pw.x` , as well as the `npools`

2024-04-05 15:46 UTC, superstar54 commented
> Currently in the app, dos.x and projwfn.x  , use the same number of resources assigned to pw.x , as well as the npools

What's would be the problem, if we add `--ntasks-per-node` and `--cpus-per-task`?

2024-04-05 15:57 UTC, AndresOrtegaGuerrero commented
> > Currently in the app, dos.x and projwfn.x  , use the same number of resources assigned to pw.x , as well as the npools
> 
> What's would be the problem, if we add `--ntasks-per-node` and `--cpus-per-task`?

There is none, at the moment these options arent available, or at least you dont have control over it 
For example imagine in one job you would like this input 
#SBATCH --job-name="qe-gpu"
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=6
#SBATCH --constraint=gpu

but maybe in another one you would like 

#SBATCH --job-name="qe-gpu"
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=3
#SBATCH --cpus-per-task=4
#SBATCH --constraint=gpu

2024-04-23 09:03 UTC, superstar54 commented
Hi @AndresOrtegaGuerrero , I added the support for `--ntasks-per-node` and `--cpus-per-task`, please try and review the PR. Here is a demo:

https://github.com/aiidalab/aiidalab-qe/assets/11457659/e23e045f-fad1-4278-9b7c-666d98b5cecf

2024-04-23 11:50 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +class PWscfWidget(QEAppComputationalResourcesWidget):
One question Xing, if i have an external plugin, can i set an independent pw.x for it ? or the pw.x is for all the plugins?

2024-04-23 13:19 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +from aiidalab_qe.common.widgets import PWscfWidget, QEAppComputationalResourcesWidget
Thank you for the suggestion. I've renamed it to `PwCodeResourceSetupWidget`. Regarding the name `ComputationalResourceSetupWidget`, I'll wait for the changes in AWB to be finalized before making updates here.

2024-04-23 13:19 UTC, superstar54 commented
> I only have a small request on the naming convention and probably also add a small test for the widget that when the checkbox ticked you test the k-point override is shown.

Hi @unkcpz , thanks for the review. I changed the name as you suggested and added a test for the new widget.

2024-04-23 14:07 UTC, superstar54 commented on src/aiidalab_qe/common/widgets.py
> +class PWscfWidget(QEAppComputationalResourcesWidget):
yes!

2024-04-24 17:10 UTC, AndresOrtegaGuerrero approved these changes
LGTM! , just be sure to communicate to the external plugins, so we make the change for the release . Great work !

2024-04-24 18:36 UTC, merged

2024-04-24 19:24 UTC, unkcpz reviewed
Thanks @superstar54. I think I am late for the party.

Just add two small comments.

2024-04-24 19:29 UTC, unkcpz commented on src/aiidalab_qe/plugins/pdos/workchain.py
> +        "num_cores_per_mpiproc": codes.get("projwfc")["cpus_per_task"],
This part seems a bit verbose and codes are repeating, consider to simplify it a bit?
- `builder.scf.pw.metadata.options.resources` five dots attributes call looks frightening and I think it makes plugin developer easy to make mistakes.
- For override the resources, maybe there already functions to do this in aiida-quantumespresso? @mbercx  Maybe you know it?

Somehow my previous comment on this was eaten by GitHub. I do it again.

2024-04-24 19:50 UTC, superstar54 commented on src/aiidalab_qe/common/widgets.py
> +            self.resource_detail.cpus_per_task.value = parameters["cpus_per_task"]
Thanks for your comment. It's a common way to use the `parameters.setter` interface, and then in another function `set_parameters` implement the real thing. In this pattern, the derived classes can easily modify or extend the setting logic by overriding a dedicated method, without needing to alter the property's interface. As you can see in the `PwCodeResourceSetupWidget` class.

2024-04-24 20:00 UTC, superstar54 commented on src/aiidalab_qe/plugins/pdos/workchain.py
> +        "num_cores_per_mpiproc": codes.get("projwfc")["cpus_per_task"],
Thanks for the suggestion. Indeed, one can use the `options` to set resources in the `get_builder_from_protocol`. and I agree that this should be the recommended way. I opened an [issue](https://github.com/aiidalab/aiidalab-qe/issues/682) on this.

2024-04-24 21:57 UTC, unkcpz commented on src/aiidalab_qe/common/widgets.py
> +            self.resource_detail.cpus_per_task.value = parameters["cpus_per_task"]
Where you find it "common"? I am fine with it, just seems the `get_` and `set_` are used and the property maybe redundant.