Feature DFT+U
aiidalab/aiidalab-qe pull request #577
Opened 2023-12-11 16:00 UTC by AndresOrtegaGuerrero

This PR add the feature to the Qe App to run simulations with DFT+U on-site

![image](https://github.com/aiidalab/aiidalab-qe/assets/34098967/80e609a3-3c59-4a92-9072-0541904b19b3)

The feature include a HubbardWidget, where the hubbard manifold is only one orbital, 
for example for Co will the the 3d , of for Si it will be the 3p 
(This can modified so the widget display the valence orbital shell , for example Co 3d and 4s) (Or if you prefer the the previous occupied shell like 3p for Co, we can discuss about this :D ) , 

I would like to have an independent tab for displaying DFT+U results (of interest) like the occupation matrix, and the occupation per atom and spin. I was wondering if this should be implemented as a plugin (Like in electronic_structure plugin) but i think the results should be available independently of the workchain run (bands, pdos, or an ext plugin)

2023-12-11 16:01 UTC, AndresOrtegaGuerrero commented
Before i continue to the final steps of the PR (like the independent tab) I was wondering if you @superstar54 and @unkcpz could give me your input on this PR design :D

2023-12-12 10:31 UTC, AndresOrtegaGuerrero commented
I have decided that the tab to display the occupation should be better in a second PR, otherwise this one will be too big

2023-12-12 13:43 UTC, unkcpz commented
@AndresOrtegaGuerrero thanks! I'll give it a look.

> I have decided that the tab to display the occupation should be better in a second PR

I agree, and since it is for the next release. I think even better steps are using your bandsplot widget to replace the current one first.

2023-12-15 15:15 UTC, unkcpz commented
Very cool! I didn't get to too much detail yet. But the first thing I notice is this create widget from an elements pattern which appeared in the magnetization setting and pseudopotential setting. I think the third time it appears to push me to provide a commend interface for the design. I'll try to work on that first.

2023-12-15 15:44 UTC, superstar54 requested changes
Thanks for the great work. Two quick comments:
- In the workflow, you need to pass the `hubbard_structure` to the plugin's workchain.
- The GUI is not set correctly when loading a finished job.

2023-12-19 08:19 UTC, AndresOrtegaGuerrero commented
@superstar54 @unkcpz  Thank you , I will work on the changes, I did notice something `aiida-quantumespresso` plugin PwBandsWorkChain is incompatible with HubbardStructure data, and also HubbardStructureData doesnt support 1D, 2D periodicity. I am waiting for this PR (https://github.com/aiidateam/aiida-quantumespresso/pull/998) to get approved. Let me know further changes

2024-02-01 13:01 UTC, AndresOrtegaGuerrero commented
For this PR to be evaluated we need the following PRs to be merged

- [ ] #566 
- [ ] https://github.com/aiidateam/aiida-quantumespresso/pull/998

2024-04-11 11:46 UTC, superstar54 requested changes
Thanks for the great work! There are a few comments, and then I think it is ready to go.
As for the DFT+U+V part, I think we can implement it in a future PR. For the moment, let's merge this PR first.

2024-04-11 11:46 UTC, superstar54 commented on tests/configuration/test_advanced.py
> +
Since this structure may be useful to test other properties, could you move this to `conftest.py` and create a fixture for it.

2024-04-11 11:46 UTC, superstar54 commented on src/aiidalab_qe/common/widgets.py
> +            f"{kind} - {manifold}"
There is possible risk. If a kind has a name "Co - up", then the label will be "Co - up - 3d", this will raise an error in the Workchain when it tries to get the kind and manifold back.

2024-04-11 11:46 UTC, superstar54 commented on src/aiidalab_qe/common/widgets.py
> +        self.hubbard = ipw.Checkbox(
suggest to change the name, e.g.
```suggestion
        self.activate_hubbard = ipw.Checkbox(
```

2024-04-11 11:57 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +            f"{kind} - {manifold}"
but usually we dont allow names as Co-up, we allow tags like Co1, or Co2 ,

2024-04-11 14:17 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +            f"{kind} - {manifold}"
But i guess this should be control @ the structure step then , dont you think ?

2024-04-11 14:25 UTC, AndresOrtegaGuerrero commented on tests/configuration/test_advanced.py
> +
thank you , i will add it in` conftest.py`

2024-04-11 14:25 UTC, AndresOrtegaGuerrero commented
@superstar54 Before merging, we need to request a new release of aiida-quantumespresso plugin, and bump the version here. So it doesn't fail when considering 1D, 2D systems for bands and so on.

2024-04-11 14:26 UTC, superstar54 commented on src/aiidalab_qe/common/widgets.py
> +            f"{kind} - {manifold}"
Yes, the tags are controlled in the structure step. However, the problem here is the `{kind} - {manifold}` could result in something like `Co-up - 3d` (e.g. if user import data from database, and the kind name is Co-up already), thus it will raise an error in the WorkChain, where you have one line of code 
```
kind, orbital = key.split(" - ")
```
I suggest you split by the last `-` to solve this problem, or you can use a dict with the kind and orbital saved explicitly.

2024-04-11 19:26 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +            f"{kind} - {manifold}"
@superstar54 so for something like this , `kind, orbital = key.rsplit("-", 1)`?

2024-04-11 19:38 UTC, superstar54 commented on src/aiidalab_qe/common/widgets.py
> +            f"{kind} - {manifold}"
Yes

2024-04-15 20:19 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/widgets.py
> +            f"{kind} - {manifold}"
Done, let me know

2024-04-16 11:11 UTC, superstar54 commented on src/aiidalab_qe/workflows/__init__.py
> +                kind, orbital = key.rsplit("-", 1)
There are spaces when creating the label.
```suggestion
                kind, orbital = key.rsplit(" - ", 1)
```

2024-04-16 12:08 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/workflows/__init__.py
> +                kind, orbital = key.rsplit("-", 1)
Done

2024-04-16 12:12 UTC, superstar54 approved these changes
LGTM!

2024-04-23 13:40 UTC, merged