New BandsPdosWidget
aiidalab/aiidalab-qe pull request #581
Opened 2023-12-13 15:24 UTC by AndresOrtegaGuerrero

This PR introduces a new bands_pdos_widget using plotly, the widget include options of drag, pan and toogle , save a snapshot , and download the data.

The formating of the bands/pdos has been moved from the result plugin to the common/bandspdoswidget.py

It allows different selection of atoms to consider, or different representations ( We can modified or create new according to your suggestions)

For spin polarized calculations it represents bands_up in red, and bands_down in blue. For non polarized the line is in black color.

The new `_projections_curated_options` allows to curated SOC pdos. 

The legend has a wheel fixing #552

2023-12-13 16:03 UTC, AndresOrtegaGuerrero commented
Please have a look , test it let me know any further changes and/or developments.

2023-12-13 16:16 UTC, AndresOrtegaGuerrero commented
I think in a second PR, i can add different test for the new widget

2024-01-10 10:22 UTC, unkcpz commented
Pinning @mikibonacci, he mentioned he has a use case that needs some adaption on the bandsplotwidget which will be replaced by this PR, so he can give a quick review and a test.

I didn't start looking at the code, but give it a try on the qeapp, from the outcome it is exactly what we needed, thanks for the great work @AndresOrtegaGuerrero.

2024-01-10 23:06 UTC, unkcpz requested changes
@AndresOrtegaGuerrero I give it a first go. 

I notice that the data validation is missing. The `BandPdosWidget` accept AiiDA node as input which make the widget not generic and vulnerable to the future change of `BandData`. 
In the original `bandsplotwidget`, we add a middle layer of `dict` type between  AiiDA node and input for the widget. The object pass to the widget then can be validated by the schema. 
I'd suggest adding this design back to the new widget. For the data validation, you can try to use pydantic.

Besides, the unit tests for the newly added widget would be very useful.

2024-01-11 08:50 UTC, AndresOrtegaGuerrero commented
> @AndresOrtegaGuerrero I give it a first go.
> 
> I notice that the data validation is missing. The `BandPdosWidget` accept AiiDA node as input which make the widget not generic and vulnerable to the future change of `BandData`. In the original `bandsplotwidget`, we add a middle layer of `dict` type between AiiDA node and input for the widget. The object pass to the widget then can be validated by the schema. I'd suggest adding this design back to the new widget. For the data validation, you can try to use pydantic.
> 
> Besides, the unit tests for the newly added widget would be very useful.

@unkcpz  Thank you , you mean that the widget doesnt call `get_pdos_data` , `exports_bands_data` from the widget using the node, but instead that the output from these functions is the input of the widget ?

2024-01-17 08:50 UTC, unkcpz requested changes
Thanks for the changes @AndresOrtegaGuerrero. I have some request upon method names and especially the flow of data/objects.

This is a widget for dealing with the bands/pdos data, convert the data to the format that plotly can plot a plot object. Then generate the plotly plot object and render it to the ipyoutput. 

I'd suggest at least separate methods for plotly plot object creating to a class `BandPdosPlot`. The class getting a formatted bands/pdos data and knowing how to create a plotly plot object. Then for the `BandPdosWidget`, it dealing with 1) parsing the data to the formatted data and pass to `BandPdosPlot` 2) dealing the logic with the QeApp, such as initialize the widget and hide the widget.

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +        )
Consider to using `StatusHTML`? Which is designed for pop the warning/error message.
The message display widget like this usually used inside the widget only, so you can make it `self._wrong_syntax` or `self._message`

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +    - pdos_options_out: Output widget to clear specific widgets.
I think most of these attributes don't need to be exposed.

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +            description="Update Plot",
The `update_plot_button` seems redundant to me, when users make changes to the widget, after the change, the plot is supposed to be updated automatically.

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +        self.export_dir = Path.cwd().joinpath("exports")
this is not used anywhere else. 
```suggestion
```

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +        import plotly.graph_objects as go
Any reason to put the import for each function? If not, please move it to the top.

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +    def _bands_labeling(self, bands):
```suggestion
    def _get_bands_labeling(self, bands):
```
this is a method that return the label from the input data, better to call with `_get` as you did for other methods.

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +        my_labels = []
```suggestion
        paths = bands[0].get("paths")
        labels = []
```
"my"? The paths and labels have their own free will, they belong to nobody ;P

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +                    if my_clean_labels[-1][-1] == i[1]:
```suggestion
            if my_clean_labels and (i not in my_clean_labels) and (my_clean_labels[-1][-1] == i[1]):
```
I guess this is the same? If not can you try to simplify it, too many layers of nest indicate things that can be polished.

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +        def download_data(_=None):
Can you move this function out?

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +        self.band_labels = self._bands_labeling(self.bands_data)
I didn't see the reason why these attributes need to initialize here. When the widget initialized, there is no plot, so these attributes are not needed.

2024-01-17 08:50 UTC, unkcpz commented on src/aiidalab_qe/common/bandpdoswidget.py
> +    def _bandsplot_widget(self):
The method name is `bandsplot` but it also deal with pdos, better to be called as `bandpdosplot`.
Moreover, this function return a plotly plot objcet, so I'd call it `get_bandpdos_plot`. 

The data flow is more clean to be like: data -> plotly plot object -> ipyoutput widget, can you check the PR and try to apply this flow?

2024-01-17 10:33 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/bandpdoswidget.py
> +            description="Update Plot",
@unkcpz  This could be problematic, considering that you also have the choice to select atoms , is better to control when to update the plot , once you are done defining the atoms you are selecting.

2024-01-17 10:35 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/common/bandpdoswidget.py
> +        def download_data(_=None):
When i do it , it doesnt work i will check if i can move it out

2024-02-05 08:42 UTC, unkcpz commented
Hi @AndresOrtegaGuerrero, it is all in good shape. Before merge, I want to ask for a final test on using the new widget for the phonon bands plot. Can you or @mikibonacci give a test on using the new widget for it? I think it is a good proof that the API exposed by the new widget is generic enough for most of use cases.

2024-02-05 08:43 UTC, unkcpz commented
Since this replace the `widget_bandsplot`, it should be able to remove the dependency from `setup.cfg`.

2024-02-05 13:53 UTC, merged