Add Feature: Documentation Page for XAS Plugin
aiidalab/aiidalab-qe pull request #614
Opened 2024-02-01 11:24 UTC by PNOGillespie

# Overview

This PR adds a complete documentation set for using the XAS plugin of AiiDALab-QE, covering both calculation setup and post-processing of the final spectra using the Plotly-derived widget provided with the plugin. The instructions should adequately cover all features of the XAS App using a self-contained, robust, and well-tested example.

This will be followed up by a video demonstration of this example, as required for BIG-MAP project key deliverables, to accompany the documentation.

Note that the documentation example uses Li<sub>2</sub>CO<sub>3</sub> as the structure, which has been added to the "From Examples" list in `src/aiidalab_qe/app/static/`, so there shouldn't be any issues in the future with missing links to important files.

2024-02-01 12:46 UTC, PNOGillespie commented
Hi @superstar54, I reformatted the source code as you asked so that each sentence is on a separate line. Obviously this wasn't possible for lists, because the syntax doesn't let you do that, but hopefully that makes review easier.

2024-02-09 09:47 UTC, superstar54 requested changes
Nice docs! Very clear and rigorous. I only has one small request, please see the comment.

2024-02-09 09:49 UTC, superstar54 commented on docs/source/howto/xas.rst
> +       $ aiidalab install quantum-espresso>=v24.04.0a1
There seems to be a bug in the `aiidalab install`.  This command does not work as expected. I would suggest removing this part. We try to avoid the user using the command line if they can do it in the GUI.

2024-02-12 14:01 UTC, superstar54 commented
> Just out of curiosity (and also in case this needs to be documented properly), is there already an issue page for the problem with `aiidalab install`?

One needs to include `"` or `'`
```diff
- aiidalab install quantum-espresso>=v24.04.0a1
+ aiidalab install "quantum-espresso>=v24.04.0a1"
```

2024-02-12 14:02 UTC, superstar54 approved these changes

2024-02-12 14:05 UTC, merged