Implement optimade widget in Qeapp
aiidalab/aiidalab-qe pull request #632
Opened 2024-03-12 06:29 UTC by unkcpz

2024-03-12 06:42 UTC, unkcpz commented
blocked by #633, rebase after merge.

2024-03-12 10:52 UTC, unkcpz commented on setup.cfg
> +    aiidalab-widgets-base>=2.2.0a0
Why? The AWB is the explicit dependency we need in the QeApp.

2024-03-12 11:08 UTC, danielhollas commented on setup.cfg
> +    aiidalab-widgets-base>=2.2.0a0
Sorry, made a typo, I meant to use the optimade extra from AWB.

2024-03-12 12:29 UTC, unkcpz commented on setup.cfg
> +    aiidalab-widgets-base>=2.2.0a0
Yes, it can, but I was thinking about to directly move to depend on the ipyoptimade.

2024-03-12 12:33 UTC, unkcpz commented on setup.cfg
> +    aiidalab-widgets-base>=2.2.0a0
Okay, I use the way you suggested.

2024-03-12 14:26 UTC, danielhollas requested changes
Thanks @unkcpz, I think reusing the optimade widget from AWB makes sense.

Just one question about the version

2024-03-12 14:26 UTC, danielhollas commented on setup.cfg
> +    aiidalab-widgets-base[optimade]>=2.2.0a0
```suggestion
    aiidalab-widgets-base[optimade]~=2.2.0a0
```

Not sure if this change was intentional? Pinning to minor version seems safer, since we tend to do breaking changes on minor versions in AWB.

2024-03-13 06:13 UTC, danielhollas approved these changes

2024-03-13 06:31 UTC, merged

2024-03-15 16:49 UTC, superstar54 commented
@unkcpz @danielhollas I can not install the QE App from after this PR. 
```console
 Using cached notebook-5.7.0-py2.py3-none-any.whl (9.0 MB)
  Using cached notebook-5.6.0-py2.py3-none-any.whl (8.9 MB)
  Using cached notebook-5.5.0-py2.py3-none-any.whl (8.4 MB)
  Using cached notebook-5.4.1-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.4.0-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.3.1-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.3.0-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.2.2-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.2.1-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.2.0-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.1.0-py2.py3-none-any.whl (8.0 MB)
  Using cached notebook-5.0.0-py2.py3-none-any.whl (6.9 MB)
  Using cached notebook-4.4.1-py2.py3-none-any.whl (6.9 MB)
INFO: pip is looking at multiple versions of nest-asyncio to determine which version is compatible with other requirements. This could take a while.
Collecting nest_asyncio~=1.5
  Using cached nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
  Using cached nest_asyncio-1.5.9-py3-none-any.whl (5.3 kB)
INFO: pip is looking at multiple versions of jinja2 to determine which version is compatible with other requirements. This could take a while.
  Using cached nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
INFO: pip is looking at multiple versions of nbclassic to determine which version is compatible with other requirements. This could take a while.
  Using cached nest_asyncio-1.5.7-py3-none-any.whl (5.3 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
  Using cached nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached nest_asyncio-1.5.4-py3-none-any.whl (5.1 kB)
INFO: pip is looking at multiple versions of nest-asyncio to determine which version is compatible with other requirements. This could take a while.
  Using cached nest_asyncio-1.5.3-py3-none-any.whl (5.1 kB)
  Using cached nest_asyncio-1.5.2-py3-none-any.whl (5.1 kB)
  Using cached nest_asyncio-1.5.1-py3-none-any.whl (5.0 kB)
  Using cached nest_asyncio-1.5.0-py3-none-any.whl (5.0 kB)
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
Collecting matplotlib>=3.3.4,~=3.3
  Using cached matplotlib-3.8.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
```
And, the test also failed for this commit, could you check?

2024-03-15 17:08 UTC, danielhollas commented
@superstar54 are you installing inside aiidalab docker image?

From the output you sent I don't see any error, just a warning that it takes a long time. Can you provide more info what happened and which commands you've used?

2024-03-15 17:09 UTC, unkcpz commented
The tests far arm64 failed since the self-hosted machine is not turned on (It is @mbercx's workstation, please check when he is back from holiday maybe). 
For the installation error, can you provide more detail output, I cannot see any error from it.

2024-03-15 17:38 UTC, superstar54 commented
Thanks for the quick reply!
I used the AiiDAlab docker image with `aiidalab-launch`. I went to the repo, and run `pip install -e .`

Then, after around 10 mins, the installation is still in progress, which is un-normal. 

Could you also try?

2024-03-16 03:12 UTC, danielhollas commented
I've tested locally outside of the docker image with the new [uv installer](https://github.com/astral-sh/uv) which is much faster than pip, and in the end it did find a resolution.

I suspect the issue comes from switching from `optimade-client` to `ipyoptimade`. @unkcpz did you change any requirements there? I suspect some requirements were unpinned and pip now has to backtrack too far in dependency resolution.

2024-03-17 03:14 UTC, danielhollas commented
@superstar54 I am unable to reproduce this. I ran the following command and it succeeded fairly promptly in a fresh AiiDAlab container.

```
aiidalab install aiidalab-qe@git+https://github.com/aiidalab/aiidalab-qe
```

Perhaps there is an issue with previously installed dependencies? Can you verify that it is indeed this commit that introduces the issue? (i.e. installation from previous one succeeds?).

Otherwise, please make it run longer and open a new issue with all the pip output.

2024-03-17 13:47 UTC, unkcpz commented
@superstar54 can you try from a newly created aiidalab-launch instance? I guess the same that it is other dependencies cause the issue, because the docker build test explicitly run the installation and didn't take too much time to resolve the dependencies. 
One thing worth to check is to wait long enough until the installation finished and use `pip freeze > txt` to export the package list and compare with the one obtained from the environment that has no such issue.

2024-03-19 12:24 UTC, superstar54 commented
@danielhollas @unkcpz thanks for the feedback. In a fresh docker container, run `pip install -e .`, which works. 

### container with issue
```console
$ pip list | grep optimade
ipyoptimade                   0.2.0
optimade                      1.0.3
optimade-client               2022.9.19
```

### fresh container
```console
$ pip list | grep optimade
ipyoptimade                   0.1.1
optimade                      0.25.5
optimade-client               2022.9.19
```

I reinstalled the `ipyoptimade` with `0.1.1`, and it solved the problem. 
Should I create an issue for  `ipyoptimade==0.2.0`, or do you already know this, and it's not an issue?

2024-03-19 12:30 UTC, unkcpz commented
`ipyoptimade==0.2.0` use the pydantic v2 and that cause the problem. We already considered it by release 0.1.1 which support pydantic v1 and `>=0.2` to support pydantic v2.
No need to open the PR, I guess you have the problem since you installed aiidalab-qe before write after I release ipyoptimade 0.2.0 without 0.1.1.

2024-03-19 12:35 UTC, danielhollas commented
Hmm, but switching to pydantic 2 should not cause pip to choke on it.


@superstar54 can I still ask to leave the pip running to completion in the problem it container and provide the full output?
If this is something that may cause problem for users of existing installs then it would be good to know.

2024-03-19 12:48 UTC, superstar54 commented
I think it never ends, but maybe you can already get some ideas from the outputs
```
Obtaining file:///home/jovyan/apps/aiidalab-qe
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: Jinja2~=3.0 in /opt/conda/lib/python3.9/site-packages (from aiidalab_qe==24.4.0a2) (3.1.2)
Requirement already satisfied: filelock~=3.8 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab_qe==24.4.0a2) (3.12.2)
Requirement already satisfied: aiida-pseudo~=1.4 in /opt/conda/lib/python3.9/site-packages (from aiidalab_qe==24.4.0a2) (1.4.0)
Requirement already satisfied: aiidalab-widgets-base[optimade]~=2.2.0a0 in /opt/conda/lib/python3.9/site-packages (from aiidalab_qe==24.4.0a2) (2.2.0a0)
Requirement already satisfied: aiida-quantumespresso~=4.4.0 in /opt/conda/lib/python3.9/site-packages (from aiidalab_qe==24.4.0a2) (4.4.0)
Requirement already satisfied: aiida-core<3,~=2.2 in /opt/conda/lib/python3.9/site-packages (from aiidalab_qe==24.4.0a2) (2.4.1)
Requirement already satisfied: importlib-resources~=5.2 in /opt/conda/lib/python3.9/site-packages (from aiidalab_qe==24.4.0a2) (5.10.0)
Requirement already satisfied: graphviz~=0.19 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.20.1)
Requirement already satisfied: jsonschema~=3.0 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (3.2.0)
Requirement already satisfied: click~=8.1 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (8.1.3)
Requirement already satisfied: pyyaml~=6.0 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (6.0)
Requirement already satisfied: numpy~=1.21 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (1.24.3)
Requirement already satisfied: requests~=2.0 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (2.31.0)
Requirement already satisfied: tqdm~=4.45 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (4.64.1)
Requirement already satisfied: archive-path~=0.4.2 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.4.2)
Requirement already satisfied: psycopg2-binary~=2.8 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (2.9.3)
Requirement already satisfied: ipython>=7 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (7.33.0)
Requirement already satisfied: aio-pika~=6.6 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (6.8.1)
Requirement already satisfied: plumpy~=0.21.6 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.21.7)
Requirement already satisfied: importlib-metadata~=4.13 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (4.13.0)
Requirement already satisfied: kiwipy[rmq]~=0.7.7 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.7.7)
Requirement already satisfied: pytz~=2021.1 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (2021.3)
Requirement already satisfied: alembic~=1.2 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (1.8.1)
Requirement already satisfied: sqlalchemy~=1.4.22 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (1.4.50)
Requirement already satisfied: upf_to_json~=0.9.2 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.9.2)
Requirement already satisfied: pgsu~=0.2.1 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.2.3)
Requirement already satisfied: paramiko>=2.7.2,~=2.7 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (2.12.0)
Requirement already satisfied: tabulate~=0.8.5 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.8.10)
Requirement already satisfied: docstring-parser in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.15)
Requirement already satisfied: click-spinner~=0.1.8 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.1.10)
Requirement already satisfied: wrapt~=1.11 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (1.15.0)
Requirement already satisfied: circus~=0.18.0 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.18.0)
Requirement already satisfied: get-annotations~=0.1 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.1.2)
Requirement already satisfied: disk-objectstore~=0.6.0 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (0.6.0)
Requirement already satisfied: psutil~=5.6 in /opt/conda/lib/python3.9/site-packages (from aiida-core<3,~=2.2->aiidalab_qe==24.4.0a2) (5.9.2)
Requirement already satisfied: pint~=0.16.1 in /home/jovyan/.local/lib/python3.9/site-packages (from aiida-pseudo~=1.4->aiidalab_qe==24.4.0a2) (0.16.1)
Requirement already satisfied: xmlschema>=1.2.5,~=1.2 in /home/jovyan/.local/lib/python3.9/site-packages (from aiida-quantumespresso~=4.4.0->aiidalab_qe==24.4.0a2) (1.11.3)
Requirement already satisfied: qe-tools~=2.0 in /home/jovyan/.local/lib/python3.9/site-packages (from aiida-quantumespresso~=4.4.0->aiidalab_qe==24.4.0a2) (2.0.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.9/site-packages (from aiida-quantumespresso~=4.4.0->aiidalab_qe==24.4.0a2) (21.3)
Collecting pydantic>=1.10.8,~=1.10
  Using cached pydantic-1.10.14-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
Requirement already satisfied: aiidalab>=21.11.2 in /opt/conda/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (23.3.0)
Requirement already satisfied: more-itertools~=8.0 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (8.14.0)
Requirement already satisfied: PyCifRW~=4.4 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (4.4.5)
Requirement already satisfied: ase~=3.18 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (3.22.1)
Requirement already satisfied: humanfriendly~=10.0 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (10.0)
Requirement already satisfied: pymysql~=0.9 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (0.9.3)
Requirement already satisfied: nglview~=3.0 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (3.0.6)
Requirement already satisfied: widgetsnbextension<3.6.3 in /opt/conda/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe==24.4.0a2) (3.6.2)
Requirement already satisfied: ipytree~=0.2 in /home/jovyan/.local/lib/python3.9/site-packages (from aiidalab-widgets-base[optimade]~=2.2.0a0->aiidalab_qe [...]

2024-03-19 13:01 UTC, superstar54 commented
10 mins later, the output updated a little bit
```
  Using cached matplotlib-3.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
  Using cached matplotlib-3.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
  Using cached matplotlib-3.7.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
  Using cached matplotlib-3.7.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
  Using cached matplotlib-3.7.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)

```
@danielhollas  I cancel the installation since I still need to work on the container for other stuff. If you need more output, I may run this later.

2024-03-19 13:04 UTC, danielhollas commented
> @danielhollas I cancel the installation since I still need to work on the container for other stuff. If you need more output, I may run this later.

Thanks, it would be useful, because at the end you could list the packages that have been installed, which might be valuable.