add aiida-core-version in ci and action
aiidalab/aiidalab-qe pull request #643
Opened 2024-03-20 16:31 UTC by superstar54

It seems #638 is an urgent issue that needs to be fixed.

This PR tries to fix #638, and

- add `aiida-core-version` in the CI test.

2024-03-20 19:45 UTC, superstar54 commented
In aiidalab_qe, it requires the `aiida-quantumespresso~=4.4.0`, which needs aiida-core>=2.3. Thus I set the `aiida-core-version: [2.3, 2.4.3]`. This limits the power of the test. 
Hi @danielhollas @unkcpz , since you are more experienced with the package dependence. Any idea how to improve?

2024-03-20 20:17 UTC, danielhollas requested changes
> Thus I set the aiida-core-version: [2.3, 2.4.3]. This limits the power of the test.

That's fine for this PR, since we will soon bump the latest version to `2.5.0`.

2024-03-20 20:17 UTC, danielhollas commented on .github/actions/integration-tests/action.yml
> +              TAG: aiida-${{ matrix.aiida-core-version }}
Hmm, I don't think you want to change the tag here, since the purpose was to test the freshly-built QEApp image? I think it's fine to keep the integration tests as they were before, and only modify unit tests in `workflows/ci.yml`

2024-03-20 20:53 UTC, superstar54 commented on .github/actions/integration-tests/action.yml
> +              TAG: aiida-${{ matrix.aiida-core-version }}
the `integration-test` is an important test in the app. I think @unkcpz also wants to run it for a different aiida-core version. 
I can change it to 
```
aiida-core-version: [2.3, 2.4.3, "newly-baked"] 
```

2024-03-20 20:54 UTC, superstar54 commented
Any idea why these three tests didn't run?

![Screenshot from 2024-03-20 21-53-52](https://github.com/aiidalab/aiidalab-qe/assets/11457659/80b1f912-046c-4e2a-9de9-33085360b58d)

2024-03-20 21:20 UTC, unkcpz commented
Thanks @superstar54 

> Thus I set the aiida-core-version: [2.3, 2.4.3]. This limits the power of the test.

The oldest version set to `2.3` makes sense as you mentioned it compatible with the aiida-quantumespresso version we pinned. But can you try to set the lastest version to 2.5.0 and bump the required aiida-quantumespresso version? The initial idea was to see the tests pass for aiida-quantumespresso 4.4 and fail for 4.5 and manifest the problem of data-regression test.

2024-03-21 08:59 UTC, danielhollas commented on .github/actions/integration-tests/action.yml
> +              TAG: aiida-${{ matrix.aiida-core-version }}
Okay, then I think 2.3 and newly-baked is enough, since the latest aiida core should be part of newly-baked.

2024-03-21 09:01 UTC, danielhollas commented
Maybe let's get this merged first and deal with the 2.5 version in a separate PR.

2024-03-21 10:57 UTC, danielhollas requested changes
Erm, the I don't think the integration test changes are going to the right direction. The integration test is meant to test the newly build image, and it doesn't make sense to build an extra image with old aiida version just for this test. Let's stick with the changes to unit tests for now.

2024-03-21 10:57 UTC, danielhollas commented on .github/workflows/docker-build-test-upload.yml
> +                aiida-core-version: [2.3, newly-baked]
Hmm, I really don't think you should add new build here, that doesn't make sense to me. Afaik the qeapp image should always be build on top of the lastest aiidalab docker stack.

CC @unkcpz

2024-03-21 11:07 UTC, danielhollas commented
For a simple integration test with an older image, you could just pull the existing image, e.g. aiidalab/full-stack:aiida-2.3.3, and test that you can install QeApp into it.

We have a test like that in aiidalab-docker-stack repo.
https://github.com/aiidalab/aiidalab-docker-stack/blob/main/tests%2Ftest-full-stack.py#L36

2024-03-21 12:10 UTC, superstar54 commented
@unkcpz I tried passing the BASE_IMAGE variable directly through the command line when invoking docker buildx bake, thus allows us to bake the image using a different `aiida-core-version`. But the test failed, and I don't have time to investigate for the moment.

As suggested by @danielhollas , it is fine that this PR only adds the CI test. So I reverted the change on the `build-test-upload`.

2024-03-21 13:12 UTC, danielhollas approved these changes

2024-03-21 15:14 UTC, merged