Feature Spin-Orbit coupling
aiidalab/aiidalab-qe pull request #708
Opened 2024-04-30 12:55 UTC by AndresOrtegaGuerrero

2024-04-30 13:16 UTC, superstar54 commented
Hi @AndresOrtegaGuerrero, Thanks for the work! That's fast, and it's a very important feature. I will look at and test this PR.

2024-05-23 09:39 UTC, superstar54 requested changes
Hi @AndresOrtegaGuerrero , thanks for the great work. Only a minor change is needed.

How would this PR affect the other plugins?

2024-05-23 09:39 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/advanced.py
> +                ("SOC", "soc"),
I suggest using `On` and `Off` as options, just like `Magnetism.`

2024-05-23 09:48 UTC, superstar54 commented on src/aiidalab_qe/common/setup_pseudos.py
> +    f"PseudoDojo/{PSEUDODOJO_VERSION}/PBEsol/FR/stringent/upf",
Does the soc always require the `FR` pseudos?

2024-05-23 10:46 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced.py
> +                ("SOC", "soc"),
@AndresOrtegaGuerrero  like options=[
                ("Off", "wo_soc"),
                ("on", "soc"), ?

2024-05-23 11:40 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/advanced.py
> +                ("SOC", "soc"),
Yes

2024-05-23 19:21 UTC, superstar54 approved these changes
LGTM!

2024-05-23 19:56 UTC, merged