♻️ REFACTOR: defaults and widgets of the steps
aiidalab/aiidalab-qe pull request #72
Opened 2021-06-08 03:06 UTC by mbercx

Fixes #67 

Several changes are made to clean up/refactor/modularize the widgets:

* Move defaults into `.yaml` that is read and used consistently. Use
`importlib_resources` for importing this into modules.
* Try to add consistency between the order of these default in the .yaml
file and how they are ordered in several commands of ths
`SubmitQeAppWorkChainStep`.
* Rename `configs` to `settings` (save for `code`, this was included in
PR #71).
* Fix issue where _both_ `OptionsConfig` (now `AdvancedSettings`) and
`SubmitQeAppWorkChainStep` would intialize a `PseudoFamilySelector`,
leading to issues in correctly assigning the pseudos.

Note that there is a small change in UI: The Materials Settings have
been moved outside of expert mode, since the layman usually can still
understand/decide whether their structure is magnetic/insulating or not.

This also seems to have fixed the issue we were having with the UI
breaking when disabling expert mode on the "Select Codes" tab.

2021-06-10 16:37 UTC, csadorf requested changes

2021-06-10 16:37 UTC, csadorf commented on aiidalab_qe/pseudos.py
> +DEFAULT_PARAMETERS = yaml.safe_load(files(parameters).joinpath("qeapp.yaml").open())
Why not load this directly within the currently `parameters/__init__.py` module and then just import it here?

2021-06-10 16:37 UTC, csadorf commented on aiidalab_qe/pseudos.py
> +    disable = traitlets.Bool()
This should be:
```suggestion
    disabled = traitlets.Bool()
```
And are you actually using that trait?

2021-06-10 16:37 UTC, csadorf commented on aiidalab_qe/pseudos.py
> +    PROTOCOL_DEFAULT = DEFAULT_PARAMETERS["pseudo_family"].split("/")[3]
Why are these class attributes?

2021-06-10 16:37 UTC, csadorf commented on aiidalab_qe/pseudos.py
> -        self.set_pseudo_family.observe(self.set_value_trait, "value")
Why is this removed? Was the function removed?

2021-06-10 16:37 UTC, csadorf commented on aiidalab_qe/steps.py
> +DEFAULT_PARAMETERS = yaml.safe_load(files(parameters).joinpath("qeapp.yaml").open())
Same comment as before.

2021-06-10 16:37 UTC, csadorf commented on aiidalab_qe/steps.py
> +            value=DEFAULT_PARAMETERS["spin_type"].upper(),
I believe it should be possible to use 2-tuples as values for these widgets. The first one corresponds to the display value, and the second one to the actual value.

We could use this to make those dropdowns look a bit nicer, .e.g.: `("Metal", "METAL")` instead of `"METAL"` would appear as "Metal" within the menu, but set the internal value to `METAL`.

Does not need to be applied as part of this PR, just a general suggestion.

2021-06-10 16:37 UTC, csadorf commented on setup.cfg
> +    importlib_resources~=5.1.4
Please make sure that the list of install requirements remains in alphabetical order.

However, what is the reason to use this library? Why not use the one in the standard library https://docs.python.org/3.8/library/importlib.html?highlight=importlib#module-importlib.resources ?

2021-06-10 16:38 UTC, mbercx commented on aiidalab_qe/pseudos.py
> +DEFAULT_PARAMETERS = yaml.safe_load(files(parameters).joinpath("qeapp.yaml").open())
That is cleaner, indeed! 👍

2021-06-10 16:41 UTC, mbercx commented on aiidalab_qe/pseudos.py
> +    disable = traitlets.Bool()
No. But didn't you say we needed the `disabled` trait? 😭 

At some point I thought I knew why, so I reinstated it 😎

2021-06-10 20:18 UTC, mbercx commented on aiidalab_qe/pseudos.py
> +    PROTOCOL_DEFAULT = DEFAULT_PARAMETERS["pseudo_family"].split("/")[3]
Fair, I only use them once. Might just as well directly load them from `DEFAULT_PARAMETERS` when setting the widget `value`.

2021-06-10 20:51 UTC, mbercx commented on aiidalab_qe/steps.py
> +            value=DEFAULT_PARAMETERS["spin_type"].upper(),
Might as well, seems easy enough to fix! Let me see if this works ;)

2021-06-10 21:27 UTC, mbercx commented on setup.cfg
> +    importlib_resources~=5.1.4
Indeed, it seems to work fine for Python 3.8 at least:

```python
import yaml

from importlib import resources
from aiidalab_qe import parameters 

DEFAULT_PARAMETERS = yaml.safe_load(resources.read_text(parameters, "qeapp.yaml"))
```

even looks cleaner to me! Not sure why the backport only recommends "users of Python 3.9 and beyond to use the standard module".

2021-06-10 21:37 UTC, mbercx commented
@csadorf thanks for the review! I think I've covered all your suggestions, but have left some of the comments as unresolved so you can still see my answers to the comments without having to open them.

2021-06-11 06:26 UTC, csadorf commented on aiidalab_qe/pseudos.py
> +    disable = traitlets.Bool()
> No. But didn't you say we needed the `disabled` trait? 😭
> 
> At some point I thought I knew why, so I reinstated it 😎

The `disabled` trait should toggle the widget into a "disabled" state when set to True. What that exactly means depends a little bit on the widget so that's why there is no default implementation for this. Ideally, subsequent steps cannot be modified (i.e. are disabled) until the previous step has been confirmed. Hence why most widgets within the app should have this trait and also implement the corresponding behavior.

2021-06-11 06:31 UTC, csadorf commented on aiidalab_qe/parameters/__init__.py
> +from aiidalab_qe import parameters
This line doesn't make sense as it implies a self-import, doesn't it?

2021-06-11 06:45 UTC, mbercx commented on aiidalab_qe/pseudos.py
> +    disable = traitlets.Bool()
Thanks for the explanation :). Makes sense!

2021-06-11 09:35 UTC, mbercx commented on aiidalab_qe/parameters/__init__.py
> +from aiidalab_qe import parameters
Maybe, but `importlib.resources` needs that import in the way I'm using it.

Typically, you would just use this in a _different_ file though, as I was using it before (i.e. in the `steps.py` and `pseudo.py` files).

I mean, it works like this. Not sure how to make it work otherwise. Probably could, but I don't know how of the top of my head.

2021-06-11 09:39 UTC, mbercx commented on aiidalab_qe/parameters/__init__.py
> +from aiidalab_qe import parameters
Maybe not use `importlib.resources`? But it does seem like a clean way of importing data files.

2021-06-11 09:45 UTC, csadorf commented on aiidalab_qe/parameters/__init__.py
> +from aiidalab_qe import parameters
If it works, it works.

2021-06-11 09:47 UTC, csadorf approved these changes
🚢

2021-06-11 09:48 UTC, mbercx commented
![Screenshot 2021-06-11 at 11 48 16](https://user-images.githubusercontent.com/25607960/121667772-eaf35a00-caaa-11eb-8cc2-66ef286f623e.png)
😭

2021-06-11 09:51 UTC, merged