Implement path for in-app guides
aiidalab/aiidalab-qe pull request #763
Opened 2024-07-03 08:05 UTC by edan-bainglass

Based on #751

This PR adds a mechanism for adding in-app guides meant as example use-cases for users.

In-app guide widgets can be added anywhere as follows:

```python
from aiidalab_qe.app.infobox import InAppGuide

example = InAppGuide(
    children=[
        ipw.HTML("An example in-app guide."),
    ],
    guide_class="example",
)
```

The "child" of the widget can be any other widget supported by `ipywidgets`. This allows developers to customize the content of the guide as they wish. The `example` CSS class provided via `guide_class` marks the widget as part of the "example" guide. This is used for toggling between guides. In addition, the class can be added in the `custom.scss` file under the `static` directory to provide a custom style to the guide.

2024-08-21 14:43 UTC, superstar54 commented
Hi @edan-bainglass , is this PR ready for review? I like the design, and I am looking forward to having it in the APP.

2024-08-21 14:46 UTC, edan-bainglass commented
@superstar54 it is :) The failed tests are due to a chain of yet-to-be-merged PRs all the way back to https://github.com/aiidalab/aiidalab-widgets-base/pull/624, which @danielhollas is reviewing.

2024-08-21 14:54 UTC, superstar54 commented
When reviewing this PR, do I need to switch https://github.com/aiidalab/aiidalab-widgets-base/pull/624?.

2024-08-21 14:56 UTC, edan-bainglass commented
If you're testing locally, then yes.

2024-09-20 04:35 UTC, edan-bainglass commented
@superstar54 @danielhollas rebased on top current state. Please give it a quick look. @superstar54 let me know if I can remove the blocked label.

2024-09-23 15:12 UTC, danielhollas requested changes
Just  a super quick thoughts.

Thanks on working on this @edan-bainglass looks super intriguing. Unfortunately this week is super busy and on Friday I am leaving for two week holiday. But I am looking forward to delving into this work once I get back.

2024-09-23 15:12 UTC, danielhollas commented on src/aiidalab_qe/common/infobox.py
> +    """The `InfoAppGuide` is used to set up in-app guides that may be toggle in unison."""
```suggestion
    """The `InfoAppGuide` is used to set up in-app guides that may be toggled in unison."""
```

2024-09-23 15:12 UTC, danielhollas commented on src/aiidalab_qe/common/infobox.py
> +        `classes` : `list[str]`, optional
Is there an expected use case for adding extra classes? CSS styling?

2024-09-23 15:12 UTC, danielhollas commented on src/aiidalab_qe/app/wrapper.py
> +            file.write("existing user")
I am still not super convinced by this approach. But for now, let's at least fix the naming. I would suggest to name the file something like ".HIDE_IN_APP_GUIDES", (it should have a leading dot, it should just be empty, no need to write to it. Also, I think this should have an absolute path to the home folder, otherwise we are not guaranteed its location right?

2024-09-23 15:12 UTC, danielhollas commented on src/aiidalab_qe/common/infobox.py
> +        `guide_id` : `str`
Is `quide_id` currently used anywhere? What is its purpose?

The name of this is confusing, since below it is added to extra classes, so it's not really an `id` in a CSS sense.

Also, how is the uniqueness enforced. Is it up to the programmer to ensure that these ids are unique in the whole app? Not sure if that is scalable (especially given that there are also external plugins that supposedly could use this as well perhaps?)

2024-09-23 15:15 UTC, edan-bainglass commented on src/aiidalab_qe/common/infobox.py
> +        `classes` : `list[str]`, optional
CSS styling

2024-09-23 15:16 UTC, edan-bainglass commented on src/aiidalab_qe/common/infobox.py
> +        `classes` : `list[str]`, optional
Also, mostly to be consistent with the parent. Liskov principle 🤙

2024-09-23 15:18 UTC, edan-bainglass commented on src/aiidalab_qe/app/wrapper.py
> +            file.write("existing user")
Oops, the first time user stuff shouldn't be there. That's the next PR. Will remove.

2024-09-23 15:27 UTC, edan-bainglass commented on src/aiidalab_qe/common/infobox.py
> +        `guide_id` : `str`
The guide id class is used by JS code to toggle the guide. Suppose you were making a new guide for bands. You'd add these widgets all around with the guide id "bands". You would then add a new guide item in the guides list with the key "bands". Selecting the guide bands will toggle all InAppGuides with the bands id.

Now, regarding collisions with existing classes, I'd have to think about it. If someone introduced the bands class, it might override, or unintentionally add styles. Will think and let you know.

2024-09-23 15:30 UTC, edan-bainglass commented on src/aiidalab_qe/common/infobox.py
> +        `guide_id` : `str`
Naively, I'd enforce that the guide id to be of a certain "unique" format, but I suppose one could always think of a case where that may be accidently used. Not sure how realistic that assumption is. Happy to consider other suggestions.

2024-09-26 06:22 UTC, superstar54 requested changes
Hi @edan-bainglass , thanks for the nice work!

Could you add a section on how to add in-app guide in the docs?

2024-09-26 06:24 UTC, edan-bainglass commented
@superstar54 will do 👍

2024-10-22 11:26 UTC, edan-bainglass commented on src/aiidalab_qe/common/infobox.py
> +        `guide_id` : `str`
@danielhollas back to this PR. Unfortunately, I am not sure at the moment how to handle this. It is actually not an id, so I'll be changing it to `guide_class`. It needs to be a class (and not an id), because multiple widgets will share this guide class, such that they can be toggled in unison. I think it is okay for now.

As for uniqueness, I can maybe append `-guide` to the guide class, so for example `bands-guide-identifier`. This should help a bit. I can make it more unique of course, e.g. `this-is-a-super-unique-guide-class-identifier-for-bands`.

2024-10-22 12:20 UTC, danielhollas commented on src/aiidalab_qe/common/infobox.py
> +        `guide_id` : `str`
>  It is actually not an id, so I'll be changing it to guide_class

Makes sense :+1: 

> As for uniqueness, I can maybe append -guide to the guide class, so for example bands-guide-identifier.
I like the idea to append a string to make this a bit more unique to prevent random clashes in the DOM from outside this widget. Perhaps appending `-in-app-guide`? That's less generic than just "guide" and is consistent with the classname that you're already adding.

However, my concern was more with how to ensure uniqueness within this class itself, e.g. how to prevent programmer from e.g. copy-pasting a snippet that creates an instance of `InAppGuide` and forgetting to change the `guide_class`? QeApp is large enough that one could imagine that making sure all instances of this widget have unique name is non-trivial (not to mention if we ultimately choose to move this widget to AWB). 

Perhaps for this you could create a class variable to would hold a list of these `guide_class` identifiers across all instances, and we could than error out in the `__init__` if we detect a duplicate? Something like

```python
class InAppGuide(InfoBox):
    unique_class_names: set = {}
    
    def __init__(self, guide_class: str, classes: list[str] | None = None, **kwargs):
        if guide_class in unique_class_names:
            raise ValueError()
        unique_class_names.add(guide_class)

```

(just an idea, perhaps I am overthinking it)

2024-10-22 13:17 UTC, edan-bainglass commented on src/aiidalab_qe/common/infobox.py
> +        `guide_id` : `str`
That's interesting. Note that after some discussion, we've decided to pursue a plugin-based approach for these. So a guide for bands will be provided by the bands plugin (along its settings, results, codes, etc.). The guide radio buttons would then be autodetected from entry points. The guide itself would be limited to the components of the plugin. So for bands, the settings panel and results panel(s).

That said, uniqueness should be handled carefully. Will consider your comment 👍

2024-12-10 05:28 UTC, edan-bainglass commented on src/aiidalab_qe/common/infobox.py
> +        `classes` : `list[str]`, optional
In the new implementation, I use extra classes to override the general in-app-guide CSS class. Not sure if this is absolutely necessary though. Will circle back once this is stable.

2024-12-11 12:41 UTC, superstar54 requested changes
Very nice in-app guide! The style is also pretty. I added a few suggestions in the comments.

Could you also add a guide for step 4.

2024-12-11 12:41 UTC, superstar54 commented on src/aiidalab_qe/guides/basic.html
> +      <li>Select resources</li>
```suggestion
      <li>Select resources in the Global resources tab</li>
```

2024-12-11 12:41 UTC, superstar54 commented on src/aiidalab_qe/guides/basic.html
> +      <li>Select <b>Full geometry</b> relaxation</li>
Since "Full geometry" is the default, consider select "Atomic positions"

2024-12-11 12:41 UTC, superstar54 commented on src/aiidalab_qe/guides/basic.html
> +  <div class="alert alert-success">???</div>
Similar to the advacned settings, 
```suggestion
  <div class="alert alert-success">In this walkthrough, we will not modify the pdos settings and proceed with the defaults.</div>
```

2024-12-11 12:41 UTC, superstar54 commented on src/aiidalab_qe/plugins/bands/guides/bands.html
> +      <li>Select resources</li>
Maybe also add a description of the calculation before submitting.

2024-12-11 15:48 UTC, edan-bainglass commented
> Very nice in-app guide! The style is also pretty. I added a few suggestions in the comments.
> 
> Could you also add a guide for step 4.

Thanks @superstar54. Note that I will make no comments regarding the actual content of the guides, as the current content is only a draft to give @giovannipizzi and @cpignedoli a sense of how it works. I will work with them in an immediately following PR to iron out the actual content, at which point, we will also cover step 4 🙂

Since all your comments above ARE regarding content, I take it you approve of the mechanism itself. Per our discussion, I will update the PR to handle uniqueness as suggested in the PR description.

2024-12-11 16:47 UTC, danielhollas commented
> Per our discussion, I will update the PR to handle uniqueness as suggested in the PR description.

LMK when you're done with that and I can have a final look (but feel free to merge anytime / don't feel block by me)

2024-12-16 14:07 UTC, edan-bainglass commented
@superstar54 I added placeholders in step 4 and after the wizard. Again, the text is not important, nor is the placement of the guide widgets. We will update these with one final PR once @cpignedoli and @giovannipizzi agree on the text. No changes in this last commit regarding the mechanism, so if you already agree with it, let me know and we merge 🙏

2024-12-16 14:08 UTC, superstar54 approved these changes
The structure looks good to me! Please ask others for the texts.

2024-12-16 14:23 UTC, edan-bainglass commented
> The structure looks good to me! Please ask others for the texts.

Good. I'm not sure while the docker image is failing though. Can you have a look? 🙏🙏🙏

2024-12-16 15:09 UTC, edan-bainglass commented
@danielhollas this and several other PRs are failing at building the docker image. Could you please have a look? 🙏

2024-12-16 15:22 UTC, danielhollas commented
@edan-bainglass appologies, I will not have time, I am leaving for holidays tomorrow and will be mostly off-line this and next week.

2024-12-16 15:53 UTC, edan-bainglass commented
> @edan-bainglass appologies, I will not have time, I am leaving for holidays tomorrow and will be mostly off-line this and next week.

Okay. No worries. Enjoy the holidays 🙂

2024-12-18 05:23 UTC, merged