Remove arm64 build
aiidalab/aiidalab-qe pull request #776
Opened 2024-07-18 20:02 UTC by danielhollas

Closes #775

2024-07-18 20:24 UTC, danielhollas commented
@unkcpz @superstar54 I need to re-enable the integration tests but otherwise this is good for initial review. Let's get this PR merged before the other. 

(-400 lines of YAML and configuration!)

2024-07-18 22:58 UTC, danielhollas commented
Tests are back and passing.

2024-07-19 07:33 UTC, unkcpz requested changes
Thanks! @danielhollas Just one minor request, then good to go.

2024-07-19 07:33 UTC, unkcpz commented on .github/workflows/docker-build-test-upload.yml
> +                      type=gha,scope=${{ github.workflow }}
Thanks for this!

2024-07-19 07:33 UTC, unkcpz commented on .github/workflows/docker-build-test-upload.yml
> +                      type=match,pattern=v(\d{2}\.\d{2}.\d+.*),group=1
```suggestion
                      type=match,pattern=v(\d{4}\.\d{4}.*),group=1
```

I guess you copy this from aiida-core? :smile:

2024-07-19 08:20 UTC, danielhollas commented on .github/workflows/docker-build-test-upload.yml
> +                      type=match,pattern=v(\d{2}\.\d{2}.\d+.*),group=1
Nope, I actually took it from this repo. :-P I think it is correct, no? The current QeApp version is `24.10.0a1`

2024-07-19 08:50 UTC, unkcpz commented on .github/workflows/docker-build-test-upload.yml
> +                      type=match,pattern=v(\d{2}\.\d{2}.\d+.*),group=1
Ah, true, my bad, I confused with aiidalab-docker-stack :sweat_smile:

2024-07-19 08:53 UTC, unkcpz approved these changes
Approved, thanks! Let's wait tests.

2024-07-19 09:04 UTC, merged