Archive home directory using multi-stage build
aiidalab/aiidalab-qe pull request #781
Opened 2024-07-22 16:55 UTC by danielhollas

2024-07-22 17:19 UTC, danielhollas commented on src/aiidalab_qe/common/setup_codes.py
> +def get_qe_env():
I've created this function so that we don't have to link QE conda env from `/opt/conda` to `~/.conda`.

2024-07-22 22:21 UTC, danielhollas commented
@unkcpz @superstar54 This is hopefully the final iteration of the docker build. :sweat_smile: For easier review, I've split chunks of this PR into 3 extra pull requests that should be reviewed and merged first: #782, #783, #784

The startup takes slighly less than 10s. More speedup is I think possible:
- Updating to Python 3.11
- Speeding up `verdi storage migrate` (I'll open an issue on aiida-core)
- Speeding up verdi in general (not sure if possible)

The size is currently 5.8Gb, but I don't understand where the increase comes from, even though I tried very hard to get rid of it. Let's merge the three PRs first, I'll continue to investigate....

2024-07-23 11:45 UTC, unkcpz requested changes
Thanks @danielhollas! The implementation looks super clear, I have one minor request.

@superstar54, you showed interests to learn more docker stuff. I'd say this is a nice PR to read if you have time.

2024-07-23 11:45 UTC, unkcpz commented on Dockerfile
> +
This also happened in stage 4 but I understand it is not avoidable.

2024-07-23 11:45 UTC, unkcpz commented on Dockerfile
> +# - Archive home folder
Stage 2 and stage 3 better to be merged? It says "to run aiidalab_qe CLI commands" then clear to directly run it in the same stage. I believe the finale size will be the same.

2024-07-23 12:30 UTC, danielhollas commented on Dockerfile
> +
Yes. It is unfortunate that we need to install all the dependencies to install qe codes and pseudos. But `uv` is so fast and I am re-using its cache that in terms of speed it doesn't matter much.

2024-07-23 16:11 UTC, danielhollas commented on Dockerfile
> +# - Archive home folder
Actually, it is beneficial to leave this as a separate stage, because the uv cache can then be immediately used in the final stage, without waiting for the rest of the home_stage build (which is the longest build part). I've rearranged things a bit for better cache utilization. Now, when you modify `Dockerfile` and rebuild, it only takes 10s!

2024-07-23 16:45 UTC, danielhollas commented on Dockerfile
> +    uv pip install --strict --system --compile-bytecode --cache-dir=${UV_CACHE_DIR} ${QE_APP_SRC}
Note that I have added the `--compile-bytecode` parameter. Unlike pip, uv does not compile python files (*.py) into bytecode (*pyc) after installation. 

This increases the image size by ~110Mb, but results in slightly fast App startup when user first launched QeApp.

2024-07-23 17:30 UTC, unkcpz commented
> the image size dropped from 5.8Gb to 5.1Gb (compared to 4.1Gb on main), although I have no idea why.

If you click on a specific tag in dockerhub, you'll see how much size each layer generated: https://hub.docker.com/r/aiidalab/qe/tags
Apparently, you remove upload images to dockerhub ;)

2024-07-25 06:34 UTC, unkcpz commented
Forget to mention, the image was redeployed to the Azure and works as I expected. I think we can merge this and from next week I 'll working on hyperqueue integration.

2024-07-25 06:35 UTC, unkcpz approved these changes

2024-07-25 06:38 UTC, unkcpz commented on .github/workflows/docker-build-test-upload.yml
> +                  # which is stored in the steps.meta.outputs.tags variable
Are you sure this will work for the PR from fork? I think from fork there is no permission to upload anything to the GH package.

2024-07-25 06:39 UTC, unkcpz commented on .github/workflows/docker-build-test-upload.yml
> +                  # which is stored in the steps.meta.outputs.tags variable
Ah, it is in this PR https://github.com/aiidalab/aiidalab-qe/pull/780. There is no pr-780 in GH registry, so I guess it is not working? If so can you revert this change back for this PR?

2024-07-25 08:16 UTC, danielhollas commented on .github/workflows/docker-build-test-upload.yml
> +                  # which is stored in the steps.meta.outputs.tags variable
Yes, you can revert it here and merge. I wanted to check that the fix works for PRs from origin as well.

(we indeed don't upload for PRs from fork, we just load to Docker locally, see the build step above how this is achieved)

2024-07-25 08:17 UTC, danielhollas commented on .github/workflows/docker-build-test-upload.yml
> +                  # which is stored in the steps.meta.outputs.tags variable
To clarify, the fix from #780 is working and #780 can be merged as well. :-)

2024-07-25 17:07 UTC, merged

2024-07-25 17:09 UTC, danielhollas commented on .github/workflows/docker-build-test-upload.yml
> +                  # which is stored in the steps.meta.outputs.tags variable
I've reverted the commit here, the fixed should be merged in #780.

2024-07-25 17:10 UTC, unkcpz commented on .github/workflows/docker-build-test-upload.yml
> +                  # which is stored in the steps.meta.outputs.tags variable
Thanks!

2024-07-31 09:34 UTC, unkcpz commented
> Apparently, you remove upload images to dockerhub ;)

Hi @danielhollas, I guess you miss one comment above?

2024-07-31 10:15 UTC, danielhollas commented
Hi. I am aware, although I should have been more explicit. Does it bring any benefits of publishing to Dockerhub? Given what you told me about this image being most important for demo server deployment, I think that only publishing to ghcr.io is fine?

Publishing to Dockerhub would complicate the GitHub actions workflow, so unless there is a clear benefit I'd advise against it.

2024-07-31 10:20 UTC, unkcpz commented
One thing a bit annoy is I can not find what is available tags in ghcr.io registry, since we have a lot images with pr-xx tags and disgest directly.

2024-07-31 10:28 UTC, danielhollas commented
Yeah, ghcr.io interface is not great. But with the significantly simpler workflow, you don't really need to search for tags, do you? If you look at the workflow, we don't push by digest or commit sha anymore, only pr-xxx on PRs and edge on main, and version when a new tag is pushed.

2024-07-31 11:10 UTC, unkcpz commented
Make sense, I think we want to have highly maintainable repo that involve less outside tools as possible to fit the goal. Would you then mind to add a paragraph to README to tell which tag can be used and is from which branch? Sort of like "Supported tags" section of `aiidalab-docker-stack`.