WIP: Hq as light scheduler
aiidalab/aiidalab-qe pull request #795
Opened 2024-08-12 15:45 UTC by unkcpz

2024-08-12 15:49 UTC, unkcpz commented on src/aiidalab_qe/common/setup_codes.py
> +                )
I think https://github.com/aiidalab/aiidalab-qe/pull/706 bring the footgun, increase the difficulty of maintenance. There are no clear error message when the setup script is fail. I'd argue to revert that change back.
I forget to pass the `computer` argument and the script simply failed with an opaque error message.

2024-08-12 16:39 UTC, superstar54 commented on src/aiidalab_qe/common/setup_codes.py
> +                )
What's the error message? Reverting to the old code really helps debuging the error? In the old code, 
```python
def setup_codes():
    for code_name in CODE_NAMES:
        _setup_code(code_name)
```
it didn't pass the computer too, thus it will probably show the same `opaque` error message using the `verdi` command.

#706 significantly enhances the speed of code setup, which remains beneficial, especially when users install the app from the AppStore, thus, I wouldn't suggest reverting to the old code, instead, we can improve it using `InstalledCode` in the future when we fix the thread problem.
Once we have more information from the error messages and can compare them, we can discuss further.

2024-08-13 13:14 UTC, unkcpz commented on src/aiidalab_qe/common/setup_codes.py
> +                )
If the `verdi` command failed it shows which command I run and I just need to rerun it to see what's wrong. With scripts, nothing I can do, it even not showing the content of the script. Can you check if https://github.com/aiidalab/aiidalab-qe/pull/695 implementation can be done?

2024-08-13 16:04 UTC, unkcpz commented on Dockerfile
> +# TODO: this seems need to do twice
I don't know how to simplify this, pip install in stage 2 above is needed to have the scheduler so the `verdi computer setup` can run. But if I understand correctly, in stage 2 it installed to /opt/conda and will not appeared in stage 3, so I need to do it again in stage 3. Is that correct? @danielhollas

2024-08-13 16:41 UTC, danielhollas commented on Dockerfile
> +     uv pip install --system --strict --compile-bytecode --cache-dir=${UV_CACHE_DIR} aiida-hyperqueue
You don't need to manually clone, you can specify a git dependency to pip directly

```suggestion
     uv pip install --system --strict --compile-bytecode --cache-dir=${UV_CACHE_DIR} "aiida-hyperqueue @ git+https://github.com/aiidateam/aiida-hyperqueue"
```

Now you don't need to have that as a separate step and you can just add the extra dependency to uv invocation on line 43 in build_deps stage.

2024-08-13 16:45 UTC, danielhollas commented on Dockerfile
> +#      uv pip install --system --strict --compile-bytecode --cache-dir=${UV_CACHE_DIR} aiida-hyperqueue
```suggestion
    uv pip install --strict --system --compile-bytecode --cache-dir=${UV_CACHE_DIR} \
     ${QE_APP_SRC} "aiida-hyperqueue @ git+https://github.com/aiidateam/aiida-hyperqueue" 
```

I think this should do the trick

2024-08-13 16:46 UTC, danielhollas commented on Dockerfile
> +# TODO: this seems need to do twice
I think you're correct. But you can significantly simplify this by combining with the previous RUN step. See my other comments.

2024-08-13 22:48 UTC, danielhollas commented on src/aiidalab_qe/common/setup_codes.py
> +                )
I've had in my head an approach for refactoring this logic for some time, I've opened #796 as a first step in that direction.

2024-08-14 04:58 UTC, unkcpz commented on Dockerfile
> +# TODO: this seems need to do twice
I also did a change in this PR, error from running script can be output by printing `err.stderr`.

2024-08-19 13:01 UTC, unkcpz commented
Just find a cache when pre-setting the computer, the issue exist also for the current `localhost`. `LOCALHOST_MPI_PROCS_PER_MACHINE` in `40_prepare-aiida.sh` was triggered in the build phase in QeApp, so the number of procs is the machine that build the image, for the image that released therefore it is `2` the number of CPUs of github action runner I assume. 

In this PR, the same problem faced for the hq computer setup, therefore, I skip the setup for the default N_PROCS and MEM.

2024-09-16 15:20 UTC, danielhollas requested changes
Some quick comments, overall looks reasonable, I'll do a second pass once all the todo's are done.

2024-09-16 15:20 UTC, danielhollas commented on before-notebook.d/41_setup-hq-computer.sh
> +    verdi computer show ${HQ_COMPUTER} || verdi computer setup        \
I don't think you need this branch at all. You can just use the `verdi computer show` command to determine if the computer exists or not.

```suggestion
verdi computer show ${HQ_COMPUTER} || verdi computer setup        \
```

2024-09-16 15:20 UTC, danielhollas commented on before-notebook.d/42_start-hq.sh
> +"
I would recommend running all this setup in the `41_setup-hq-computer.sh` script right after you setup the computer. That way you can ensure that you run it only once (I believe that's what we do in the base image)

2024-09-16 15:20 UTC, danielhollas commented on src/aiidalab_qe/setup/codes.py
> +    # XXX: "qe" in check is not future proof if there are similar packages such as qe-tool, better solution?? JSON output??
I think you can take a look how we do it in aiidalab-docker-stack tests, where I think we use the json output.

2024-09-16 15:20 UTC, danielhollas commented on Dockerfile
>      uv pip install --strict --system --compile-bytecode --cache-dir=${UV_CACHE_DIR} ${QE_APP_SRC}
I think you can just add it here to avoid invoking `uv` twice.
```suggestion
    uv pip install --strict --system --compile-bytecode --cache-dir=${UV_CACHE_DIR} ${QE_APP_SRC} "aiida-hyperqueue@git+https://github.com/aiidateam/aiida-hyperqueue"
```

2024-09-16 15:20 UTC, danielhollas commented on Dockerfile
> +ARG HQ_COMPUTER
Does this line do anything? It looks like you're defining it again on line 130 anyway.

2024-09-16 15:20 UTC, danielhollas commented on Dockerfile
> +     uv pip install --system --strict --compile-bytecode --cache-dir=${UV_CACHE_DIR} \
I don't think you need to compile the bytecode here since this is just a preparatory layer. This should save some time. I would also move this up and merge this with the previous uv invocation as part of `build_deps`. That way `uv` can resolve both packages together and ensure the dependencies are consistent.

```suggestion
     uv pip install --system --strict --cache-dir=${UV_CACHE_DIR} \
```

2024-09-16 19:13 UTC, unkcpz commented on before-notebook.d/41_setup-hq-computer.sh
> +    verdi computer show ${HQ_COMPUTER} || verdi computer setup        \
worth to try, I'll change it.

2024-09-16 19:14 UTC, unkcpz commented on before-notebook.d/42_start-hq.sh
> +"
The problem is the the `CPU_LIMIT` and `MEMORY_LIMIT` is the runtime variables that didn't know during the building stage.

2024-09-16 19:16 UTC, unkcpz commented on Dockerfile
> +ARG HQ_COMPUTER
True! I was going to defined it once and used it for the other stage but it seems not pass to next stage as `ENV`.
Now I hardcode the computer name in two place which is fine but not good enough.

2024-09-17 08:44 UTC, unkcpz commented
@danielhollas all requests addressed.

2024-09-18 13:38 UTC, unkcpz commented on Dockerfile
> +ARG FULL_STACK_VER=edge
```suggestion
ARG FULL_STACK_VER=2024.1023
```

2024-09-20 08:43 UTC, unkcpz commented
I convert back to draft, since test on the production deployment reveal a problem that untar not happened for the presistent volume since it checks home is empty but there will be a `lost+found` folder in k8s deployment. I change to use `.FLAG_HOME_INITIALIZED` flag file. If it works, I'll make it a separated PR.

2024-09-20 12:25 UTC, unkcpz commented
Ready for another review.

2024-09-20 12:28 UTC, unkcpz commented on before-notebook.d/00_untar-home.sh
> +fi
This do the trick, because in the k8s deployment, taring for the empty files like `work` for example has permission issue. Which not cause any problem I can see but it prevent the qeapp folder copy after. I remove it out as a independent operation.

2024-09-25 01:43 UTC, danielhollas approved these changes
Did a super quick review, LGTM. (btw: will be away for the next three weeks)

2024-09-25 01:43 UTC, danielhollas commented on before-notebook.d/00_untar-home.sh
> +if [ ! -e $home/.FLAG_HOME_INITIALIZED ]; then
Not a huge fan of this solution since it seems brittle (user can remove this file). 
I am somewhat confused, why does the previous one not work anymore?
(feel free to ignore, this is just me rambling :D)

2024-09-25 01:43 UTC, danielhollas commented on before-notebook.d/43_start-hq.sh
I didn't look into this file too deeply, might want to get other eyes on this.

2024-09-25 07:00 UTC, unkcpz commented on before-notebook.d/00_untar-home.sh
> +if [ ! -e $home/.FLAG_HOME_INITIALIZED ]; then
Two problems with previous one
1. the left side is `0` and right side is `\0` as str.
2. On the k8s deployment, if the persistent volume is used, it has a `lost+found` folder exist before this script is running.

So another solution I did was `if [ $(ls -A ${home} | wc -l ) -lt 1 ]; then`, but it is more brittle I assume :-p

2024-09-25 07:01 UTC, unkcpz commented on before-notebook.d/43_start-hq.sh
Sure, please do it, I am not in hurry to get this merged.

2024-09-25 07:04 UTC, unkcpz commented
>  (btw: will be away for the next three weeks)

No problem, and congrats with the atomspec paper!

2024-09-25 07:29 UTC, danielhollas commented
Thanks! I've been meaning to announce it on the forum and thank the team but I did not get to it yet. : 🙈

2024-10-17 14:15 UTC, unkcpz commented
I merge this now, since in the demo server checkin meeting we set the next test from @cpignedoli  and @giovannipizzi at next Wednesday. It is good to have an alpha release include this one and many new fixes and use version tag to be deployed in the server.

2024-10-17 14:22 UTC, merged