Feature/degauss widget pdos tab
aiidalab/aiidalab-qe pull request #833
Opened 2024-09-30 09:35 UTC by AndresOrtegaGuerrero

This tab includes a degauss widget to the pdos plugin
This useful for some case where the PDOS calculation doesnt obtain some projections (is a projwfc,x bug , that Giovanni mentioned) , this is a way around to avoid this. 

 ![image](https://github.com/user-attachments/assets/dd3e864b-4097-4cf5-ad27-9428c59a0d47)

2024-10-01 10:47 UTC, cpignedoli requested changes
The PDOS smearing affects both DOS and PDOS so teh name of teh widget shoudl be different.
-it must be NOT active by default
-It should have a default value that provides similar results compared to default tetraedron parameters (so something close to 0.005 for protocol moderate --I tested Au for this--))

2024-10-01 11:15 UTC, cpignedoli commented on src/aiidalab_qe/plugins/pdos/setting.py
> +            value=0.01,
```suggestion
            value=0.005,
```

2024-10-01 11:16 UTC, cpignedoli approved these changes
approved if you merge my new default value

2024-10-02 14:56 UTC, mikibonacci approved these changes
Hi @AndresOrtegaGuerrero, thank you for the PR. 
For me it can be merged, I just left a small comment (nothing relevant actually).

2024-10-02 15:25 UTC, merged