Feature/handling molecules
aiidalab/aiidalab-qe pull request #834
Opened 2024-10-01 08:56 UTC by AndresOrtegaGuerrero

This feature handles #734 

- [ ] Include the option molecule for StructureData editor
- [ ] Band structure calculation should be disabled
- [ ] Cell Optimizatio not available if structure is molecule
- [ ] kpoint_distance should be disable and force [1,1,1]
- [ ] Realoading an old workflow should restore normal behavior of app
- [ ] PdosCalculation Test

Modification to molecule editor
![molecule_editor](https://github.com/user-attachments/assets/e6084c08-16ff-435d-beb1-62ee65ccb0a5)

Cell option no available for Molecule
![cell_opt_option_no_available](https://github.com/user-attachments/assets/4de8d9c4-d2d6-4645-a00f-9b72cf859eac)

Kpoint_Distance disable for Molecules
![kpoint_distance_disable_for_molecules](https://github.com/user-attachments/assets/ca301ff6-3fc9-48b9-ae0a-54227a86a60c)

New Workflow shuold restore behavior 
![new_workflow_or_reset_restore_normal_behavior](https://github.com/user-attachments/assets/48379c89-66ec-42ae-b7f1-5e37a490af4f)

2024-10-01 09:23 UTC, AndresOrtegaGuerrero commented
For this PR We need #833 merged to get the PDOS peaks otherwise is all 0.0

2024-10-01 09:24 UTC, AndresOrtegaGuerrero commented
@edan-bainglass  I included you since it involves widgets and some behaviour of the app , so you can give your opinion for changes or things to consider

2024-10-01 11:44 UTC, cpignedoli approved these changes
tested in combination with #833 
Automatic selection of periodicity will have to follow as a separate PR. The user can then override the automatic selection.

2024-10-02 05:37 UTC, edan-bainglass approved these changes
Okay, all good from me! Note that it will likely all change in my PR - not the behavior, but the implementation, due to the introduction of MVC.

One comment though - I find it odd that a control that modifies the app behavior (disable this, remove that) is somewhat "hidden" deep down (expand step, expand editors, switch tab...). I would consider elevating such controls. I am planning a layout redesign PR after my MVC PR. Should be a fun one!

2024-10-02 05:37 UTC, edan-bainglass commented on src/aiidalab_qe/app/configuration/workflow.py
> +        """Update the relax type options based on the input structure."""
Just giving you a heads up of what to expect in my beast PR, so no worries on changing it here 🙂

2024-10-02 05:43 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/workflow.py
> +        """Update the relax type options based on the input structure."""
Yeah, I know! that part of removing was something that i wanted to check with you , so for molecules we cannot allow the user to do Cell Optimization , however in ipywidgets the ToogleButtons , there is no way to disable one option .. so I opted to go my way around and remove that option for molecules, while making sure it should be present for 1d,2d, and 3d systems.

2024-10-02 05:52 UTC, edan-bainglass commented on src/aiidalab_qe/app/configuration/workflow.py
> +        """Update the relax type options based on the input structure."""
Right, I've encountered the limitation before. Would be nice in general if any option-selection widget allowed disabling certain options. Oh well...

2024-10-02 07:37 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/workflow.py
> +        """Update the relax type options based on the input structure."""
So , i would rename as 
@tl.observe("input_structure")
    def _update_relax_type(self, change):

or keep the name of _on_input_structure_change name , since i need the traitlets to trigger this function ?

2024-10-02 08:55 UTC, edan-bainglass commented on src/aiidalab_qe/app/configuration/workflow.py
> +        """Update the relax type options based on the input structure."""
Again, I wouldn't change it at this stage. But if you did...

```python
@tl.observe("input_structure")
def _on_input_structure_change(self, change):
    self._update_relax_type(change["new"])  # or `change` if you need more from it 

def _update_relax_type(self, input_structure):  # or change (see above)
    ...
```

Sometimes, the triggered handler (`_on_<state>_change`) might trigger several methods. This pattern makes it clear what does are. For example:

```
on structure change:
  do this()
  then do that()
  then finally do the last thing()
```

Easier to maintain. Also, `this`, `that`, etc. are effectively "business logic", so they are moved to the model. Then you get

```
on structure change:
  model.do_this()
  model.do_that()
  model.the_last_thing()
```

**Exception to the rule**: controllers can also modify the view directly. In such a case, the method would not go through the model.

----

Please don't let any of the above block your PR 🙏

2024-10-02 08:57 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/workflow.py
> +        """Update the relax type options based on the input structure."""
ok i will keep the name , and i guess later we sit together for lazy loading :D

2024-10-04 09:44 UTC, AndresOrtegaGuerrero commented
I will wait for the input from @superstar54 or @PNOGillespie  , to know there is no conflict with the XAS or XPS plugins. or extra modifications so is 100% compatible

2024-10-04 10:24 UTC, superstar54 requested changes
Hi @AndresOrtegaGuerrero , thanks for the nice work! I requested a few changes.

- For the kpoints, I think we need to use `gamma_only` for molecule instead of [1, 1, 1], because the former one is faster.



- XAS plugin does not support molecule calculation. I think @PNOGillespie could add a warning message in the XAS GUI if users activate the molecule option (in a future PR).
- XPS plugin supports molecule, and has a molecule option in the XPS GUI  explicitly, I can modify it in a future PR to use the molecule option from this PR. 

So, I think your PR can go ahead without worry XAS and XPS.

2024-10-04 10:24 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/workflow.py
> +            self.properties["bands"].run.disabled = False
`elif` and `else` are duplicated.

2024-10-04 10:24 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/__init__.py
> +
This is not needed because you already linked the `input_structure` to the `input_structure` of the `workchain_settings.`
```suggestion
```

2024-10-04 10:24 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/advanced.py
> +
I suggest not creating the link; instead, modify the `_override_changed` method. In this way, you only need to keep the logic in one place.

2024-10-04 10:42 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced.py
> +
I need this link to be created and removed , so that the kpoints distance is not modify for molecules , if not the override keep it blocked

2024-10-04 10:43 UTC, AndresOrtegaGuerrero commented
> Hi @AndresOrtegaGuerrero , thanks for the nice work! I requested a few changes.
> 
> * For the kpoints, I think we need to use `gamma_only` for molecule instead of [1, 1, 1], because the former one is faster.
> * XAS plugin does not support molecule calculation. I think @PNOGillespie could add a warning message in the XAS GUI if users activate the molecule option (in a future PR).
> * XPS plugin supports molecule, and has a molecule option in the XPS GUI  explicitly, I can modify it in a future PR to use the molecule option from this PR.
> 
> So, I think your PR can go ahead without worry XAS and XPS.

I would not use gamma_only , then there will be problems for vibroscopy app

2024-10-04 10:45 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/__init__.py
> +
I need this trailet here , to remove the cell optimization option to be deleted

2024-10-04 10:50 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced.py
> +
since is liked to the reset()

2024-10-04 10:51 UTC, AndresOrtegaGuerrero commented
> > there will be problems for vibroscopy app
> 
> `gamma_only` is one time faster than [1, 1, 1] and is suggested to be used in a normal case. The plugin could have its logic to handle the molecule case, e.g., the vibroscopy app can override the `gamma_only` to [1, 1,1].
> 
> Another parameter is `assume_isolated`; it's also suggested to use `mt` for the molecular system.

The idea is to set this first and in a follow up set the MT

2024-10-04 10:53 UTC, superstar54 commented
Ok to add MT in another PR.

btw, I can not find the `gamma_only` in the latest docs of pw, :laughing:

2024-10-04 11:01 UTC, AndresOrtegaGuerrero commented
> Ok to add MT in another PR.
> 
> btw, I can not find the `gamma_only` in the latest docs of pw, 😆

and the MT for the assume isolate ,
so it will be K_POINT{gamma}

Yest the best is to set that logic and how it affect other plugins in a follow up PR

2024-10-04 11:39 UTC, superstar54 commented on src/aiidalab_qe/app/configuration/advanced.py
> +
I understand that the link is used to disable the `kpoints_distance` widget. You can achieve this in `_override_changed`. If input_structure is a molecule, the `kpoints_distance` widget is disabled no matter the change is.

2024-10-04 13:29 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/configuration/advanced.py
> +
but the issue, is when uploading a job with pbc that is not molecule , so I tried with the override ,but i realize that since is linked with the reset , it was better to create and remove the link ,

2024-10-05 06:07 UTC, superstar54 approved these changes
LGTM!

2024-10-05 06:48 UTC, merged