Adding the download button for QeAppWorkChains.
aiidalab/aiidalab-qe pull request #850
Opened 2024-10-08 14:19 UTC by mikibonacci

This fixes https://github.com/aiidalab/aiidalab-qe/issues/823

We provide a DownloadDataWidget to download, separately:

- AiiDA archive: export_{node.pk}.aiida
- AiiDA raw data export_{node.pk}_raw.zip

both are zip files.

2024-10-08 14:53 UTC, mikibonacci commented
Hi @superstar54 and @AndresOrtegaGuerrero , this PR is ready for review. 

The main new thing is the `DownloadDataWidget`, in the new `utils` subfolder of the `result` one. I left mostly untouched the implementation of a download output button found in the `WorkChainOutputs`, as I have not fully understood how it works. I preferred to implement a widget which contains both archive and raw_data download buttons. 

Files are downloaded as zip archives. 

A part the implementation, which probably needs to be improved, only one issue: with google chrome the downloads are seen as insecure (I think because they are zip files, and we have http instead of https). 
Could you please confirm that also you have this issue?

Thanks!

2024-10-08 16:10 UTC, AndresOrtegaGuerrero commented
@mikibonacci thank you , do you think we can include the import aiida node , is too much for this PR ?

2024-10-08 16:11 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/utils/download_data.py
> +import base64
Should we have this in common folder instead

2024-10-08 16:37 UTC, mikibonacci commented
Hi @AndresOrtegaGuerrero , thanks for looking at this PR. for the import button, I think I can do a second PR so we don't add too much to this one. But also, I am a bit concerned on what the user may try to upload... for example, maybe they expect that if a PwBaseWorkChain is imported, this will be visible in the app... but this is not always true (true only if we import the whole QeAppWorkChain). Actually, we should be safe enough, as the user typically will just export and import using the app buttons.

To summarize, I think we can do it in another PR, maybe not a critical one. We have already the upload widget from euphonic vibro-app, so should be easy to use similar code and just play with the import API of AiiDA

2024-10-08 16:44 UTC, mikibonacci commented on src/aiidalab_qe/app/result/utils/download_data.py
> +import base64
what do you mean?

2024-10-08 18:50 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/utils/download_data.py
> +import base64
I mean of having this widget in the folder common , but i am not sure , i think having it in results is ok , is just it could be nice to have the widgets in a single folder.

2024-10-08 18:52 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/utils/download_data.py
> +        Download both the phonopy.yaml and fc.hdf5 files.
Maybe lets update this docstring

2024-10-08 18:53 UTC, AndresOrtegaGuerrero commented on src/aiidalab_qe/app/result/utils/download_data.py
> +    def download_raw_data(self, _=None):
these download methods might be be simplified into one ? where you can receive arguments for the desire download ?

2024-10-09 11:10 UTC, mikibonacci commented on src/aiidalab_qe/app/result/utils/download_data.py
> +        Download both the phonopy.yaml and fc.hdf5 files.
oh right, I totally forgot to do it, sorry

2024-10-09 11:11 UTC, mikibonacci commented on src/aiidalab_qe/app/result/utils/download_data.py
> +    def download_raw_data(self, _=None):
yeah I think should not be difficult, I will do it

2024-10-09 13:33 UTC, mikibonacci commented on src/aiidalab_qe/app/result/utils/download_data.py
> +import base64
yeah I see... maybe we can move it later, during the lazy loading refactoring merging

2024-10-10 06:20 UTC, AndresOrtegaGuerrero commented
> Hi @superstar54 and @AndresOrtegaGuerrero , this PR is ready for review.
> 
> The main new thing is the `DownloadDataWidget`, in the new `utils` subfolder of the `result` one. I left mostly untouched the implementation of a download output button found in the `WorkChainOutputs`, as I have not fully understood how it works. I preferred to implement a widget which contains both archive and raw_data download buttons.
> 
> Files are downloaded as zip archives.
> 
> A part the implementation, which probably needs to be improved, only one issue: with google chrome the downloads are seen as insecure (I think because they are zip files, and we have http instead of https). Could you please confirm that also you have this issue?
> 
> Thanks!

One question why the aiida file is saved as a zip?

2024-10-10 08:18 UTC, superstar54 commented on src/aiidalab_qe/app/result/utils/download_data.py
> +        self.download_raw_button = ipw.Button(
It would be good to add a tooltip for both buttons. In the tooltip, explain what the `archive` and `raw` mean.

2024-10-10 08:31 UTC, mikibonacci commented
Hi @AndresOrtegaGuerrero , it is just the standard archive format when you create an archive (see this in [aiida-core create.py file](https://github.com/aiidateam/aiida-core/blob/main/src/aiida/tools/archive/create.py) at line 173. 
Maybe I can just put the button description to be "Download AiiDA archive data" and not "Download AiiDA archive zip data", as it may be a bit misleading (the user may try to unzip the archive file). 

What do you think?

2024-10-10 08:34 UTC, superstar54 commented on src/aiidalab_qe/app/result/utils/download_data.py
> +        It updates the button's description to indicate that the download is in progress,
I would suggest not modifying the description but instead showing this information in another container, e.g., an HTML.

2024-10-18 09:22 UTC, mikibonacci commented on src/aiidalab_qe/app/result/utils/download_data.py
> +        It updates the button's description to indicate that the download is in progress,
Done

2024-10-18 10:06 UTC, superstar54 requested changes
Hi @mikibonacci , thanks for the update. It's a good way to download it in another thread!

Maybe one bug: when download the `raw` data, it always in this status: `Downloading data...`

2024-10-18 10:06 UTC, superstar54 commented on src/aiidalab_qe/app/result/utils/download_data.py
> +            filename = f"export_{self.node.pk}.aiida"
It's would be good to add `qeapp` to the name of the file, e.g.,
```suggestion
            filename = f"export_qeapp_calculation_pk_{self.node.pk}.aiida"
```
Same for the raw data

2024-10-18 10:06 UTC, superstar54 commented on src/aiidalab_qe/app/result/workchain_viewer.py
> +                    children=[self._download_button_widget, title],
It's too compact to show the download widget and the title in an HBox. Please use `VBox`.

2024-10-18 10:30 UTC, mikibonacci commented
Hi @superstar54 , thanks for reviewing the PR. I addressed your valuable comments and suggestions.

However, I don't understand the bug you mention: are the data downloaded in your local machine but the "Downloading data..." still there?

2024-10-18 10:55 UTC, superstar54 commented
In my test, tt's a small calculation, the `aidia` file is downloaded within 5 s. But for the `raw` data, after 10 mins, it still shows `Downloading data...`, and no data is not downloaded.

2024-10-18 14:45 UTC, mikibonacci commented
Hi @superstar54 , I think I solved the issue.  I just disable the raw data download if the ProcessDumper cannot be imported. I have not found a way to catch the error from the second thread (for now).

2024-10-18 14:59 UTC, superstar54 approved these changes
LGTM!

2024-10-21 13:35 UTC, merged