Improved warning messages
aiidalab/aiidalab-qe pull request #862
Opened 2024-10-14 12:15 UTC by mikibonacci

This fixes https://github.com/aiidalab/aiidalab-qe/issues/859

- refactoring of the warnings and suggestions
- comparison also with the cpus_count()

Three cases:
1 (2): run (not) on localhost with large systems (more than 10 atoms or volume larges than 1000 Angstroms) and asking than 4 CPUs:

![Screenshot from 2024-10-14 14-11-24](https://github.com/user-attachments/assets/a39c865a-1dd1-484a-88ca-98d32b3e0b88)

3: run on localhost but asking more than half of the available CPUs
![Screenshot from 2024-10-14 14-11-45](https://github.com/user-attachments/assets/f26adb49-7034-4758-8d1f-b0a67e5c57f8)

Here is the code: https://github.com/mikibonacci/aiidalab-qe/blob/e6d94e1ac485521d36873ce53311751b6d7643f5/src/aiidalab_qe/app/submission/__init__.py#L241

the suggestions are contained in the `suggestions` variable, and the three messages are constructed with respect the logic conditions just below.

Improvement on the messages and the conditions are more than welcome, @giovannipizzi and @cpignedoli !

2024-10-18 09:48 UTC, superstar54 requested changes
Hi @mikibonacci , thanks for the work! I added a few change request.

2024-10-18 09:48 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +            "more_resources": "<li>Increase the resources (CPUs should be equal or more than 4, if possible) </li>",
`should be equal or more than 4` could mislead the user, and let the user think that 4 cpus is enough for a large system. Could you use a simple function to calculate the number of cpus based on the number of atoms and volume?
Assume the maximum number of computation time is ~ 5 days.

2024-10-18 09:48 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +        elif on_localhost and num_cpus > np.ceil(localhost_cpus / 2):
How about showing the warning message when `80%` cpus is used?

2024-10-18 09:48 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +        localhost_cpus = len(os.sched_getaffinity(0))  # or os.cpu_count()
@unkcpz Could you check if this gives a correct number of CPUs in a docker container?

2024-10-18 09:56 UTC, mikibonacci commented on src/aiidalab_qe/app/submission/__init__.py
> +        localhost_cpus = len(os.sched_getaffinity(0))  # or os.cpu_count()
just as a reference: https://github.com/getsentry/self-hosted/issues/2126#issue-1696973715

2024-10-21 14:24 UTC, superstar54 approved these changes
LGTM! Two small change requests.

2024-10-21 14:24 UTC, superstar54 commented on src/aiidalab_qe/app/submission/__init__.py
> +                f"or a significant cell volume ({int(volume)} Å<sup>3</sup>), "
suggest to:
`The selected structure is large, with {num_sites} atoms and a volume of {int(volume)} Å<sup>3</sup>, making it...`

2024-10-21 15:15 UTC, merged