Use try/except to catch error
aiidalab/aiidalab-qe pull request #917
Opened 2024-11-07 07:38 UTC by superstar54

2024-11-07 07:58 UTC, superstar54 commented
Very funny thing: the `pre-commit` and `ruff` conflict with each other.

2024-11-08 09:10 UTC, unkcpz commented on src/aiidalab_qe/setup/codes.py
> +        return False
This may not correct, if the function return from exception, the exception will not propagate up.
The exception was handled by where the function `_install` who is calling `qe_installed()`. 

The change here will shadow docker build to show the exception message when it is failed.

2024-11-08 09:15 UTC, unkcpz commented on src/aiidalab_qe/setup/codes.py
> +        return False
At 2 pm?

2024-11-08 16:40 UTC, superstar54 commented
As suggested by @unkcpz ,  if the cmd to inspect the env fails, we should raise the error and stop the installation.

2024-11-11 08:33 UTC, unkcpz commented on src/aiidalab_qe/setup/codes.py
> +        ) from error
```suggestion
    except Exception as exc:
        raise RuntimeError(
            "Failed to check if Quantum Espresso is installed."
        ) from exc
   else:
       return False  # noqa: TRY300
```

Also for the catched exception, I think there are two types of exceptions we know which are `SubprocessCallError` and `JsonParseError`. You can catch those two and for uncatched exceptions, use raise to propagated it up.

2024-11-11 08:36 UTC, unkcpz commented
> Very funny thing: the pre-commit and ruff conflict with each other.

What you mean `pre-commit` and `ruff` are conflict? We use `ruff` in `pre-commit` as linter.

2024-11-11 08:44 UTC, unkcpz commented
> I added code required by ruff, in this [commit](https://github.com/aiidalab/aiidalab-qe/pull/917/commits/2e98568a73db876f45ca76a6acdfe0c819c3bcf7), but pre-commit deleted it [later](https://github.com/aiidalab/aiidalab-qe/pull/917/commits/bf06b6d6c5cc9b89a4b4ad1b682f06f9c1285373). Then ruff check failed.

Because the else was supposed to add to try..except. If is not correct to early return with an else in the try block.

2024-11-11 08:46 UTC, unkcpz requested changes

2024-11-11 08:46 UTC, unkcpz commented on src/aiidalab_qe/setup/codes.py
> +        ) from error
For TRY300, you can move it to else block, https://docs.astral.sh/ruff/rules/try-consider-else/

2025-01-14 09:38 UTC, edan-bainglass approved these changes
I guess LGTM? Maybe check with @unkcpz.

2025-01-14 09:39 UTC, superstar54 commented
Hi @unkcpz I think the current version works, and we can catch the exception in future work.

2025-01-14 09:41 UTC, merged

2025-01-14 09:45 UTC, superstar54 commented
An issue is opened for further improvement: https://github.com/aiidalab/aiidalab-qe/issues/1092

2025-01-14 09:57 UTC, unkcpz commented
I remember I did discuss with @superstar54 offline. I thought this one is already merged~ So all good.