Add missing features in resource settings tabs
aiidalab/aiidalab-qe pull request #946
Opened 2024-11-26 16:57 UTC by edan-bainglass

Description coming soon :)

2024-11-28 17:48 UTC, edan-bainglass commented
@superstar54 ready for review 🙏

2024-12-05 06:03 UTC, edan-bainglass commented
> @superstar54 ready for review 🙏

Pleeeeeeeeeeeeeeease @superstar54 🙏

2024-12-05 11:06 UTC, superstar54 commented
> @superstar54 ready for review 🙏

Hi @edan-bainglass , my apologies for overlooking your comment earlier. I’m reviewing it now. Thanks for your patience! 🙏

2024-12-05 12:10 UTC, superstar54 commented
One more missing feature: the panel shows a wrong warning message when an HPC is selected. This is probably because it checks the resource before the `model.selected` gets updated, so the app thinks the localhost is used.

In the screenshot, I selected the merlin hpc with 44 cpus for each node, but it give a warning that it only has 28 cpus (which is the number of my localhost).

![Screenshot from 2024-12-05 13-04-59](https://github.com/user-attachments/assets/aea2889d-9cf1-45ff-9358-7b8a0ee62c0a)

2024-12-05 12:24 UTC, superstar54 commented on src/aiidalab_qe/common/panel.py
> +        "global.global_codes",
One concern: the base class hardcodes a dependency on "global.global_codes," where "global" is an identifier defined in the subclass or the context where the class is used.

2024-12-05 12:41 UTC, superstar54 requested changes
Hi @edan-bainglass , thanks for the nice work. 

One issue when loading the previous calculations, the code setting and the override box are not loaded correctly.

2024-12-05 12:41 UTC, superstar54 commented on src/aiidalab_qe/common/panel.py
> +            },
we need to save the `override` value so that it shows correctly when loading a previous calculation.
```suggestion
            },
            "override": self.override,
```

2024-12-05 12:41 UTC, superstar54 commented on tests/test_submit_qe_workchain/test_create_builder_default.yml
> -    override: false
This is needed. See the comment on the `override` value in the `get_model_state` method.

2024-12-06 06:13 UTC, edan-bainglass commented on src/aiidalab_qe/common/panel.py
> +        "global.global_codes",
Yeah, this is not great. It appears to be non-breaking, as linking a model's trait to its own same trait does not raise an error and also doesn't do anything. However, it is still a thorn in principal.

Two ways to decouple:
1. Make the global panel unique. I don't like this - regardless of its special treatment, it IS conceptually a resources panel
2. Link the dependency explicitly during plugin discovery (in `_fetch_plugin_resource_settings`) rather than via the `_link_model` method:
```python
global_model = self._model.get_model("global")
... # then later in the for loop...
self._model.add_model(identifier, model)
tl.dlink(
    (global_model, "global_codes"),
    (model, "global_codes"),
)
```
Comments:
- This is the only thing `_link_model` is doing, so by applying the above workaround, we render the method unnecessary
- Other future dependencies between the plugin panels and the global panel may require similar workarounds
---
I'm honestly not too bothered by it. There are more pros than this one conceptual con. But I am open to discussion on the matter.

2024-12-06 06:15 UTC, edan-bainglass commented
> One issue when loading the previous calculations, the code setting and the override box are not loaded correctly.

Thanks @superstar54 for the review. Indeed, I discovered this issue yesterday morning but didn't have much time to think about it. I tried first to understand how `set_model_state` works in resource models. I had some questions, but maybe it is best we discuss your implementation in person next week. For now, I'll try to adjust for your other comments, then play with this issue a bit more to see if I can resolve it already 🙂

2024-12-07 13:06 UTC, edan-bainglass commented
> One more missing feature: the panel shows a wrong warning message when an HPC is selected. This is probably because it checks the resource before the `model.selected` gets updated, so the app thinks the localhost is used.
> 
> In the screenshot, I selected the merlin hpc with 44 cpus for each node, but it give a warning that it only has 28 cpus (which is the number of my localhost).

Right, indeed, it appears to be so that the check is done prior to the update of `model.selected`. But I'm having difficulty understanding why this is so. In the global settings panel, we do
```python
    def _render_code_widget(
        self,
        code_model: CodeModel,
        code_widget: QEAppComputationalResourcesWidget,
    ):
        super()._render_code_widget(code_model, code_widget)
        if code_model.default_calc_job_plugin == "quantumespresso.pw":
            code_model.observe(
                self._on_pw_code_resource_change,
                [
                    "num_cpus",
                    "num_nodes",
                    "ntasks_per_node",
                    "cpus_per_task",
                    "max_wallclock_seconds",
                ],
            )
```
where in `super()._render_code_widget(...)`, we set up a two-way link between the dropdown and `selected`. This means in the observation order, `selected` should sync prior to triggering the `_on_pw_code_resource_change` handler. But this is not the case. Not sure why at the moment.

2024-12-08 05:24 UTC, edan-bainglass commented
@superstar54 could you please have a look at my comments? I think this is closer to a solution, but we need to see if it sufficient. My main concern at the moment is the mistimed firing of `check_resources`. I'm still uncertain as to how this is happening.

Note that some part of the code is only there to handle changes in options occurring on the widget side. This happens when one introduces a new code using the "new code setup" button. However, we discussed removing this button in favor of a dedicated notebook for creating new codes. If and when this gets merged, some code introduced in this PR will be removed.

2024-12-08 08:24 UTC, superstar54 commented on src/aiidalab_qe/common/panel.py
> +        "global.global_codes",
Another solution is to keep the dependencies empty in the `ResourceSettingsModel` and create another `PluginResourceSettingsModel` for the plugin, in which we add this `global.global_codes`; in this way, we follow the oop and avoid making `_fetch_plugin_resource_settings` special.

2024-12-08 08:43 UTC, superstar54 commented
Hi @edan-bainglass , thank you for the update. Regarding the dependencies issue, I suggest creating a `PluginResourceSettingsModel` class. For the `check_resources` issue, I don't know the reason either, we need more debugging to find the details.

2024-12-08 09:03 UTC, edan-bainglass commented on src/aiidalab_qe/common/panel.py
> +        "global.global_codes",
Very nice 💪

2024-12-08 11:58 UTC, edan-bainglass commented on src/aiidalab_qe/common/panel.py
> +        "global.global_codes",
Implemented in latest push!

2024-12-08 13:26 UTC, edan-bainglass commented
> Hi @edan-bainglass , thank you for the update. Regarding the dependencies issue, I suggest creating a `PluginResourceSettingsModel` class. For the `check_resources` issue, I don't know the reason either, we need more debugging to find the details.

@superstar54 I found out the issue with `check_resources` misfiring. The observations I set up in the app only come after those set up by the `QEAppComputationalResourcesWidget`. There, the selector's `value` is observed and triggers a change in `num_cpus`, which in turn also syncs up `ntasks_per_node`. As these fire prior to the my links, we see `num_cpus` change before the selector's `value` synchronizes with the model's `selected`. 

I'm afraid there is nothing to be done here short of redesigning `QEAppComputationalResourcesWidget`, which would likely be a minor change.

2024-12-09 09:52 UTC, superstar54 approved these changes
Thanks for the nice work! LGTM!

2024-12-09 10:49 UTC, merged