upgrade qe-plugin , include nbands_factor to PdosWorkChain
aiidalab/aiidalab-qe pull request #965
Opened 2024-12-02 10:54 UTC by AndresOrtegaGuerrero

In this PR , we solve the issue of the PDOS and BandStructure not matching the energies. 

![newplot (1)](https://github.com/user-attachments/assets/1939a484-f2af-45ce-9cf0-02ab020210db)

Now the PDOS and BANDS match

2024-12-02 12:19 UTC, cpignedoli approved these changes
ok from my side

2024-12-03 09:58 UTC, superstar54 requested changes

2024-12-03 09:58 UTC, superstar54 commented on src/aiidalab_qe/plugins/pdos/workchain.py
> +        pdos["nbands_factor"] = orm.Float(3.0)
Suggest to read the value directly from the `PwBandsWorkChain` so that the value always keeps updated with the bands.
```suggestion
        pdos["nbands_factor"] = orm.Float(PwBandsWorkChain.get_protocol_inputs()['nbands_factor'])
```

2024-12-03 11:02 UTC, superstar54 approved these changes
Thanks for the work! LGTM!

2024-12-03 11:04 UTC, merged