Rename job history and convert the button to a link to a new tab
aiidalab/aiidalab-qe pull request #995
Opened 2024-12-18 09:08 UTC by superstar54

Fix https://github.com/aiidalab/aiidalab-qe/issues/996 and https://github.com/aiidalab/aiidalab-qe/issues/997

- Rename `Job history` to `Calculation history`
- Convert the button to a link to a new tab

2024-12-18 10:37 UTC, edan-bainglass commented on src/aiidalab_qe/app/wrapper.py
> +        display(Javascript(f"window.open('{url}', '_blank')"))
See #988. I think this will run into a similar issue.

2024-12-18 10:41 UTC, edan-bainglass requested changes
Thanks @superstar54. Looks good and works on my end. A few comments:

- We'll have to figure out another approach for linking to another notebook to avoid browser pop-up blocker (#988)

- Need a space between Quantum and ESPRESSO in the notebook title
- Could we make the table expand to full page width?

![image](https://github.com/user-attachments/assets/f713b76f-b4b5-4628-b702-7876dc18af1b)

2024-12-18 17:36 UTC, superstar54 commented
Hi @edan-bainglass , thanks for the review.

> Could we make the table expand to full page width?

Do you know how to do this? I tried `ipw.Layout(width="100%")`, but it does not work.

2024-12-19 06:49 UTC, edan-bainglass approved these changes
Excellent. LGTM! Thanks @superstar54. I'll look into the pop-up blocker issue today. Once I have a fix, I can also apply it to your button.

2024-12-19 07:33 UTC, merged